<?php declare(strict_types = 1);

namespace PHPStan\Rules\Arrays;

use PhpParser\Node;
use PHPStan\Analyser\Scope;
use PHPStan\DependencyInjection\RegisteredRule;
use PHPStan\Node\LiteralArrayNode;
use PHPStan\Node\Printer\ExprPrinter;
use PHPStan\Rules\Rule;
use PHPStan\Rules\RuleErrorBuilder;
use PHPStan\Type\ArrayUnpackingHelper;
use PHPStan\Type\Constant\ConstantIntegerType;
use function array_key_first;
use function array_keys;
use function array_search;
use function count;
use function implode;
use function is_bool;
use function is_float;
use function is_int;
use function is_string;
use function max;
use function sprintf;
use function var_export;
use const PHP_INT_MAX;

/**
 * @implements Rule<LiteralArrayNode>
 */
#[RegisteredRule(level: 0)]
final class DuplicateKeysInLiteralArraysRule implements Rule
{

	public function __construct(
		private ExprPrinter $exprPrinter,
		private ArrayUnpackingHelper $arrayUnpackingHelper,
	)
	{
	}

	public function getNodeType(): string
	{
		return LiteralArrayNode::class;
	}

	public function processNode(Node $node, Scope $scope): array
	{
		$duplicateKeys = [];
		$printedValues = [];
		$valueLines = [];

		/**
		 * @var int|false|null $autoGeneratedIndex
		 * - An int value represent the biggest integer used as array key.
		 *   When no key is provided this value + 1 will be used.
		 * - Null is used as initializer instead of 0 to avoid issue with negative keys.
		 * - False means a non-scalar value was encountered and we cannot be sure of the next keys.
		 */
		$autoGeneratedIndex = null;
		$seenKeys = [];
		$seenUnions = [];
		foreach ($node->getItemNodes() as $itemNode) {
			$item = $itemNode->getArrayItem();
			if ($item === null) {
				$autoGeneratedIndex = false;
				continue;
			}

			$key = $item->key;
			if ($item->unpack) {
				if ($autoGeneratedIndex === false) {
					continue;
				}

				if ($autoGeneratedIndex === null) {
					$nextImplicitIndex = 0;
				} elseif ($autoGeneratedIndex === PHP_INT_MAX) {
					$nextImplicitIndex = null;
				} else {
					$nextImplicitIndex = $autoGeneratedIndex + 1;
				}

				// an unpacked item contributes all of its own keys, with its integer
				// keys renumbered starting from the current implicit index
				$keyTypes = $this->arrayUnpackingHelper->getKeyTypes(
					$itemNode->getScope()->getType($item->value),
					$nextImplicitIndex,
				);
				if ($keyTypes === null) {
					$autoGeneratedIndex = false;
					continue;
				}

				foreach ($keyTypes as $unpackedKeyType) {
					if (!$unpackedKeyType instanceof ConstantIntegerType) {
						continue;
					}

					$autoGeneratedIndex = $autoGeneratedIndex === null
						? $unpackedKeyType->getValue()
						: max($autoGeneratedIndex, $unpackedKeyType->getValue());
				}
			} elseif ($key === null) {
				if ($autoGeneratedIndex === false) {
					continue;
				}

				if ($autoGeneratedIndex === null) {
					$autoGeneratedIndex = 0;
					$keyTypes = [new ConstantIntegerType(0)];
				} elseif ($autoGeneratedIndex === PHP_INT_MAX) {
					// PHP throws "Cannot add element to the array as the next
					// element is already occupied" instead of wrapping around.
					$autoGeneratedIndex = false;
					continue;
				} else {
					$keyTypes = [new ConstantIntegerType(++$autoGeneratedIndex)];
				}
			} else {
				$keyType = $itemNode->getScope()->getType($key);
				$arrayKeyValues = $keyType->toArrayKey()->getConstantScalarValues();
				// once the implicit index is unknown an explicit key can't bring it back -
				// the forgotten items might have taken up a higher index than this one
				if ($autoGeneratedIndex !== false && count($arrayKeyValues) === 1 && is_int($arrayKeyValues[0])) {
					$autoGeneratedIndex = $autoGeneratedIndex === null
						? $arrayKeyValues[0]
						: max($autoGeneratedIndex, $arrayKeyValues[0]);
				}

				$keyTypes = [$keyType];
			}

			foreach ($keyTypes as $keyType) {
				$keyValues = $keyType->toArrayKey()->getConstantScalarValues();
				if (count($keyValues) === 0) {
					$autoGeneratedIndex = false;
					continue;
				}

				$duplicate = false;
				$newValues = $keyValues;
				foreach ($newValues as $k => $newValue) {
					if (array_search($newValue, $seenKeys, true) !== false) {
						unset($newValues[$k]);
					}

					if ($newValues === []) {
						$duplicate = true;
						break;
					}
				}

				if ($newValues !== []) {
					if (count($newValues) === 1) {
						$newValue = $newValues[array_key_first($newValues)];
						foreach ($seenUnions as $k => $union) {
							$offset = array_search($newValue, $union, true);
							if ($offset === false) {
								continue;
							}

							unset($seenUnions[$k][$offset]);

							// turn a union into a seen key, when all its elements have been seen
							if (count($seenUnions[$k]) !== 1) {
								continue;
							}

							$seenKeys[] = $seenUnions[$k][array_key_first($seenUnions[$k])];
							unset($seenUnions[$k]);
						}
						$seenKeys[] = $newValue;
					} else {
						$seenUnions[] = $newValues;
					}
				}

				foreach ($keyValues as $value) {
					// Prevent php warning by manually casting array keys
					if (is_bool($value) || is_float($value)) {
						$value = (int) $value;
					} elseif ($value === null) {
						$value = (string) $value;
					}

					$printedValue = $key !== null
						? $this->exprPrinter->printExpr($key)
						: (is_string($value) ? var_export($value, true) : $value);
					$printedValues[$value][] = $printedValue;

					if (!isset($valueLines[$value])) {
						$valueLines[$value] = $item->getStartLine();
					}

					if (!$duplicate) {
						continue;
					}

					$duplicateKeys[$value] = true;
				}
			}
		}

		$messages = [];
		foreach (array_keys($duplicateKeys) as $value) {
			$messages[] = RuleErrorBuilder::message(sprintf(
				'Array has %d %s with value %s (%s).',
				count($printedValues[$value]),
				count($printedValues[$value]) === 1 ? 'duplicate key' : 'duplicate keys',
				var_export($value, true),
				implode(', ', $printedValues[$value]),
			))->identifier('array.duplicateKey')->line($valueLines[$value])->build();
		}

		return $messages;
	}

}
