[files]
extend-exclude = [
    ".git/",
]
ignore-hidden = false

[default.extend-identifiers]
# Known typos
NonRemoveableTypeTrait = "NonRemoveableTypeTrait"
supportsLessOverridenParametersWithVariadic = "supportsLessOverridenParametersWithVariadic"
# API property name
consts = "consts"
# PHP built-in function (alias of is_writable)
is_writeable = "is_writeable"

[default.extend-words]
# override false-positives
Excluder = "Excluder"
