[files]
extend-exclude = [
    ".git/",
]
ignore-hidden = false

[default.extend-identifiers]
# Known typos
NonRemoveableTypeTrait = "NonRemoveableTypeTrait"
supportsLessOverridenParametersWithVariadic = "supportsLessOverridenParametersWithVariadic"
