[files]
extend-exclude = [
    ".git/",
]
ignore-hidden = false

[default.extend-identifiers]
# Known typos
NonRemoveableTypeTrait = "NonRemoveableTypeTrait"
supportsLessOverridenParametersWithVariadic = "supportsLessOverridenParametersWithVariadic"
# API property name
consts = "consts"

[default.extend-words]
# override false-positives
Excluder = "Excluder"
