/* What turbo-ext/bin/generate-declarations.php renders for src/Analyser/MutatingScope.php,
 * kept next to the port while it is differential-only: the generator covers
 * the shadowed classes, and the shadowing commit hands the header to it. */

#ifndef PHPSTANTURBO_MUTATING_SCOPE_DECLARATIONS_H
#define PHPSTANTURBO_MUTATING_SCOPE_DECLARATIONS_H

#include "reg.h"

namespace ptdecl::MutatingScope {

/* the OBJ_PROP_NUM slots of the instance properties the class declares (the inherited ones come first) */
namespace slot {
inline constexpr uint32_t resolvedTypes = 0;
inline constexpr uint32_t nodeCallbackScope = 1;
inline constexpr uint32_t namespace_ = 2;
inline constexpr uint32_t scopeOutOfFirstLevelStatement = 3;
inline constexpr uint32_t scopeWithPromotedNativeTypes = 4;
inline constexpr uint32_t container = 5;
inline constexpr uint32_t scopeFactory = 6;
inline constexpr uint32_t reflectionProvider = 7;
inline constexpr uint32_t initializerExprTypeResolver = 8;
inline constexpr uint32_t expressionTypeResolverExtensions = 9;
inline constexpr uint32_t exprPrinter = 10;
inline constexpr uint32_t typeSpecifier = 11;
inline constexpr uint32_t propertyReflectionFinder = 12;
inline constexpr uint32_t parser = 13;
inline constexpr uint32_t constantResolver = 14;
inline constexpr uint32_t expressionResultStorageStack = 15;
inline constexpr uint32_t context = 16;
inline constexpr uint32_t phpVersion = 17;
inline constexpr uint32_t attributeReflectionFactory = 18;
inline constexpr uint32_t configuredPhpVersionRangeHelper = 19;
inline constexpr uint32_t nodeCallback = 20;
inline constexpr uint32_t declareStrictTypes = 21;
inline constexpr uint32_t function = 22;
inline constexpr uint32_t expressionTypes = 23;
inline constexpr uint32_t nativeExpressionTypes = 24;
inline constexpr uint32_t conditionalExpressions = 25;
inline constexpr uint32_t inClosureBindScopeClasses = 26;
inline constexpr uint32_t anonymousFunctionReflection = 27;
inline constexpr uint32_t inFirstLevelStatement = 28;
inline constexpr uint32_t currentlyAssignedExpressions = 29;
inline constexpr uint32_t currentlyAllowedUndefinedExpressions = 30;
inline constexpr uint32_t inFunctionCallsStack = 31;
inline constexpr uint32_t afterExtractCall = 32;
inline constexpr uint32_t parentScope = 33;
inline constexpr uint32_t nativeTypesPromoted = 34;
inline constexpr uint32_t templateArgumentFrame = 35;
inline constexpr uint32_t templateArgumentConstraints = 36;
} // namespace slot

inline void declareClass(reg::Class &cls)
{
	cls.implements({ "PHPStan\\Analyser\\Scope", "PHPStan\\Analyser\\NodeCallbackInvoker", "PHPStan\\Analyser\\CollectedDataEmitter" });
}

/* the properties the class declares itself, in declaration order (a used trait's come from its registrar) */
inline void declareProperties(reg::Class &cls)
{
	cls.property("globalConstantFetchKeys", ZEND_ACC_PRIVATE | ZEND_ACC_STATIC, reg::PropertyKind::TypedEmptyArray, MAY_BE_ARRAY);
	cls.property("resolvedTypes", ZEND_ACC_PUBLIC, reg::PropertyKind::TypedEmptyArray, MAY_BE_ARRAY);
	cls.property("nodeCallbackScope", ZEND_ACC_PRIVATE, reg::PropertyKind::TypedNull, MAY_BE_NULL, "PHPStan\\Analyser\\MutatingScope");
	cls.property("namespace", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, MAY_BE_NULL | MAY_BE_STRING);
	cls.property("scopeOutOfFirstLevelStatement", ZEND_ACC_PRIVATE, reg::PropertyKind::TypedNull, MAY_BE_NULL, "PHPStan\\Analyser\\MutatingScope");
	cls.property("scopeWithPromotedNativeTypes", ZEND_ACC_PRIVATE, reg::PropertyKind::TypedNull, MAY_BE_NULL, "PHPStan\\Analyser\\MutatingScope");
	cls.property("container", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\DependencyInjection\\Container");
	cls.property("scopeFactory", ZEND_ACC_PROTECTED, reg::PropertyKind::Typed, 0, "PHPStan\\Analyser\\InternalScopeFactory");
	cls.property("reflectionProvider", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\Reflection\\ReflectionProvider");
	cls.property("initializerExprTypeResolver", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\Reflection\\InitializerExprTypeResolver");
	cls.property("expressionTypeResolverExtensions", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\DependencyInjection\\ExtensionsCollection");
	cls.property("exprPrinter", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\Node\\Printer\\ExprPrinter");
	cls.property("typeSpecifier", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\Analyser\\TypeSpecifier");
	cls.property("propertyReflectionFinder", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\Rules\\Properties\\PropertyReflectionFinder");
	cls.property("parser", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\Parser\\Parser");
	cls.property("constantResolver", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\Analyser\\ConstantResolver");
	cls.property("expressionResultStorageStack", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\Analyser\\ExpressionResultStorageStack");
	cls.property("context", ZEND_ACC_PROTECTED, reg::PropertyKind::Typed, 0, "PHPStan\\Analyser\\ScopeContext");
	cls.property("phpVersion", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\Php\\PhpVersion");
	cls.property("attributeReflectionFactory", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\Reflection\\AttributeReflectionFactory");
	cls.property("configuredPhpVersionRangeHelper", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, 0, "PHPStan\\Php\\ConfiguredPhpVersionRangeHelper");
	cls.property("nodeCallback", ZEND_ACC_PRIVATE, reg::PropertyKind::Null, 0);
	cls.property("declareStrictTypes", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, MAY_BE_BOOL);
	cls.property("function", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, MAY_BE_NULL, "PHPStan\\Reflection\\Php\\PhpFunctionFromParserNodeReflection");
	cls.property("expressionTypes", ZEND_ACC_PUBLIC, reg::PropertyKind::Typed, MAY_BE_ARRAY);
	cls.property("nativeExpressionTypes", ZEND_ACC_PROTECTED, reg::PropertyKind::Typed, MAY_BE_ARRAY);
	cls.property("conditionalExpressions", ZEND_ACC_PROTECTED, reg::PropertyKind::Typed, MAY_BE_ARRAY);
	cls.property("inClosureBindScopeClasses", ZEND_ACC_PROTECTED, reg::PropertyKind::Typed, MAY_BE_ARRAY);
	cls.property("anonymousFunctionReflection", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, MAY_BE_NULL, "PHPStan\\Type\\ClosureType");
	cls.property("inFirstLevelStatement", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, MAY_BE_BOOL);
	cls.property("currentlyAssignedExpressions", ZEND_ACC_PROTECTED, reg::PropertyKind::Typed, MAY_BE_ARRAY);
	cls.property("currentlyAllowedUndefinedExpressions", ZEND_ACC_PROTECTED, reg::PropertyKind::Typed, MAY_BE_ARRAY);
	cls.property("inFunctionCallsStack", ZEND_ACC_PUBLIC, reg::PropertyKind::Typed, MAY_BE_ARRAY);
	cls.property("afterExtractCall", ZEND_ACC_PROTECTED, reg::PropertyKind::Typed, MAY_BE_BOOL);
	cls.property("parentScope", ZEND_ACC_PRIVATE, reg::PropertyKind::Typed, MAY_BE_NULL, "PHPStan\\Analyser\\MutatingScope");
	cls.property("nativeTypesPromoted", ZEND_ACC_PUBLIC, reg::PropertyKind::Typed, MAY_BE_BOOL);
	cls.property("templateArgumentFrame", ZEND_ACC_PROTECTED, reg::PropertyKind::Typed, MAY_BE_NULL, "PHPStan\\Analyser\\Generics\\TemplateArgumentFrame");
	cls.property("templateArgumentConstraints", ZEND_ACC_PROTECTED, reg::PropertyKind::Typed, MAY_BE_NULL, "PHPStan\\Analyser\\Generics\\TemplateArgumentConstraints");
}

/* the signatures of the methods the class declares itself (a used trait's are in the trait's header) */
namespace sig {
inline constexpr reg::Arg __construct_args[] = { reg::typed("container", 0, "PHPStan\\DependencyInjection\\Container"), reg::typed("scopeFactory", 0, "PHPStan\\Analyser\\InternalScopeFactory"), reg::typed("reflectionProvider", 0, "PHPStan\\Reflection\\ReflectionProvider"), reg::typed("initializerExprTypeResolver", 0, "PHPStan\\Reflection\\InitializerExprTypeResolver"), reg::typed("expressionTypeResolverExtensions", 0, "PHPStan\\DependencyInjection\\ExtensionsCollection"), reg::typed("exprPrinter", 0, "PHPStan\\Node\\Printer\\ExprPrinter"), reg::typed("typeSpecifier", 0, "PHPStan\\Analyser\\TypeSpecifier"), reg::typed("propertyReflectionFinder", 0, "PHPStan\\Rules\\Properties\\PropertyReflectionFinder"), reg::typed("parser", 0, "PHPStan\\Parser\\Parser"), reg::typed("constantResolver", 0, "PHPStan\\Analyser\\ConstantResolver"), reg::typed("expressionResultStorageStack", 0, "PHPStan\\Analyser\\ExpressionResultStorageStack"), reg::typed("context", 0, "PHPStan\\Analyser\\ScopeContext"), reg::typed("phpVersion", 0, "PHPStan\\Php\\PhpVersion"), reg::typed("attributeReflectionFactory", 0, "PHPStan\\Reflection\\AttributeReflectionFactory"), reg::typed("configuredPhpVersionRangeHelper", 0, "PHPStan\\Php\\ConfiguredPhpVersionRangeHelper"), reg::typed("nodeCallback", 0, nullptr, false, false, "null"), reg::typed("declareStrictTypes", MAY_BE_BOOL, nullptr, false, false, "false"), reg::typed("function", MAY_BE_NULL, "PHPStan\\Reflection\\Php\\PhpFunctionFromParserNodeReflection", false, false, "null"), reg::typed("namespace", MAY_BE_NULL | MAY_BE_STRING, nullptr, false, false, "null"), reg::typed("expressionTypes", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("nativeExpressionTypes", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("conditionalExpressions", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("inClosureBindScopeClasses", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("anonymousFunctionReflection", MAY_BE_NULL, "PHPStan\\Type\\ClosureType", false, false, "null"), reg::typed("inFirstLevelStatement", MAY_BE_BOOL, nullptr, false, false, "true"), reg::typed("currentlyAssignedExpressions", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("currentlyAllowedUndefinedExpressions", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("inFunctionCallsStack", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("afterExtractCall", MAY_BE_BOOL, nullptr, false, false, "false"), reg::typed("parentScope", MAY_BE_NULL, "PHPStan\\Analyser\\MutatingScope", false, false, "null"), reg::typed("nativeTypesPromoted", MAY_BE_BOOL, nullptr, false, false, "false"), reg::typed("templateArgumentFrame", MAY_BE_NULL, "PHPStan\\Analyser\\Generics\\TemplateArgumentFrame", false, false, "null"), reg::typed("templateArgumentConstraints", MAY_BE_NULL, "PHPStan\\Analyser\\Generics\\TemplateArgumentConstraints", false, false, "null") };
inline constexpr reg::Sig __construct = { "__construct", ZEND_ACC_PUBLIC, 15, __construct_args, 33, nullptr };
inline constexpr reg::Arg toNodeCallbackScope_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig toNodeCallbackScope = { "toNodeCallbackScope", ZEND_ACC_PUBLIC, 0, nullptr, 0, &toNodeCallbackScope_return };
inline constexpr reg::Arg toWalkScope_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig toWalkScope = { "toWalkScope", ZEND_ACC_PUBLIC, 0, nullptr, 0, &toWalkScope_return };
inline constexpr reg::Arg toMutatingScope_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig toMutatingScope = { "toMutatingScope", ZEND_ACC_PUBLIC, 0, nullptr, 0, &toMutatingScope_return };
inline constexpr reg::Arg getFile_return = reg::typed("", MAY_BE_STRING);
inline constexpr reg::Sig getFile = { "getFile", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getFile_return };
inline constexpr reg::Arg getFileDescription_return = reg::typed("", MAY_BE_STRING);
inline constexpr reg::Sig getFileDescription = { "getFileDescription", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getFileDescription_return };
inline constexpr reg::Arg isDeclareStrictTypes_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isDeclareStrictTypes = { "isDeclareStrictTypes", ZEND_ACC_PUBLIC, 0, nullptr, 0, &isDeclareStrictTypes_return };
inline constexpr reg::Arg enterDeclareStrictTypes_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterDeclareStrictTypes = { "enterDeclareStrictTypes", ZEND_ACC_PUBLIC, 0, nullptr, 0, &enterDeclareStrictTypes_return };
inline constexpr reg::Arg rememberConstructorExpressions_args[] = { reg::typed("currentExpressionTypes", MAY_BE_ARRAY) };
inline constexpr reg::Arg rememberConstructorExpressions_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig rememberConstructorExpressions = { "rememberConstructorExpressions", ZEND_ACC_PRIVATE, 1, rememberConstructorExpressions_args, 1, &rememberConstructorExpressions_return };
inline constexpr reg::Arg classHasCustomSerialization_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig classHasCustomSerialization = { "classHasCustomSerialization", ZEND_ACC_PRIVATE, 0, nullptr, 0, &classHasCustomSerialization_return };
inline constexpr reg::Arg rememberConstructorScope_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig rememberConstructorScope = { "rememberConstructorScope", ZEND_ACC_PUBLIC, 0, nullptr, 0, &rememberConstructorScope_return };
inline constexpr reg::Arg isReadonlyPropertyFetch_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr\\PropertyFetch"), reg::typed("allowOnlyOnThis", MAY_BE_BOOL) };
inline constexpr reg::Arg isReadonlyPropertyFetch_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isReadonlyPropertyFetch = { "isReadonlyPropertyFetch", ZEND_ACC_PUBLIC, 2, isReadonlyPropertyFetch_args, 2, &isReadonlyPropertyFetch_return };
inline constexpr reg::Arg isInClass_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isInClass = { "isInClass", ZEND_ACC_PUBLIC, 0, nullptr, 0, &isInClass_return };
inline constexpr reg::Arg isInTrait_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isInTrait = { "isInTrait", ZEND_ACC_PUBLIC, 0, nullptr, 0, &isInTrait_return };
inline constexpr reg::Arg getClassReflection_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Reflection\\ClassReflection");
inline constexpr reg::Sig getClassReflection = { "getClassReflection", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getClassReflection_return };
inline constexpr reg::Arg getTraitReflection_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Reflection\\ClassReflection");
inline constexpr reg::Sig getTraitReflection = { "getTraitReflection", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getTraitReflection_return };
inline constexpr reg::Arg getFunction_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Reflection\\Php\\PhpFunctionFromParserNodeReflection");
inline constexpr reg::Sig getFunction = { "getFunction", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getFunction_return };
inline constexpr reg::Arg getFunctionName_return = reg::typed("", MAY_BE_NULL | MAY_BE_STRING);
inline constexpr reg::Sig getFunctionName = { "getFunctionName", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getFunctionName_return };
inline constexpr reg::Arg getNamespace_return = reg::typed("", MAY_BE_NULL | MAY_BE_STRING);
inline constexpr reg::Sig getNamespace = { "getNamespace", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getNamespace_return };
inline constexpr reg::Arg getParentScope_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig getParentScope = { "getParentScope", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getParentScope_return };
inline constexpr reg::Arg canAnyVariableExist_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig canAnyVariableExist = { "canAnyVariableExist", ZEND_ACC_PUBLIC, 0, nullptr, 0, &canAnyVariableExist_return };
inline constexpr reg::Arg afterExtractCall_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig afterExtractCall = { "afterExtractCall", ZEND_ACC_PUBLIC, 0, nullptr, 0, &afterExtractCall_return };
inline constexpr reg::Arg afterClearstatcacheCall_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig afterClearstatcacheCall = { "afterClearstatcacheCall", ZEND_ACC_PUBLIC, 0, nullptr, 0, &afterClearstatcacheCall_return };
inline constexpr reg::Arg afterOpenSslCall_args[] = { reg::typed("openSslFunctionName", MAY_BE_STRING) };
inline constexpr reg::Arg afterOpenSslCall_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig afterOpenSslCall = { "afterOpenSslCall", ZEND_ACC_PUBLIC, 1, afterOpenSslCall_args, 1, &afterOpenSslCall_return };
inline constexpr reg::Arg invalidateVolatileExpressions_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig invalidateVolatileExpressions = { "invalidateVolatileExpressions", ZEND_ACC_PUBLIC, 0, nullptr, 0, &invalidateVolatileExpressions_return };
inline constexpr reg::Arg invalidateExistenceCheckExpressions_args[] = { reg::typed("functionNames", MAY_BE_ARRAY), reg::typed("declaredSymbolName", MAY_BE_NULL | MAY_BE_STRING) };
inline constexpr reg::Arg invalidateExistenceCheckExpressions_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig invalidateExistenceCheckExpressions = { "invalidateExistenceCheckExpressions", ZEND_ACC_PUBLIC, 2, invalidateExistenceCheckExpressions_args, 2, &invalidateExistenceCheckExpressions_return };
inline constexpr reg::Arg hasVariableType_args[] = { reg::typed("variableName", MAY_BE_STRING) };
inline constexpr reg::Arg hasVariableType_return = reg::typed("", 0, "PHPStan\\TrinaryLogic");
inline constexpr reg::Sig hasVariableType = { "hasVariableType", ZEND_ACC_PUBLIC, 1, hasVariableType_args, 1, &hasVariableType_return };
inline constexpr reg::Arg getVariableType_args[] = { reg::typed("variableName", MAY_BE_STRING) };
inline constexpr reg::Arg getVariableType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getVariableType = { "getVariableType", ZEND_ACC_PUBLIC, 1, getVariableType_args, 1, &getVariableType_return };
inline constexpr reg::Arg getDefinedVariables_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig getDefinedVariables = { "getDefinedVariables", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getDefinedVariables_return };
inline constexpr reg::Arg getMaybeDefinedVariables_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig getMaybeDefinedVariables = { "getMaybeDefinedVariables", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getMaybeDefinedVariables_return };
inline constexpr reg::Arg findPossiblyImpureCallDescriptions_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg findPossiblyImpureCallDescriptions_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig findPossiblyImpureCallDescriptions = { "findPossiblyImpureCallDescriptions", ZEND_ACC_PUBLIC, 1, findPossiblyImpureCallDescriptions_args, 1, &findPossiblyImpureCallDescriptions_return };
inline constexpr reg::Arg isGlobalVariable_args[] = { reg::typed("variableName", MAY_BE_STRING) };
inline constexpr reg::Arg isGlobalVariable_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isGlobalVariable = { "isGlobalVariable", ZEND_ACC_PRIVATE, 1, isGlobalVariable_args, 1, &isGlobalVariable_return };
inline constexpr reg::Arg hasConstant_args[] = { reg::typed("name", 0, "PhpParser\\Node\\Name") };
inline constexpr reg::Arg hasConstant_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig hasConstant = { "hasConstant", ZEND_ACC_PUBLIC, 1, hasConstant_args, 1, &hasConstant_return };
inline constexpr reg::Arg fileHasCompilerHaltStatementCalls_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig fileHasCompilerHaltStatementCalls = { "fileHasCompilerHaltStatementCalls", ZEND_ACC_PRIVATE, 0, nullptr, 0, &fileHasCompilerHaltStatementCalls_return };
inline constexpr reg::Arg isInAnonymousFunction_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isInAnonymousFunction = { "isInAnonymousFunction", ZEND_ACC_PUBLIC, 0, nullptr, 0, &isInAnonymousFunction_return };
inline constexpr reg::Arg getAnonymousFunctionReflection_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Type\\ClosureType");
inline constexpr reg::Sig getAnonymousFunctionReflection = { "getAnonymousFunctionReflection", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getAnonymousFunctionReflection_return };
inline constexpr reg::Arg getAnonymousFunctionReturnType_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getAnonymousFunctionReturnType = { "getAnonymousFunctionReturnType", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getAnonymousFunctionReturnType_return };
inline constexpr reg::Arg withAnonymousFunctionReflection_args[] = { reg::typed("anonymousFunctionReflection", 0, "PHPStan\\Type\\ClosureType") };
inline constexpr reg::Arg withAnonymousFunctionReflection_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig withAnonymousFunctionReflection = { "withAnonymousFunctionReflection", ZEND_ACC_PUBLIC, 1, withAnonymousFunctionReflection_args, 1, &withAnonymousFunctionReflection_return };
inline constexpr reg::Arg getType_args[] = { reg::typed("node", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg getType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getType = { "getType", ZEND_ACC_PUBLIC, 1, getType_args, 1, &getType_return };
inline constexpr reg::Arg getScopeType_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg getScopeType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getScopeType = { "getScopeType", ZEND_ACC_PUBLIC, 1, getScopeType_args, 1, &getScopeType_return };
inline constexpr reg::Arg getScopeNativeType_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg getScopeNativeType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getScopeNativeType = { "getScopeNativeType", ZEND_ACC_PUBLIC, 1, getScopeNativeType_args, 1, &getScopeNativeType_return };
inline constexpr reg::Arg getNodeKey_args[] = { reg::typed("node", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg getNodeKey_return = reg::typed("", MAY_BE_STRING);
inline constexpr reg::Sig getNodeKey = { "getNodeKey", ZEND_ACC_PUBLIC, 1, getNodeKey_args, 1, &getNodeKey_return };
inline constexpr reg::Arg getExprPrinter_return = reg::typed("", 0, "PHPStan\\Node\\Printer\\ExprPrinter");
inline constexpr reg::Sig getExprPrinter = { "getExprPrinter", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getExprPrinter_return };
inline constexpr reg::Arg duplicateWith_args[] = { reg::typed("expressionTypes", MAY_BE_ARRAY), reg::typed("nativeExpressionTypes", MAY_BE_ARRAY), reg::typed("conditionalExpressions", MAY_BE_ARRAY), reg::typed("currentlyAssignedExpressions", MAY_BE_ARRAY), reg::typed("currentlyAllowedUndefinedExpressions", MAY_BE_ARRAY), reg::typed("inFunctionCallsStack", MAY_BE_ARRAY), reg::typed("inFirstLevelStatement", MAY_BE_BOOL), reg::typed("afterExtractCall", MAY_BE_BOOL) };
inline constexpr reg::Arg duplicateWith_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig duplicateWith = { "duplicateWith", ZEND_ACC_PUBLIC, 8, duplicateWith_args, 8, &duplicateWith_return };
inline constexpr reg::Arg getClosureScopeCacheKey_args[] = { reg::typed("relevantRoots", MAY_BE_NULL | MAY_BE_ARRAY, nullptr, false, false, "null") };
inline constexpr reg::Arg getClosureScopeCacheKey_return = reg::typed("", MAY_BE_STRING);
inline constexpr reg::Sig getClosureScopeCacheKey = { "getClosureScopeCacheKey", ZEND_ACC_PUBLIC, 0, getClosureScopeCacheKey_args, 1, &getClosureScopeCacheKey_return };
inline constexpr reg::Arg exprStringIsRootedIn_args[] = { reg::typed("exprString", MAY_BE_STRING), reg::typed("roots", MAY_BE_ARRAY) };
inline constexpr reg::Arg exprStringIsRootedIn_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig exprStringIsRootedIn = { "exprStringIsRootedIn", ZEND_ACC_PRIVATE | ZEND_ACC_STATIC, 2, exprStringIsRootedIn_args, 2, &exprStringIsRootedIn_return };
inline constexpr reg::Arg resolveType_args[] = { reg::typed("exprString", MAY_BE_STRING), reg::typed("node", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg resolveType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig resolveType = { "resolveType", ZEND_ACC_PRIVATE, 2, resolveType_args, 2, &resolveType_return };
inline constexpr reg::Arg resolveTypeOfNewWorldHandlerNode_args[] = { reg::typed("node", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg resolveTypeOfNewWorldHandlerNode_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig resolveTypeOfNewWorldHandlerNode = { "resolveTypeOfNewWorldHandlerNode", ZEND_ACC_PRIVATE, 1, resolveTypeOfNewWorldHandlerNode_args, 1, &resolveTypeOfNewWorldHandlerNode_return };
inline constexpr reg::Arg getCurrentTypesOfSpecifiedExpr_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg getCurrentTypesOfSpecifiedExpr_return = reg::typed("", MAY_BE_NULL | MAY_BE_ARRAY);
inline constexpr reg::Sig getCurrentTypesOfSpecifiedExpr = { "getCurrentTypesOfSpecifiedExpr", ZEND_ACC_PRIVATE, 1, getCurrentTypesOfSpecifiedExpr_args, 1, &getCurrentTypesOfSpecifiedExpr_return };
inline constexpr reg::Arg specifyTypesOfNewWorldHandlerNode_args[] = { reg::typed("node", 0, "PhpParser\\Node\\Expr"), reg::typed("context", 0, "PHPStan\\Analyser\\TypeSpecifierContext") };
inline constexpr reg::Arg specifyTypesOfNewWorldHandlerNode_return = reg::typed("", 0, "PHPStan\\Analyser\\SpecifiedTypes");
inline constexpr reg::Sig specifyTypesOfNewWorldHandlerNode = { "specifyTypesOfNewWorldHandlerNode", ZEND_ACC_PUBLIC, 2, specifyTypesOfNewWorldHandlerNode_args, 2, &specifyTypesOfNewWorldHandlerNode_return };
inline constexpr reg::Arg obtainResultForNode_args[] = { reg::typed("node", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg obtainResultForNode_return = reg::typed("", 0, "PHPStan\\Analyser\\ExpressionResult");
inline constexpr reg::Sig obtainResultForNode = { "obtainResultForNode", ZEND_ACC_PUBLIC, 1, obtainResultForNode_args, 1, &obtainResultForNode_return };
inline constexpr reg::Arg pushExpressionResultStorage_args[] = { reg::typed("storage", 0, "PHPStan\\Analyser\\ExpressionResultStorage") };
inline constexpr reg::Arg pushExpressionResultStorage_return = reg::typed("", MAY_BE_VOID);
inline constexpr reg::Sig pushExpressionResultStorage = { "pushExpressionResultStorage", ZEND_ACC_PUBLIC, 1, pushExpressionResultStorage_args, 1, &pushExpressionResultStorage_return };
inline constexpr reg::Arg popExpressionResultStorage_return = reg::typed("", MAY_BE_VOID);
inline constexpr reg::Sig popExpressionResultStorage = { "popExpressionResultStorage", ZEND_ACC_PUBLIC, 0, nullptr, 0, &popExpressionResultStorage_return };
inline constexpr reg::Arg findSettledStoredResult_args[] = { reg::typed("node", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg findSettledStoredResult_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Analyser\\ExpressionResult");
inline constexpr reg::Sig findSettledStoredResult = { "findSettledStoredResult", ZEND_ACC_PROTECTED, 1, findSettledStoredResult_args, 1, &findSettledStoredResult_return };
inline constexpr reg::Arg getCurrentExpressionResultStorage_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Analyser\\ExpressionResultStorage");
inline constexpr reg::Sig getCurrentExpressionResultStorage = { "getCurrentExpressionResultStorage", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getCurrentExpressionResultStorage_return };
inline constexpr reg::Arg withTemplateArgumentFrame_args[] = { reg::typed("frame", MAY_BE_NULL, "PHPStan\\Analyser\\Generics\\TemplateArgumentFrame") };
inline constexpr reg::Arg withTemplateArgumentFrame_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig withTemplateArgumentFrame = { "withTemplateArgumentFrame", ZEND_ACC_PUBLIC, 1, withTemplateArgumentFrame_args, 1, &withTemplateArgumentFrame_return };
inline constexpr reg::Arg getCurrentTemplateArgumentFrame_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Analyser\\Generics\\TemplateArgumentFrame");
inline constexpr reg::Sig getCurrentTemplateArgumentFrame = { "getCurrentTemplateArgumentFrame", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getCurrentTemplateArgumentFrame_return };
inline constexpr reg::Arg getTemplateArgumentConstraints_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Analyser\\Generics\\TemplateArgumentConstraints");
inline constexpr reg::Sig getTemplateArgumentConstraints = { "getTemplateArgumentConstraints", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getTemplateArgumentConstraints_return };
inline constexpr reg::Arg withTemplateArgumentConstraints_args[] = { reg::typed("constraints", MAY_BE_NULL, "PHPStan\\Analyser\\Generics\\TemplateArgumentConstraints") };
inline constexpr reg::Arg withTemplateArgumentConstraints_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig withTemplateArgumentConstraints = { "withTemplateArgumentConstraints", ZEND_ACC_PUBLIC, 1, withTemplateArgumentConstraints_args, 1, &withTemplateArgumentConstraints_return };
inline constexpr reg::Arg addTemplateArgumentConstraints_args[] = { reg::typed("constraints", MAY_BE_NULL, "PHPStan\\Analyser\\Generics\\TemplateArgumentConstraints") };
inline constexpr reg::Arg addTemplateArgumentConstraints_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig addTemplateArgumentConstraints = { "addTemplateArgumentConstraints", ZEND_ACC_PUBLIC, 1, addTemplateArgumentConstraints_args, 1, &addTemplateArgumentConstraints_return };
inline constexpr reg::Arg withoutMemoizedTypes_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig withoutMemoizedTypes = { "withoutMemoizedTypes", ZEND_ACC_PUBLIC, 0, nullptr, 0, &withoutMemoizedTypes_return };
inline constexpr reg::Arg getDifferingVariableRoots_args[] = { reg::typed("other", 0, "PHPStan\\Analyser\\MutatingScope") };
inline constexpr reg::Arg getDifferingVariableRoots_return = reg::typed("", MAY_BE_NULL | MAY_BE_ARRAY);
inline constexpr reg::Sig getDifferingVariableRoots = { "getDifferingVariableRoots", ZEND_ACC_PUBLIC, 1, getDifferingVariableRoots_args, 1, &getDifferingVariableRoots_return };
inline constexpr reg::Arg getVariableRootOfExpressionKey_args[] = { reg::typed("key", MAY_BE_STRING) };
inline constexpr reg::Arg getVariableRootOfExpressionKey_return = reg::typed("", MAY_BE_NULL | MAY_BE_STRING);
inline constexpr reg::Sig getVariableRootOfExpressionKey = { "getVariableRootOfExpressionKey", ZEND_ACC_PRIVATE | ZEND_ACC_STATIC, 1, getVariableRootOfExpressionKey_args, 1, &getVariableRootOfExpressionKey_return };
inline constexpr reg::Arg withRecordedStatementDelta_args[] = { reg::typed("recordedEntry", 0, "PHPStan\\Analyser\\MutatingScope"), reg::typed("recordedExit", 0, "PHPStan\\Analyser\\MutatingScope") };
inline constexpr reg::Arg withRecordedStatementDelta_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig withRecordedStatementDelta = { "withRecordedStatementDelta", ZEND_ACC_PUBLIC, 2, withRecordedStatementDelta_args, 2, &withRecordedStatementDelta_return };
inline constexpr reg::Arg applyRecordedHolderDelta_args[] = { reg::typed("current", MAY_BE_ARRAY), reg::typed("recordedEntry", MAY_BE_ARRAY), reg::typed("recordedExit", MAY_BE_ARRAY) };
inline constexpr reg::Arg applyRecordedHolderDelta_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig applyRecordedHolderDelta = { "applyRecordedHolderDelta", ZEND_ACC_PRIVATE | ZEND_ACC_STATIC, 3, applyRecordedHolderDelta_args, 3, &applyRecordedHolderDelta_return };
inline constexpr reg::Arg getNativeType_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg getNativeType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getNativeType = { "getNativeType", ZEND_ACC_PUBLIC, 1, getNativeType_args, 1, &getNativeType_return };
inline constexpr reg::Arg getKeepVoidType_args[] = { reg::typed("node", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg getKeepVoidType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getKeepVoidType = { "getKeepVoidType", ZEND_ACC_PUBLIC, 1, getKeepVoidType_args, 1, &getKeepVoidType_return };
inline constexpr reg::Arg doNotTreatPhpDocTypesAsCertain_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig doNotTreatPhpDocTypesAsCertain = { "doNotTreatPhpDocTypesAsCertain", ZEND_ACC_PUBLIC, 0, nullptr, 0, &doNotTreatPhpDocTypesAsCertain_return };
inline constexpr reg::Arg promoteNativeTypes_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig promoteNativeTypes = { "promoteNativeTypes", ZEND_ACC_PRIVATE, 0, nullptr, 0, &promoteNativeTypes_return };
inline constexpr reg::Arg resolveName_args[] = { reg::typed("name", 0, "PhpParser\\Node\\Name") };
inline constexpr reg::Arg resolveName_return = reg::typed("", MAY_BE_STRING);
inline constexpr reg::Sig resolveName = { "resolveName", ZEND_ACC_PUBLIC, 1, resolveName_args, 1, &resolveName_return };
inline constexpr reg::Arg resolveTypeByName_args[] = { reg::typed("name", 0, "PhpParser\\Node\\Name") };
inline constexpr reg::Arg resolveTypeByName_return = reg::typed("", 0, "PHPStan\\Type\\TypeWithClassName");
inline constexpr reg::Sig resolveTypeByName = { "resolveTypeByName", ZEND_ACC_PUBLIC, 1, resolveTypeByName_args, 1, &resolveTypeByName_return };
inline constexpr reg::Arg getTypeFromValue_args[] = { reg::typed("value", 0) };
inline constexpr reg::Arg getTypeFromValue_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getTypeFromValue = { "getTypeFromValue", ZEND_ACC_PUBLIC, 1, getTypeFromValue_args, 1, &getTypeFromValue_return };
inline constexpr reg::Arg hasExpressionType_args[] = { reg::typed("node", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg hasExpressionType_return = reg::typed("", 0, "PHPStan\\TrinaryLogic");
inline constexpr reg::Sig hasExpressionType = { "hasExpressionType", ZEND_ACC_PUBLIC, 1, hasExpressionType_args, 1, &hasExpressionType_return };
inline constexpr reg::Arg getTrackedExpressionType_args[] = { reg::typed("node", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg getTrackedExpressionType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getTrackedExpressionType = { "getTrackedExpressionType", ZEND_ACC_PUBLIC, 1, getTrackedExpressionType_args, 1, &getTrackedExpressionType_return };
inline constexpr reg::Arg pushInFunctionCall_args[] = { reg::typed("reflection", 0), reg::typed("parameter", MAY_BE_NULL, "PHPStan\\Reflection\\ParameterReflection"), reg::typed("rememberTypes", MAY_BE_BOOL) };
inline constexpr reg::Arg pushInFunctionCall_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig pushInFunctionCall = { "pushInFunctionCall", ZEND_ACC_PUBLIC, 3, pushInFunctionCall_args, 3, &pushInFunctionCall_return };
inline constexpr reg::Arg popInFunctionCall_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig popInFunctionCall = { "popInFunctionCall", ZEND_ACC_PUBLIC, 0, nullptr, 0, &popInFunctionCall_return };
inline constexpr reg::Arg isInClassExists_args[] = { reg::typed("className", MAY_BE_STRING) };
inline constexpr reg::Arg isInClassExists_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isInClassExists = { "isInClassExists", ZEND_ACC_PUBLIC, 1, isInClassExists_args, 1, &isInClassExists_return };
inline constexpr reg::Arg getFunctionCallStack_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig getFunctionCallStack = { "getFunctionCallStack", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getFunctionCallStack_return };
inline constexpr reg::Arg getFunctionCallStackWithParameters_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig getFunctionCallStackWithParameters = { "getFunctionCallStackWithParameters", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getFunctionCallStackWithParameters_return };
inline constexpr reg::Arg isInFunctionExists_args[] = { reg::typed("functionName", MAY_BE_STRING) };
inline constexpr reg::Arg isInFunctionExists_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isInFunctionExists = { "isInFunctionExists", ZEND_ACC_PUBLIC, 1, isInFunctionExists_args, 1, &isInFunctionExists_return };
inline constexpr reg::Arg enterClass_args[] = { reg::typed("classReflection", 0, "PHPStan\\Reflection\\ClassReflection") };
inline constexpr reg::Arg enterClass_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterClass = { "enterClass", ZEND_ACC_PUBLIC, 1, enterClass_args, 1, &enterClass_return };
inline constexpr reg::Arg enterTrait_args[] = { reg::typed("traitReflection", 0, "PHPStan\\Reflection\\ClassReflection") };
inline constexpr reg::Arg enterTrait_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterTrait = { "enterTrait", ZEND_ACC_PUBLIC, 1, enterTrait_args, 1, &enterTrait_return };
inline constexpr reg::Arg enterClassMethod_args[] = { reg::typed("classMethod", 0, "PhpParser\\Node\\Stmt\\ClassMethod"), reg::typed("templateTypeMap", 0, "PHPStan\\Type\\Generic\\TemplateTypeMap"), reg::typed("phpDocParameterTypes", MAY_BE_ARRAY), reg::typed("phpDocReturnType", MAY_BE_NULL, "PHPStan\\Type\\Type"), reg::typed("throwType", MAY_BE_NULL, "PHPStan\\Type\\Type"), reg::typed("deprecatedDescription", MAY_BE_NULL | MAY_BE_STRING), reg::typed("isDeprecated", MAY_BE_BOOL), reg::typed("isInternal", MAY_BE_BOOL), reg::typed("isFinal", MAY_BE_BOOL), reg::typed("isPure", MAY_BE_NULL | MAY_BE_BOOL, nullptr, false, false, "null"), reg::typed("acceptsNamedArguments", MAY_BE_BOOL, nullptr, false, false, "true"), reg::typed("asserts", MAY_BE_NULL, "PHPStan\\Reflection\\Assertions", false, false, "null"), reg::typed("selfOutType", MAY_BE_NULL, "PHPStan\\Type\\Type", false, false, "null"), reg::typed("phpDocComment", MAY_BE_NULL | MAY_BE_STRING, nullptr, false, false, "null"), reg::typed("parameterOutTypes", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("immediatelyInvokedCallableParameters", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("phpDocClosureThisTypeParameters", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("isConstructor", MAY_BE_BOOL, nullptr, false, false, "false"), reg::typed("resolvedPhpDocBlock", MAY_BE_NULL, "PHPStan\\PhpDoc\\ResolvedPhpDocBlock", false, false, "null"), reg::typed("phpDocPureUnlessCallableIsImpureParameters", MAY_BE_ARRAY, nullptr, false, false, "[]") };
inline constexpr reg::Arg enterClassMethod_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterClassMethod = { "enterClassMethod", ZEND_ACC_PUBLIC, 9, enterClassMethod_args, 20, &enterClassMethod_return };
inline constexpr reg::Arg enterPropertyHook_args[] = { reg::typed("hook", 0, "PhpParser\\Node\\PropertyHook"), reg::typed("propertyName", MAY_BE_STRING), reg::typed("nativePropertyTypeNode", MAY_BE_NULL, "PhpParser\\Node\\Identifier|PhpParser\\Node\\Name|PhpParser\\Node\\ComplexType"), reg::typed("phpDocPropertyType", MAY_BE_NULL, "PHPStan\\Type\\Type"), reg::typed("phpDocParameterTypes", MAY_BE_ARRAY), reg::typed("throwType", MAY_BE_NULL, "PHPStan\\Type\\Type"), reg::typed("deprecatedDescription", MAY_BE_NULL | MAY_BE_STRING), reg::typed("isDeprecated", MAY_BE_BOOL), reg::typed("isPure", MAY_BE_NULL | MAY_BE_BOOL), reg::typed("phpDocComment", MAY_BE_NULL | MAY_BE_STRING), reg::typed("resolvedPhpDocBlock", MAY_BE_NULL, "PHPStan\\PhpDoc\\ResolvedPhpDocBlock", false, false, "null") };
inline constexpr reg::Arg enterPropertyHook_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterPropertyHook = { "enterPropertyHook", ZEND_ACC_PUBLIC, 10, enterPropertyHook_args, 11, &enterPropertyHook_return };
inline constexpr reg::Arg transformStaticType_args[] = { reg::typed("type", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg transformStaticType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig transformStaticType = { "transformStaticType", ZEND_ACC_PRIVATE, 1, transformStaticType_args, 1, &transformStaticType_return };
inline constexpr reg::Arg getRealParameterTypes_args[] = { reg::typed("functionLike", 0, "PhpParser\\Node\\FunctionLike") };
inline constexpr reg::Arg getRealParameterTypes_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig getRealParameterTypes = { "getRealParameterTypes", ZEND_ACC_PRIVATE, 1, getRealParameterTypes_args, 1, &getRealParameterTypes_return };
inline constexpr reg::Arg getRealParameterDefaultValues_args[] = { reg::typed("functionLike", 0, "PhpParser\\Node\\FunctionLike") };
inline constexpr reg::Arg getRealParameterDefaultValues_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig getRealParameterDefaultValues = { "getRealParameterDefaultValues", ZEND_ACC_PRIVATE, 1, getRealParameterDefaultValues_args, 1, &getRealParameterDefaultValues_return };
inline constexpr reg::Arg getParameterAttributes_args[] = { reg::typed("functionLike", 0, "PhpParser\\Node\\Stmt\\ClassMethod|PhpParser\\Node\\Stmt\\Function_|PhpParser\\Node\\PropertyHook") };
inline constexpr reg::Arg getParameterAttributes_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig getParameterAttributes = { "getParameterAttributes", ZEND_ACC_PRIVATE, 1, getParameterAttributes_args, 1, &getParameterAttributes_return };
inline constexpr reg::Arg enterFunction_args[] = { reg::typed("function", 0, "PhpParser\\Node\\Stmt\\Function_"), reg::typed("templateTypeMap", 0, "PHPStan\\Type\\Generic\\TemplateTypeMap"), reg::typed("phpDocParameterTypes", MAY_BE_ARRAY), reg::typed("phpDocReturnType", MAY_BE_NULL, "PHPStan\\Type\\Type"), reg::typed("throwType", MAY_BE_NULL, "PHPStan\\Type\\Type"), reg::typed("deprecatedDescription", MAY_BE_NULL | MAY_BE_STRING), reg::typed("isDeprecated", MAY_BE_BOOL), reg::typed("isInternal", MAY_BE_BOOL), reg::typed("isPure", MAY_BE_NULL | MAY_BE_BOOL, nullptr, false, false, "null"), reg::typed("acceptsNamedArguments", MAY_BE_BOOL, nullptr, false, false, "true"), reg::typed("asserts", MAY_BE_NULL, "PHPStan\\Reflection\\Assertions", false, false, "null"), reg::typed("phpDocComment", MAY_BE_NULL | MAY_BE_STRING, nullptr, false, false, "null"), reg::typed("parameterOutTypes", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("immediatelyInvokedCallableParameters", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("phpDocClosureThisTypeParameters", MAY_BE_ARRAY, nullptr, false, false, "[]"), reg::typed("pureUnlessCallableIsImpureParameters", MAY_BE_ARRAY, nullptr, false, false, "[]") };
inline constexpr reg::Arg enterFunction_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterFunction = { "enterFunction", ZEND_ACC_PUBLIC, 8, enterFunction_args, 16, &enterFunction_return };
inline constexpr reg::Arg enterFunctionLike_args[] = { reg::typed("functionReflection", 0, "PHPStan\\Reflection\\Php\\PhpFunctionFromParserNodeReflection"), reg::typed("preserveConstructorScope", MAY_BE_BOOL) };
inline constexpr reg::Arg enterFunctionLike_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterFunctionLike = { "enterFunctionLike", ZEND_ACC_PRIVATE, 2, enterFunctionLike_args, 2, &enterFunctionLike_return };
inline constexpr reg::Arg enterNamespace_args[] = { reg::typed("namespaceName", MAY_BE_STRING) };
inline constexpr reg::Arg enterNamespace_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterNamespace = { "enterNamespace", ZEND_ACC_PUBLIC, 1, enterNamespace_args, 1, &enterNamespace_return };
inline constexpr reg::Arg enterClosureBind_args[] = { reg::typed("thisType", MAY_BE_NULL, "PHPStan\\Type\\Type"), reg::typed("nativeThisType", MAY_BE_NULL, "PHPStan\\Type\\Type"), reg::typed("scopeClasses", MAY_BE_ARRAY) };
inline constexpr reg::Arg enterClosureBind_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterClosureBind = { "enterClosureBind", ZEND_ACC_PUBLIC, 3, enterClosureBind_args, 3, &enterClosureBind_return };
inline constexpr reg::Arg restoreOriginalScopeAfterClosureBind_args[] = { reg::typed("originalScope", 0, "PHPStan\\Analyser\\MutatingScope") };
inline constexpr reg::Arg restoreOriginalScopeAfterClosureBind_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig restoreOriginalScopeAfterClosureBind = { "restoreOriginalScopeAfterClosureBind", ZEND_ACC_PUBLIC, 1, restoreOriginalScopeAfterClosureBind_args, 1, &restoreOriginalScopeAfterClosureBind_return };
inline constexpr reg::Arg restoreThis_args[] = { reg::typed("restoreThisScope", 0, "PHPStan\\Analyser\\MutatingScope") };
inline constexpr reg::Arg restoreThis_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig restoreThis = { "restoreThis", ZEND_ACC_PUBLIC, 1, restoreThis_args, 1, &restoreThis_return };
inline constexpr reg::Arg enterClosureCall_args[] = { reg::typed("thisType", 0, "PHPStan\\Type\\Type"), reg::typed("nativeThisType", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg enterClosureCall_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterClosureCall = { "enterClosureCall", ZEND_ACC_PUBLIC, 2, enterClosureCall_args, 2, &enterClosureCall_return };
inline constexpr reg::Arg isInClosureBind_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isInClosureBind = { "isInClosureBind", ZEND_ACC_PUBLIC, 0, nullptr, 0, &isInClosureBind_return };
inline constexpr reg::Arg withClosureBindScopeClasses_args[] = { reg::typed("scopeClasses", MAY_BE_ARRAY) };
inline constexpr reg::Arg withClosureBindScopeClasses_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig withClosureBindScopeClasses = { "withClosureBindScopeClasses", ZEND_ACC_PUBLIC, 1, withClosureBindScopeClasses_args, 1, &withClosureBindScopeClasses_return };
inline constexpr reg::Arg enterAnonymousFunction_args[] = { reg::typed("closure", 0, "PhpParser\\Node\\Expr\\Closure"), reg::typed("callableParameters", MAY_BE_NULL | MAY_BE_ARRAY), reg::typed("nativeCallableParameters", MAY_BE_NULL | MAY_BE_ARRAY, nullptr, false, false, "null") };
inline constexpr reg::Arg enterAnonymousFunction_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterAnonymousFunction = { "enterAnonymousFunction", ZEND_ACC_PUBLIC, 2, enterAnonymousFunction_args, 3, &enterAnonymousFunction_return };
inline constexpr reg::Arg enterAnonymousFunctionWithoutReflection_args[] = { reg::typed("closure", 0, "PhpParser\\Node\\Expr\\Closure"), reg::typed("callableParameters", MAY_BE_NULL | MAY_BE_ARRAY), reg::typed("nativeCallableParameters", MAY_BE_NULL | MAY_BE_ARRAY) };
inline constexpr reg::Arg enterAnonymousFunctionWithoutReflection_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterAnonymousFunctionWithoutReflection = { "enterAnonymousFunctionWithoutReflection", ZEND_ACC_PUBLIC, 3, enterAnonymousFunctionWithoutReflection_args, 3, &enterAnonymousFunctionWithoutReflection_return };
inline constexpr reg::Arg expressionTypeIsUnchangeable_args[] = { reg::typed("typeHolder", 0, "PHPStan\\Analyser\\ExpressionTypeHolder") };
inline constexpr reg::Arg expressionTypeIsUnchangeable_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig expressionTypeIsUnchangeable = { "expressionTypeIsUnchangeable", ZEND_ACC_PRIVATE, 1, expressionTypeIsUnchangeable_args, 1, &expressionTypeIsUnchangeable_return };
inline constexpr reg::Arg invalidateStaticExpressions_args[] = { reg::typed("expressionTypes", MAY_BE_ARRAY) };
inline constexpr reg::Arg invalidateStaticExpressions_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig invalidateStaticExpressions = { "invalidateStaticExpressions", ZEND_ACC_PRIVATE, 1, invalidateStaticExpressions_args, 1, &invalidateStaticExpressions_return };
inline constexpr reg::Arg enterArrowFunction_args[] = { reg::typed("arrowFunction", 0, "PhpParser\\Node\\Expr\\ArrowFunction"), reg::typed("callableParameters", MAY_BE_NULL | MAY_BE_ARRAY), reg::typed("nativeCallableParameters", MAY_BE_NULL | MAY_BE_ARRAY, nullptr, false, false, "null") };
inline constexpr reg::Arg enterArrowFunction_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterArrowFunction = { "enterArrowFunction", ZEND_ACC_PUBLIC, 2, enterArrowFunction_args, 3, &enterArrowFunction_return };
inline constexpr reg::Arg enterArrowFunctionWithoutReflection_args[] = { reg::typed("arrowFunction", 0, "PhpParser\\Node\\Expr\\ArrowFunction"), reg::typed("callableParameters", MAY_BE_NULL | MAY_BE_ARRAY), reg::typed("nativeCallableParameters", MAY_BE_NULL | MAY_BE_ARRAY) };
inline constexpr reg::Arg enterArrowFunctionWithoutReflection_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterArrowFunctionWithoutReflection = { "enterArrowFunctionWithoutReflection", ZEND_ACC_PUBLIC, 3, enterArrowFunctionWithoutReflection_args, 3, &enterArrowFunctionWithoutReflection_return };
inline constexpr reg::Arg isParameterValueNullable_args[] = { reg::typed("parameter", 0, "PhpParser\\Node\\Param") };
inline constexpr reg::Arg isParameterValueNullable_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isParameterValueNullable = { "isParameterValueNullable", ZEND_ACC_PUBLIC, 1, isParameterValueNullable_args, 1, &isParameterValueNullable_return };
inline constexpr reg::Arg getFunctionType_args[] = { reg::typed("type", 0), reg::typed("isNullable", MAY_BE_BOOL), reg::typed("isVariadic", MAY_BE_BOOL) };
inline constexpr reg::Arg getFunctionType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getFunctionType = { "getFunctionType", ZEND_ACC_PUBLIC, 3, getFunctionType_args, 3, &getFunctionType_return };
inline constexpr reg::Arg getCallableParameterType_args[] = { reg::typed("parameter", 0, "PhpParser\\Node\\Param"), reg::typed("callableParameters", MAY_BE_ARRAY), reg::typed("index", MAY_BE_LONG) };
inline constexpr reg::Arg getCallableParameterType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getCallableParameterType = { "getCallableParameterType", ZEND_ACC_PRIVATE, 3, getCallableParameterType_args, 3, &getCallableParameterType_return };
inline constexpr reg::Arg buildVariadicArrayTypeFromCallableParameters_args[] = { reg::typed("callableParameters", MAY_BE_ARRAY), reg::typed("startIndex", MAY_BE_LONG) };
inline constexpr reg::Arg buildVariadicArrayTypeFromCallableParameters_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig buildVariadicArrayTypeFromCallableParameters = { "buildVariadicArrayTypeFromCallableParameters", ZEND_ACC_PRIVATE, 2, buildVariadicArrayTypeFromCallableParameters_args, 2, &buildVariadicArrayTypeFromCallableParameters_return };
inline constexpr reg::Arg intersectButNotNever_args[] = { reg::typed("nativeType", 0, "PHPStan\\Type\\Type"), reg::typed("inferredType", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg intersectButNotNever_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig intersectButNotNever = { "intersectButNotNever", ZEND_ACC_PUBLIC | ZEND_ACC_STATIC, 2, intersectButNotNever_args, 2, &intersectButNotNever_return };
inline constexpr reg::Arg enterMatch_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr\\Match_"), reg::typed("condType", 0, "PHPStan\\Type\\Type"), reg::typed("condNativeType", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg enterMatch_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterMatch = { "enterMatch", ZEND_ACC_PUBLIC, 3, enterMatch_args, 3, &enterMatch_return };
inline constexpr reg::Arg enterForeach_args[] = { reg::typed("originalScope", 0, "PHPStan\\Analyser\\MutatingScope"), reg::typed("iteratee", 0, "PhpParser\\Node\\Expr"), reg::typed("iterateeType", 0, "PHPStan\\Type\\Type"), reg::typed("nativeIterateeType", 0, "PHPStan\\Type\\Type"), reg::typed("valueName", MAY_BE_STRING), reg::typed("keyName", MAY_BE_NULL | MAY_BE_STRING), reg::typed("valueByRef", MAY_BE_BOOL) };
inline constexpr reg::Arg enterForeach_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterForeach = { "enterForeach", ZEND_ACC_PUBLIC, 7, enterForeach_args, 7, &enterForeach_return };
inline constexpr reg::Arg enterForeachKey_args[] = { reg::typed("originalScope", 0, "PHPStan\\Analyser\\MutatingScope"), reg::typed("iteratee", 0, "PhpParser\\Node\\Expr"), reg::typed("iterateeType", 0, "PHPStan\\Type\\Type"), reg::typed("nativeIterateeType", 0, "PHPStan\\Type\\Type"), reg::typed("keyName", MAY_BE_STRING) };
inline constexpr reg::Arg enterForeachKey_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterForeachKey = { "enterForeachKey", ZEND_ACC_PUBLIC, 5, enterForeachKey_args, 5, &enterForeachKey_return };
inline constexpr reg::Arg enterCatchType_args[] = { reg::typed("catchType", 0, "PHPStan\\Type\\Type"), reg::typed("variableName", MAY_BE_NULL | MAY_BE_STRING) };
inline constexpr reg::Arg enterCatchType_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterCatchType = { "enterCatchType", ZEND_ACC_PUBLIC, 2, enterCatchType_args, 2, &enterCatchType_return };
inline constexpr reg::Arg enterExpressionAssign_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr"), reg::typed("isPlainWrite", MAY_BE_BOOL, nullptr, false, false, "true") };
inline constexpr reg::Arg enterExpressionAssign_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig enterExpressionAssign = { "enterExpressionAssign", ZEND_ACC_PUBLIC, 1, enterExpressionAssign_args, 2, &enterExpressionAssign_return };
inline constexpr reg::Arg exitExpressionAssign_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg exitExpressionAssign_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig exitExpressionAssign = { "exitExpressionAssign", ZEND_ACC_PUBLIC, 1, exitExpressionAssign_args, 1, &exitExpressionAssign_return };
inline constexpr reg::Arg isInExpressionAssign_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg isInExpressionAssign_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isInExpressionAssign = { "isInExpressionAssign", ZEND_ACC_PUBLIC, 1, isInExpressionAssign_args, 1, &isInExpressionAssign_return };
inline constexpr reg::Arg isInWriteExpressionAssign_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg isInWriteExpressionAssign_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isInWriteExpressionAssign = { "isInWriteExpressionAssign", ZEND_ACC_PUBLIC, 1, isInWriteExpressionAssign_args, 1, &isInWriteExpressionAssign_return };
inline constexpr reg::Arg setAllowedUndefinedExpression_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg setAllowedUndefinedExpression_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig setAllowedUndefinedExpression = { "setAllowedUndefinedExpression", ZEND_ACC_PUBLIC, 1, setAllowedUndefinedExpression_args, 1, &setAllowedUndefinedExpression_return };
inline constexpr reg::Arg unsetAllowedUndefinedExpression_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg unsetAllowedUndefinedExpression_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig unsetAllowedUndefinedExpression = { "unsetAllowedUndefinedExpression", ZEND_ACC_PUBLIC, 1, unsetAllowedUndefinedExpression_args, 1, &unsetAllowedUndefinedExpression_return };
inline constexpr reg::Arg isUndefinedExpressionAllowed_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg isUndefinedExpressionAllowed_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isUndefinedExpressionAllowed = { "isUndefinedExpressionAllowed", ZEND_ACC_PUBLIC, 1, isUndefinedExpressionAllowed_args, 1, &isUndefinedExpressionAllowed_return };
inline constexpr reg::Arg assignVariable_args[] = { reg::typed("variableName", MAY_BE_STRING), reg::typed("type", 0, "PHPStan\\Type\\Type"), reg::typed("nativeType", 0, "PHPStan\\Type\\Type"), reg::typed("certainty", 0, "PHPStan\\TrinaryLogic"), reg::typed("intertwinedPropagatedFrom", MAY_BE_ARRAY, nullptr, false, false, "[]") };
inline constexpr reg::Arg assignVariable_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig assignVariable = { "assignVariable", ZEND_ACC_PUBLIC, 4, assignVariable_args, 5, &assignVariable_return };
inline constexpr reg::Arg overwriteExpression_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr"), reg::typed("type", 0, "PHPStan\\Type\\Type"), reg::typed("nativeType", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg overwriteExpression_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig overwriteExpression = { "overwriteExpression", ZEND_ACC_PRIVATE, 3, overwriteExpression_args, 3, &overwriteExpression_return };
inline constexpr reg::Arg resolveIntertwinedAssignedType_args[] = { reg::typed("scope", 0, "PHPStan\\Analyser\\MutatingScope"), reg::typed("rootType", 0, "PHPStan\\Type\\Type"), reg::typed("assignedExpr", 0, "PhpParser\\Node\\Expr"), reg::typed("rootVariableName", MAY_BE_STRING), reg::typed("native", MAY_BE_BOOL) };
inline constexpr reg::Arg resolveIntertwinedAssignedType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig resolveIntertwinedAssignedType = { "resolveIntertwinedAssignedType", ZEND_ACC_PRIVATE, 5, resolveIntertwinedAssignedType_args, 5, &resolveIntertwinedAssignedType_return };
inline constexpr reg::Arg isDimFetchPathReachable_args[] = { reg::typed("scope", 0, "PHPStan\\Analyser\\MutatingScope"), reg::typed("dimFetch", 0, "PhpParser\\Node\\Expr\\ArrayDimFetch") };
inline constexpr reg::Arg isDimFetchPathReachable_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isDimFetchPathReachable = { "isDimFetchPathReachable", ZEND_ACC_PRIVATE, 2, isDimFetchPathReachable_args, 2, &isDimFetchPathReachable_return };
inline constexpr reg::Arg unsetExpression_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg unsetExpression_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig unsetExpression = { "unsetExpression", ZEND_ACC_PRIVATE, 1, unsetExpression_args, 1, &unsetExpression_return };
inline constexpr reg::Arg getStateType_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg getStateType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getStateType = { "getStateType", ZEND_ACC_PUBLIC, 1, getStateType_args, 1, &getStateType_return };
inline constexpr reg::Arg getScopeStateType_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg getScopeStateType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getScopeStateType = { "getScopeStateType", ZEND_ACC_PRIVATE, 1, getScopeStateType_args, 1, &getScopeStateType_return };
inline constexpr reg::Arg getScopeStateNativeType_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg getScopeStateNativeType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getScopeStateNativeType = { "getScopeStateNativeType", ZEND_ACC_PRIVATE, 1, getScopeStateNativeType_args, 1, &getScopeStateNativeType_return };
inline constexpr reg::Arg resolveScopeStateType_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr"), reg::typed("native", MAY_BE_BOOL) };
inline constexpr reg::Arg resolveScopeStateType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig resolveScopeStateType = { "resolveScopeStateType", ZEND_ACC_PRIVATE, 2, resolveScopeStateType_args, 2, &resolveScopeStateType_return };
inline constexpr reg::Arg specifyExpressionType_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr"), reg::typed("type", 0, "PHPStan\\Type\\Type"), reg::typed("nativeType", 0, "PHPStan\\Type\\Type"), reg::typed("certainty", 0, "PHPStan\\TrinaryLogic") };
inline constexpr reg::Arg specifyExpressionType_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig specifyExpressionType = { "specifyExpressionType", ZEND_ACC_PUBLIC, 4, specifyExpressionType_args, 4, &specifyExpressionType_return };
inline constexpr reg::Arg openSpecificationScope_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig openSpecificationScope = { "openSpecificationScope", ZEND_ACC_PRIVATE, 0, nullptr, 0, &openSpecificationScope_return };
inline constexpr reg::Arg isSpecifyExpressionTypeNoop_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr"), reg::typed("type", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg isSpecifyExpressionTypeNoop_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isSpecifyExpressionTypeNoop = { "isSpecifyExpressionTypeNoop", ZEND_ACC_PRIVATE, 2, isSpecifyExpressionTypeNoop_args, 2, &isSpecifyExpressionTypeNoop_return };
inline constexpr reg::Arg specifyExpressionTypeInPlace_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr"), reg::typed("type", 0, "PHPStan\\Type\\Type"), reg::typed("nativeType", 0, "PHPStan\\Type\\Type"), reg::typed("certainty", 0, "PHPStan\\TrinaryLogic") };
inline constexpr reg::Arg specifyExpressionTypeInPlace_return = reg::typed("", MAY_BE_VOID);
inline constexpr reg::Sig specifyExpressionTypeInPlace = { "specifyExpressionTypeInPlace", ZEND_ACC_PRIVATE, 4, specifyExpressionTypeInPlace_args, 4, &specifyExpressionTypeInPlace_return };
inline constexpr reg::Arg assignExpression_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr"), reg::typed("type", 0, "PHPStan\\Type\\Type"), reg::typed("nativeType", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg assignExpression_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig assignExpression = { "assignExpression", ZEND_ACC_PUBLIC, 3, assignExpression_args, 3, &assignExpression_return };
inline constexpr reg::Arg assignInitializedProperty_args[] = { reg::typed("fetchedOnType", 0, "PHPStan\\Type\\Type"), reg::typed("propertyName", MAY_BE_STRING) };
inline constexpr reg::Arg assignInitializedProperty_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig assignInitializedProperty = { "assignInitializedProperty", ZEND_ACC_PUBLIC, 2, assignInitializedProperty_args, 2, &assignInitializedProperty_return };
inline constexpr reg::Arg invalidateExpression_args[] = { reg::typed("expressionToInvalidate", 0, "PhpParser\\Node\\Expr"), reg::typed("requireMoreCharacters", MAY_BE_BOOL, nullptr, false, false, "false"), reg::typed("invalidatingClass", MAY_BE_NULL, "PHPStan\\Reflection\\ClassReflection", false, false, "null"), reg::typed("keepPropertyFetches", MAY_BE_BOOL, nullptr, false, false, "false") };
inline constexpr reg::Arg invalidateExpression_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig invalidateExpression = { "invalidateExpression", ZEND_ACC_PUBLIC, 1, invalidateExpression_args, 4, &invalidateExpression_return };
inline constexpr reg::Arg isPrivatePropertyOfDifferentClass_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr"), reg::typed("invalidatingClass", 0, "PHPStan\\Reflection\\ClassReflection") };
inline constexpr reg::Arg isPrivatePropertyOfDifferentClass_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isPrivatePropertyOfDifferentClass = { "isPrivatePropertyOfDifferentClass", ZEND_ACC_PUBLIC, 2, isPrivatePropertyOfDifferentClass_args, 2, &isPrivatePropertyOfDifferentClass_return };
inline constexpr reg::Arg invalidateMethodsOnExpression_args[] = { reg::typed("expressionToInvalidate", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg invalidateMethodsOnExpression_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig invalidateMethodsOnExpression = { "invalidateMethodsOnExpression", ZEND_ACC_PRIVATE, 1, invalidateMethodsOnExpression_args, 1, &invalidateMethodsOnExpression_return };
inline constexpr reg::Arg setExpressionCertaintyKeepingType_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr"), reg::typed("certainty", 0, "PHPStan\\TrinaryLogic") };
inline constexpr reg::Arg setExpressionCertaintyKeepingType_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig setExpressionCertaintyKeepingType = { "setExpressionCertaintyKeepingType", ZEND_ACC_PRIVATE, 2, setExpressionCertaintyKeepingType_args, 2, &setExpressionCertaintyKeepingType_return };
inline constexpr reg::Arg isComplexUnionType_args[] = { reg::typed("type", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg isComplexUnionType_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isComplexUnionType = { "isComplexUnionType", ZEND_ACC_PRIVATE, 1, isComplexUnionType_args, 1, &isComplexUnionType_return };
inline constexpr reg::Arg addTypeToExpression_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr"), reg::typed("type", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg addTypeToExpression_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig addTypeToExpression = { "addTypeToExpression", ZEND_ACC_PUBLIC, 2, addTypeToExpression_args, 2, &addTypeToExpression_return };
inline constexpr reg::Arg removeTypeFromExpression_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr"), reg::typed("typeToRemove", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg removeTypeFromExpression_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig removeTypeFromExpression = { "removeTypeFromExpression", ZEND_ACC_PUBLIC, 2, removeTypeFromExpression_args, 2, &removeTypeFromExpression_return };
inline constexpr reg::Arg filterByTruthyValue_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg filterByTruthyValue_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig filterByTruthyValue = { "filterByTruthyValue", ZEND_ACC_PUBLIC, 1, filterByTruthyValue_args, 1, &filterByTruthyValue_return };
inline constexpr reg::Arg filterByFalseyValue_args[] = { reg::typed("expr", 0, "PhpParser\\Node\\Expr") };
inline constexpr reg::Arg filterByFalseyValue_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig filterByFalseyValue = { "filterByFalseyValue", ZEND_ACC_PUBLIC, 1, filterByFalseyValue_args, 1, &filterByFalseyValue_return };
inline constexpr reg::Arg applySpecifiedTypes_args[] = { reg::typed("specifiedTypes", 0, "PHPStan\\Analyser\\SpecifiedTypes") };
inline constexpr reg::Arg applySpecifiedTypes_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig applySpecifiedTypes = { "applySpecifiedTypes", ZEND_ACC_PUBLIC, 1, applySpecifiedTypes_args, 1, &applySpecifiedTypes_return };
inline constexpr reg::Arg processConditionalExpressionsAfterSpecifying_args[] = { reg::typed("specifiedExpressions", MAY_BE_ARRAY) };
inline constexpr reg::Arg processConditionalExpressionsAfterSpecifying_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig processConditionalExpressionsAfterSpecifying = { "processConditionalExpressionsAfterSpecifying", ZEND_ACC_PRIVATE, 1, processConditionalExpressionsAfterSpecifying_args, 1, &processConditionalExpressionsAfterSpecifying_return };
inline constexpr reg::Arg getConditionalExpressions_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig getConditionalExpressions = { "getConditionalExpressions", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getConditionalExpressions_return };
inline constexpr reg::Arg addConditionalExpressions_args[] = { reg::typed("exprString", MAY_BE_STRING), reg::typed("conditionalExpressionHolders", MAY_BE_ARRAY) };
inline constexpr reg::Arg addConditionalExpressions_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig addConditionalExpressions = { "addConditionalExpressions", ZEND_ACC_PUBLIC, 2, addConditionalExpressions_args, 2, &addConditionalExpressions_return };
inline constexpr reg::Arg exitFirstLevelStatements_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig exitFirstLevelStatements = { "exitFirstLevelStatements", ZEND_ACC_PUBLIC, 0, nullptr, 0, &exitFirstLevelStatements_return };
inline constexpr reg::Arg isInFirstLevelStatement_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isInFirstLevelStatement = { "isInFirstLevelStatement", ZEND_ACC_PUBLIC, 0, nullptr, 0, &isInFirstLevelStatement_return };
inline constexpr reg::Arg mergeWith_args[] = { reg::typed("otherScope", MAY_BE_NULL, "PHPStan\\Analyser\\MutatingScope"), reg::typed("preserveVacuousConditionals", MAY_BE_BOOL, nullptr, false, false, "false") };
inline constexpr reg::Arg mergeWith_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig mergeWith = { "mergeWith", ZEND_ACC_PUBLIC, 1, mergeWith_args, 2, &mergeWith_return };
inline constexpr reg::Arg mergeWithVariableState_args[] = { reg::typed("otherScope", MAY_BE_NULL, "PHPStan\\Analyser\\MutatingScope"), reg::typed("preserveVacuousConditionals", MAY_BE_BOOL, nullptr, false, false, "false") };
inline constexpr reg::Arg mergeWithVariableState_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig mergeWithVariableState = { "mergeWithVariableState", ZEND_ACC_PRIVATE, 1, mergeWithVariableState_args, 2, &mergeWithVariableState_return };
inline constexpr reg::Arg withoutPreciseClassConstantFetches_args[] = { reg::typed("differingExpressionKeys", MAY_BE_ARRAY), reg::typed("ourExpressionTypes", MAY_BE_ARRAY), reg::typed("theirExpressionTypes", MAY_BE_ARRAY) };
inline constexpr reg::Arg withoutPreciseClassConstantFetches_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig withoutPreciseClassConstantFetches = { "withoutPreciseClassConstantFetches", ZEND_ACC_PRIVATE, 3, withoutPreciseClassConstantFetches_args, 3, &withoutPreciseClassConstantFetches_return };
inline constexpr reg::Arg preserveVacuousConditionalExpressions_args[] = { reg::typed("currentConditionalExpressions", MAY_BE_ARRAY), reg::typed("sourceConditionalExpressions", MAY_BE_ARRAY), reg::typed("otherExpressionTypes", MAY_BE_ARRAY) };
inline constexpr reg::Arg preserveVacuousConditionalExpressions_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig preserveVacuousConditionalExpressions = { "preserveVacuousConditionalExpressions", ZEND_ACC_PRIVATE, 3, preserveVacuousConditionalExpressions_args, 3, &preserveVacuousConditionalExpressions_return };
inline constexpr reg::Arg mergeSameGuardConditionalExpressions_args[] = { reg::typed("currentConditionalExpressions", MAY_BE_ARRAY), reg::typed("ourConditionalExpressions", MAY_BE_ARRAY), reg::typed("theirConditionalExpressions", MAY_BE_ARRAY) };
inline constexpr reg::Arg mergeSameGuardConditionalExpressions_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig mergeSameGuardConditionalExpressions = { "mergeSameGuardConditionalExpressions", ZEND_ACC_PRIVATE, 3, mergeSameGuardConditionalExpressions_args, 3, &mergeSameGuardConditionalExpressions_return };
inline constexpr reg::Arg mergeConditionalExpressions_args[] = { reg::typed("newConditionalExpressions", MAY_BE_ARRAY), reg::typed("existingConditionalExpressions", MAY_BE_ARRAY) };
inline constexpr reg::Arg mergeConditionalExpressions_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig mergeConditionalExpressions = { "mergeConditionalExpressions", ZEND_ACC_PRIVATE, 2, mergeConditionalExpressions_args, 2, &mergeConditionalExpressions_return };
inline constexpr reg::Arg mergeInitializedProperties_args[] = { reg::typed("calledMethodScope", 0, "PHPStan\\Analyser\\MutatingScope") };
inline constexpr reg::Arg mergeInitializedProperties_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig mergeInitializedProperties = { "mergeInitializedProperties", ZEND_ACC_PUBLIC, 1, mergeInitializedProperties_args, 1, &mergeInitializedProperties_return };
inline constexpr reg::Arg processFinallyScope_args[] = { reg::typed("finallyScope", 0, "PHPStan\\Analyser\\MutatingScope"), reg::typed("originalFinallyScope", 0, "PHPStan\\Analyser\\MutatingScope") };
inline constexpr reg::Arg processFinallyScope_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig processFinallyScope = { "processFinallyScope", ZEND_ACC_PUBLIC, 2, processFinallyScope_args, 2, &processFinallyScope_return };
inline constexpr reg::Arg processFinallyScopeVariableTypeHolders_args[] = { reg::typed("ourVariableTypeHolders", MAY_BE_ARRAY), reg::typed("finallyVariableTypeHolders", MAY_BE_ARRAY), reg::typed("originalVariableTypeHolders", MAY_BE_ARRAY) };
inline constexpr reg::Arg processFinallyScopeVariableTypeHolders_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig processFinallyScopeVariableTypeHolders = { "processFinallyScopeVariableTypeHolders", ZEND_ACC_PRIVATE, 3, processFinallyScopeVariableTypeHolders_args, 3, &processFinallyScopeVariableTypeHolders_return };
inline constexpr reg::Arg processClosureScope_args[] = { reg::typed("closureScope", 0, "PHPStan\\Analyser\\MutatingScope"), reg::typed("prevScope", MAY_BE_NULL, "PHPStan\\Analyser\\MutatingScope"), reg::typed("byRefUses", MAY_BE_ARRAY) };
inline constexpr reg::Arg processClosureScope_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig processClosureScope = { "processClosureScope", ZEND_ACC_PUBLIC, 3, processClosureScope_args, 3, &processClosureScope_return };
inline constexpr reg::Arg processAlwaysIterableForeachScopeWithoutPollute_args[] = { reg::typed("finalScope", 0, "PHPStan\\Analyser\\MutatingScope") };
inline constexpr reg::Arg processAlwaysIterableForeachScopeWithoutPollute_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig processAlwaysIterableForeachScopeWithoutPollute = { "processAlwaysIterableForeachScopeWithoutPollute", ZEND_ACC_PUBLIC, 1, processAlwaysIterableForeachScopeWithoutPollute_args, 1, &processAlwaysIterableForeachScopeWithoutPollute_return };
inline constexpr reg::Arg generalizeWith_args[] = { reg::typed("otherScope", 0, "PHPStan\\Analyser\\MutatingScope"), reg::typed("writableVariableNames", MAY_BE_NULL | MAY_BE_ARRAY, nullptr, false, false, "null") };
inline constexpr reg::Arg generalizeWith_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig generalizeWith = { "generalizeWith", ZEND_ACC_PUBLIC, 1, generalizeWith_args, 2, &generalizeWith_return };
inline constexpr reg::Arg generalizeWithVariableState_args[] = { reg::typed("otherScope", 0, "PHPStan\\Analyser\\MutatingScope"), reg::typed("writableVariableNames", MAY_BE_NULL | MAY_BE_ARRAY) };
inline constexpr reg::Arg generalizeWithVariableState_return = reg::typed("", 0, "PHPStan\\Analyser\\MutatingScope");
inline constexpr reg::Sig generalizeWithVariableState = { "generalizeWithVariableState", ZEND_ACC_PRIVATE, 2, generalizeWithVariableState_args, 2, &generalizeWithVariableState_return };
inline constexpr reg::Arg generalizeVariableTypeHolders_args[] = { reg::typed("variableTypeHolders", MAY_BE_ARRAY), reg::typed("otherVariableTypeHolders", MAY_BE_ARRAY), reg::typed("writableVariableNames", MAY_BE_NULL | MAY_BE_ARRAY) };
inline constexpr reg::Arg generalizeVariableTypeHolders_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig generalizeVariableTypeHolders = { "generalizeVariableTypeHolders", ZEND_ACC_PRIVATE, 3, generalizeVariableTypeHolders_args, 3, &generalizeVariableTypeHolders_return };
inline constexpr reg::Arg flattenUnionForGeneralization_args[] = { reg::typed("type", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg flattenUnionForGeneralization_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig flattenUnionForGeneralization = { "flattenUnionForGeneralization", ZEND_ACC_PRIVATE, 1, flattenUnionForGeneralization_args, 1, &flattenUnionForGeneralization_return };
inline constexpr reg::Arg generalizeType_args[] = { reg::typed("a", 0, "PHPStan\\Type\\Type"), reg::typed("b", 0, "PHPStan\\Type\\Type"), reg::typed("depth", MAY_BE_LONG) };
inline constexpr reg::Arg generalizeType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig generalizeType = { "generalizeType", ZEND_ACC_PRIVATE, 3, generalizeType_args, 3, &generalizeType_return };
inline constexpr reg::Arg getArrayDepth_args[] = { reg::typed("type", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg getArrayDepth_return = reg::typed("", MAY_BE_LONG);
inline constexpr reg::Sig getArrayDepth = { "getArrayDepth", ZEND_ACC_PRIVATE | ZEND_ACC_STATIC, 1, getArrayDepth_args, 1, &getArrayDepth_return };
inline constexpr reg::Arg equals_args[] = { reg::typed("otherScope", 0, "PHPStan\\Analyser\\MutatingScope") };
inline constexpr reg::Arg equals_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig equals = { "equals", ZEND_ACC_PUBLIC, 1, equals_args, 1, &equals_return };
inline constexpr reg::Arg compareConditionalExpressions_args[] = { reg::typed("conditionalExpressions", MAY_BE_ARRAY), reg::typed("otherConditionalExpressions", MAY_BE_ARRAY) };
inline constexpr reg::Arg compareConditionalExpressions_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig compareConditionalExpressions = { "compareConditionalExpressions", ZEND_ACC_PRIVATE, 2, compareConditionalExpressions_args, 2, &compareConditionalExpressions_return };
inline constexpr reg::Arg compareVariableTypeHolders_args[] = { reg::typed("variableTypeHolders", MAY_BE_ARRAY), reg::typed("otherVariableTypeHolders", MAY_BE_ARRAY) };
inline constexpr reg::Arg compareVariableTypeHolders_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig compareVariableTypeHolders = { "compareVariableTypeHolders", ZEND_ACC_PRIVATE, 2, compareVariableTypeHolders_args, 2, &compareVariableTypeHolders_return };
inline constexpr reg::Arg canAccessProperty_args[] = { reg::typed("propertyReflection", 0, "PHPStan\\Reflection\\PropertyReflection") };
inline constexpr reg::Arg canAccessProperty_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig canAccessProperty = { "canAccessProperty", ZEND_ACC_PUBLIC, 1, canAccessProperty_args, 1, &canAccessProperty_return };
inline constexpr reg::Arg canReadProperty_args[] = { reg::typed("propertyReflection", 0, "PHPStan\\Reflection\\ExtendedPropertyReflection") };
inline constexpr reg::Arg canReadProperty_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig canReadProperty = { "canReadProperty", ZEND_ACC_PUBLIC, 1, canReadProperty_args, 1, &canReadProperty_return };
inline constexpr reg::Arg canWriteProperty_args[] = { reg::typed("propertyReflection", 0, "PHPStan\\Reflection\\ExtendedPropertyReflection") };
inline constexpr reg::Arg canWriteProperty_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig canWriteProperty = { "canWriteProperty", ZEND_ACC_PUBLIC, 1, canWriteProperty_args, 1, &canWriteProperty_return };
inline constexpr reg::Arg canCallMethod_args[] = { reg::typed("methodReflection", 0, "PHPStan\\Reflection\\MethodReflection") };
inline constexpr reg::Arg canCallMethod_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig canCallMethod = { "canCallMethod", ZEND_ACC_PUBLIC, 1, canCallMethod_args, 1, &canCallMethod_return };
inline constexpr reg::Arg canAccessConstant_args[] = { reg::typed("constantReflection", 0, "PHPStan\\Reflection\\ClassConstantReflection") };
inline constexpr reg::Arg canAccessConstant_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig canAccessConstant = { "canAccessConstant", ZEND_ACC_PUBLIC, 1, canAccessConstant_args, 1, &canAccessConstant_return };
inline constexpr reg::Arg canAccessClassMember_args[] = { reg::typed("classMemberReflection", 0, "PHPStan\\Reflection\\ClassMemberReflection") };
inline constexpr reg::Arg canAccessClassMember_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig canAccessClassMember = { "canAccessClassMember", ZEND_ACC_PRIVATE, 1, canAccessClassMember_args, 1, &canAccessClassMember_return };
inline constexpr reg::Arg debug_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig debug = { "debug", ZEND_ACC_PUBLIC, 0, nullptr, 0, &debug_return };
inline constexpr reg::Arg filterTypeWithMethod_args[] = { reg::typed("typeWithMethod", 0, "PHPStan\\Type\\Type"), reg::typed("methodName", MAY_BE_STRING) };
inline constexpr reg::Arg filterTypeWithMethod_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Type\\Type");
inline constexpr reg::Sig filterTypeWithMethod = { "filterTypeWithMethod", ZEND_ACC_PUBLIC, 2, filterTypeWithMethod_args, 2, &filterTypeWithMethod_return };
inline constexpr reg::Arg getMethodReflection_args[] = { reg::typed("typeWithMethod", 0, "PHPStan\\Type\\Type"), reg::typed("methodName", MAY_BE_STRING) };
inline constexpr reg::Arg getMethodReflection_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Reflection\\ExtendedMethodReflection");
inline constexpr reg::Sig getMethodReflection = { "getMethodReflection", ZEND_ACC_PUBLIC, 2, getMethodReflection_args, 2, &getMethodReflection_return };
inline constexpr reg::Arg getNakedMethod_args[] = { reg::typed("typeWithMethod", 0, "PHPStan\\Type\\Type"), reg::typed("methodName", MAY_BE_STRING) };
inline constexpr reg::Arg getNakedMethod_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Reflection\\ExtendedMethodReflection");
inline constexpr reg::Sig getNakedMethod = { "getNakedMethod", ZEND_ACC_PUBLIC, 2, getNakedMethod_args, 2, &getNakedMethod_return };
inline constexpr reg::Arg getPropertyReflection_args[] = { reg::typed("typeWithProperty", 0, "PHPStan\\Type\\Type"), reg::typed("propertyName", MAY_BE_STRING) };
inline constexpr reg::Arg getPropertyReflection_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Reflection\\ExtendedPropertyReflection");
inline constexpr reg::Sig getPropertyReflection = { "getPropertyReflection", ZEND_ACC_PUBLIC, 2, getPropertyReflection_args, 2, &getPropertyReflection_return };
inline constexpr reg::Arg getInstancePropertyReflection_args[] = { reg::typed("typeWithProperty", 0, "PHPStan\\Type\\Type"), reg::typed("propertyName", MAY_BE_STRING) };
inline constexpr reg::Arg getInstancePropertyReflection_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Reflection\\ExtendedPropertyReflection");
inline constexpr reg::Sig getInstancePropertyReflection = { "getInstancePropertyReflection", ZEND_ACC_PUBLIC, 2, getInstancePropertyReflection_args, 2, &getInstancePropertyReflection_return };
inline constexpr reg::Arg getStaticPropertyReflection_args[] = { reg::typed("typeWithProperty", 0, "PHPStan\\Type\\Type"), reg::typed("propertyName", MAY_BE_STRING) };
inline constexpr reg::Arg getStaticPropertyReflection_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Reflection\\ExtendedPropertyReflection");
inline constexpr reg::Sig getStaticPropertyReflection = { "getStaticPropertyReflection", ZEND_ACC_PUBLIC, 2, getStaticPropertyReflection_args, 2, &getStaticPropertyReflection_return };
inline constexpr reg::Arg getConstantReflection_args[] = { reg::typed("typeWithConstant", 0, "PHPStan\\Type\\Type"), reg::typed("constantName", MAY_BE_STRING) };
inline constexpr reg::Arg getConstantReflection_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Reflection\\ClassConstantReflection");
inline constexpr reg::Sig getConstantReflection = { "getConstantReflection", ZEND_ACC_PUBLIC, 2, getConstantReflection_args, 2, &getConstantReflection_return };
inline constexpr reg::Arg getConstantExplicitTypeFromConfig_args[] = { reg::typed("constantName", MAY_BE_STRING), reg::typed("constantType", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg getConstantExplicitTypeFromConfig_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getConstantExplicitTypeFromConfig = { "getConstantExplicitTypeFromConfig", ZEND_ACC_PUBLIC, 2, getConstantExplicitTypeFromConfig_args, 2, &getConstantExplicitTypeFromConfig_return };
inline constexpr reg::Arg getConstantTypes_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig getConstantTypes = { "getConstantTypes", ZEND_ACC_PRIVATE, 0, nullptr, 0, &getConstantTypes_return };
inline constexpr reg::Arg getGlobalConstantType_args[] = { reg::typed("name", 0, "PhpParser\\Node\\Name") };
inline constexpr reg::Arg getGlobalConstantType_return = reg::typed("", MAY_BE_NULL, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getGlobalConstantType = { "getGlobalConstantType", ZEND_ACC_PRIVATE, 1, getGlobalConstantType_args, 1, &getGlobalConstantType_return };
inline constexpr reg::Arg createGlobalConstantFetches_args[] = { reg::typed("name", 0, "PhpParser\\Node\\Name"), reg::typed("nameString", MAY_BE_STRING), reg::typed("namespace", MAY_BE_NULL | MAY_BE_STRING) };
inline constexpr reg::Arg createGlobalConstantFetches_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig createGlobalConstantFetches = { "createGlobalConstantFetches", ZEND_ACC_PRIVATE | ZEND_ACC_STATIC, 3, createGlobalConstantFetches_args, 3, &createGlobalConstantFetches_return };
inline constexpr reg::Arg getNativeConstantTypes_return = reg::typed("", MAY_BE_ARRAY);
inline constexpr reg::Sig getNativeConstantTypes = { "getNativeConstantTypes", ZEND_ACC_PRIVATE, 0, nullptr, 0, &getNativeConstantTypes_return };
inline constexpr reg::Arg getIterableKeyType_args[] = { reg::typed("iteratee", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg getIterableKeyType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getIterableKeyType = { "getIterableKeyType", ZEND_ACC_PUBLIC, 1, getIterableKeyType_args, 1, &getIterableKeyType_return };
inline constexpr reg::Arg getIterableValueType_args[] = { reg::typed("iteratee", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg getIterableValueType_return = reg::typed("", 0, "PHPStan\\Type\\Type");
inline constexpr reg::Sig getIterableValueType = { "getIterableValueType", ZEND_ACC_PUBLIC, 1, getIterableValueType_args, 1, &getIterableValueType_return };
inline constexpr reg::Arg getPhpVersion_return = reg::typed("", 0, "PHPStan\\Php\\PhpVersions");
inline constexpr reg::Sig getPhpVersion = { "getPhpVersion", ZEND_ACC_PUBLIC, 0, nullptr, 0, &getPhpVersion_return };
inline constexpr reg::Arg isOverallPhpVersionRange_args[] = { reg::typed("type", 0, "PHPStan\\Type\\Type") };
inline constexpr reg::Arg isOverallPhpVersionRange_return = reg::typed("", MAY_BE_BOOL);
inline constexpr reg::Sig isOverallPhpVersionRange = { "isOverallPhpVersionRange", ZEND_ACC_PRIVATE, 1, isOverallPhpVersionRange_args, 1, &isOverallPhpVersionRange_return };
inline constexpr reg::Arg invokeNodeCallback_args[] = { reg::typed("node", 0, "PhpParser\\Node") };
inline constexpr reg::Arg invokeNodeCallback_return = reg::typed("", MAY_BE_VOID);
inline constexpr reg::Sig invokeNodeCallback = { "invokeNodeCallback", ZEND_ACC_PUBLIC, 1, invokeNodeCallback_args, 1, &invokeNodeCallback_return };
inline constexpr reg::Arg emitCollectedData_args[] = { reg::typed("collectorType", MAY_BE_STRING), reg::typed("data", MAY_BE_ANY) };
inline constexpr reg::Arg emitCollectedData_return = reg::typed("", MAY_BE_VOID);
inline constexpr reg::Sig emitCollectedData = { "emitCollectedData", ZEND_ACC_PUBLIC, 2, emitCollectedData_args, 2, &emitCollectedData_return };
} // namespace sig

} // namespace ptdecl::MutatingScope

#endif
