<?php declare(strict_types = 1);

namespace FilterVar;

use function PHPStan\Testing\assertType;

function () {
	/** @var mixed $mixed */
	$mixed = null;
	$nullFilter = \FILTER_NULL_ON_FAILURE;
	$forceArrayFilter = \FILTER_FORCE_ARRAY;
	$filterIp = FILTER_VALIDATE_IP;

	assertType('string|false', filter_var($mixed, FILTER_DEFAULT ));
	assertType('mixed', filter_var($mixed, FILTER_DEFAULT , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_DEFAULT , ["flags" => $mixed]));
	assertType('string|null', filter_var($mixed, FILTER_DEFAULT , FILTER_NULL_ON_FAILURE));
	assertType('string|null', filter_var($mixed, FILTER_DEFAULT , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('string|null', filter_var($mixed, FILTER_DEFAULT , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('string|null', filter_var($mixed, FILTER_DEFAULT , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|string', filter_var($mixed, FILTER_DEFAULT , ["options" => ["default" => new Analyser]]));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_DEFAULT , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_DEFAULT , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_DEFAULT , FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_DEFAULT , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_DEFAULT , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_DEFAULT , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_DEFAULT , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_DEFAULT , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('string|false', filter_var($mixed, FILTER_UNSAFE_RAW ));
	assertType('mixed', filter_var($mixed, FILTER_UNSAFE_RAW , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_UNSAFE_RAW , ["flags" => $mixed]));
	assertType('string|null', filter_var($mixed, FILTER_UNSAFE_RAW , FILTER_NULL_ON_FAILURE));
	assertType('string|null', filter_var($mixed, FILTER_UNSAFE_RAW , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('string|null', filter_var($mixed, FILTER_UNSAFE_RAW , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('string|null', filter_var($mixed, FILTER_UNSAFE_RAW , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|string', filter_var($mixed, FILTER_UNSAFE_RAW , ["options" => ["default" => new Analyser]]));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_UNSAFE_RAW , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_UNSAFE_RAW , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_UNSAFE_RAW , FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_UNSAFE_RAW , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_UNSAFE_RAW , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_UNSAFE_RAW , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_UNSAFE_RAW , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_UNSAFE_RAW , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('string|false', filter_var($mixed, FILTER_SANITIZE_EMAIL ));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_EMAIL , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_EMAIL , ["flags" => $mixed]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_EMAIL , FILTER_NULL_ON_FAILURE));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_EMAIL , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_EMAIL , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_EMAIL , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|string', filter_var($mixed, FILTER_SANITIZE_EMAIL , ["options" => ["default" => new Analyser]]));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_EMAIL , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_EMAIL , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_EMAIL , FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_EMAIL , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_EMAIL , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_EMAIL , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_EMAIL , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_EMAIL , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('string|false', filter_var($mixed, FILTER_SANITIZE_ENCODED ));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_ENCODED , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_ENCODED , ["flags" => $mixed]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_ENCODED , FILTER_NULL_ON_FAILURE));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_ENCODED , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_ENCODED , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_ENCODED , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|string', filter_var($mixed, FILTER_SANITIZE_ENCODED , ["options" => ["default" => new Analyser]]));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_ENCODED , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_ENCODED , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_ENCODED , FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_ENCODED , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_ENCODED , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_ENCODED , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_ENCODED , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_ENCODED , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('string|false', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT ));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , ["flags" => $mixed]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , FILTER_NULL_ON_FAILURE));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|string', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , ["options" => ["default" => new Analyser]]));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_NUMBER_FLOAT , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('string|false', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT ));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , ["flags" => $mixed]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , FILTER_NULL_ON_FAILURE));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|string', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , ["options" => ["default" => new Analyser]]));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_NUMBER_INT , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('string|false', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS ));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , ["flags" => $mixed]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , FILTER_NULL_ON_FAILURE));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|string', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , ["options" => ["default" => new Analyser]]));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_SPECIAL_CHARS , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('string|false', filter_var($mixed, FILTER_SANITIZE_STRING ));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_STRING , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_STRING , ["flags" => $mixed]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_STRING , FILTER_NULL_ON_FAILURE));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_STRING , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_STRING , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_STRING , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|string', filter_var($mixed, FILTER_SANITIZE_STRING , ["options" => ["default" => new Analyser]]));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_STRING , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_STRING , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_STRING , FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_STRING , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_STRING , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_STRING , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_STRING , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_STRING , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('string|false', filter_var($mixed, FILTER_SANITIZE_URL ));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_URL , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_URL , ["flags" => $mixed]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_URL , FILTER_NULL_ON_FAILURE));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_URL , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_URL , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_URL , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|string', filter_var($mixed, FILTER_SANITIZE_URL , ["options" => ["default" => new Analyser]]));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_URL , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_URL , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_URL , FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_URL , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_URL , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_URL , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_URL , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_URL , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('string|false', filter_var($mixed, FILTER_VALIDATE_REGEXP ));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_REGEXP , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_REGEXP , ["flags" => $mixed]));
	assertType('string|null', filter_var($mixed, FILTER_VALIDATE_REGEXP , FILTER_NULL_ON_FAILURE));
	assertType('string|null', filter_var($mixed, FILTER_VALIDATE_REGEXP , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('string|null', filter_var($mixed, FILTER_VALIDATE_REGEXP , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('string|null', filter_var($mixed, FILTER_VALIDATE_REGEXP , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|string', filter_var($mixed, FILTER_VALIDATE_REGEXP , ["options" => ["default" => new Analyser]]));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_VALIDATE_REGEXP , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_VALIDATE_REGEXP , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_VALIDATE_REGEXP , FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_VALIDATE_REGEXP , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_VALIDATE_REGEXP , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_VALIDATE_REGEXP , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_VALIDATE_REGEXP , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_VALIDATE_REGEXP , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('string|false', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES ));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , ["flags" => $mixed]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , FILTER_NULL_ON_FAILURE));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('string|null', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|string', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , ["options" => ["default" => new Analyser]]));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , FILTER_FORCE_ARRAY));
	assertType('array<array|string|null>', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|string|false>', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|string>', filter_var($mixed, FILTER_SANITIZE_ADD_SLASHES , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('non-falsy-string|false', filter_var($mixed, FILTER_VALIDATE_EMAIL ));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_EMAIL , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_EMAIL , ["flags" => $mixed]));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_EMAIL , FILTER_NULL_ON_FAILURE));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_EMAIL , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_EMAIL , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_EMAIL , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|non-falsy-string', filter_var($mixed, FILTER_VALIDATE_EMAIL , ["options" => ["default" => new Analyser]]));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, FILTER_VALIDATE_EMAIL , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, FILTER_VALIDATE_EMAIL , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, FILTER_VALIDATE_EMAIL , FILTER_FORCE_ARRAY));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, FILTER_VALIDATE_EMAIL , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, FILTER_VALIDATE_EMAIL , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, FILTER_VALIDATE_EMAIL , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|non-falsy-string>', filter_var($mixed, FILTER_VALIDATE_EMAIL , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|non-falsy-string>', filter_var($mixed, FILTER_VALIDATE_EMAIL , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('non-falsy-string|false', filter_var($mixed, FILTER_VALIDATE_IP ));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_IP , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_IP , ["flags" => $mixed]));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_IP , FILTER_NULL_ON_FAILURE));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_IP , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_IP , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_IP , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|non-falsy-string', filter_var($mixed, FILTER_VALIDATE_IP , ["options" => ["default" => new Analyser]]));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, FILTER_VALIDATE_IP , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, FILTER_VALIDATE_IP , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, FILTER_VALIDATE_IP , FILTER_FORCE_ARRAY));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, FILTER_VALIDATE_IP , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, FILTER_VALIDATE_IP , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, FILTER_VALIDATE_IP , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|non-falsy-string>', filter_var($mixed, FILTER_VALIDATE_IP , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|non-falsy-string>', filter_var($mixed, FILTER_VALIDATE_IP , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('non-falsy-string|false', filter_var($mixed, $filterIp ));
	assertType('mixed', filter_var($mixed, $filterIp , $mixed));
	assertType('mixed', filter_var($mixed, $filterIp , ["flags" => $mixed]));
	assertType('non-falsy-string|null', filter_var($mixed, $filterIp , FILTER_NULL_ON_FAILURE));
	assertType('non-falsy-string|null', filter_var($mixed, $filterIp , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('non-falsy-string|null', filter_var($mixed, $filterIp , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('non-falsy-string|null', filter_var($mixed, $filterIp , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|non-falsy-string', filter_var($mixed, $filterIp , ["options" => ["default" => new Analyser]]));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, $filterIp , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, $filterIp , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, $filterIp , FILTER_FORCE_ARRAY));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, $filterIp , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, $filterIp , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, $filterIp , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|non-falsy-string>', filter_var($mixed, $filterIp , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|non-falsy-string>', filter_var($mixed, $filterIp , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('non-falsy-string|false', filter_var($mixed, FILTER_VALIDATE_MAC ));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_MAC , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_MAC , ["flags" => $mixed]));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_MAC , FILTER_NULL_ON_FAILURE));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_MAC , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_MAC , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_MAC , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|non-falsy-string', filter_var($mixed, FILTER_VALIDATE_MAC , ["options" => ["default" => new Analyser]]));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, FILTER_VALIDATE_MAC , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, FILTER_VALIDATE_MAC , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, FILTER_VALIDATE_MAC , FILTER_FORCE_ARRAY));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, FILTER_VALIDATE_MAC , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, FILTER_VALIDATE_MAC , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, FILTER_VALIDATE_MAC , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|non-falsy-string>', filter_var($mixed, FILTER_VALIDATE_MAC , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|non-falsy-string>', filter_var($mixed, FILTER_VALIDATE_MAC , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('non-falsy-string|false', filter_var($mixed, FILTER_VALIDATE_URL ));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_URL , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_URL , ["flags" => $mixed]));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_URL , FILTER_NULL_ON_FAILURE));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_URL , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_URL , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('non-falsy-string|null', filter_var($mixed, FILTER_VALIDATE_URL , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|non-falsy-string', filter_var($mixed, FILTER_VALIDATE_URL , ["options" => ["default" => new Analyser]]));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, FILTER_VALIDATE_URL , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, FILTER_VALIDATE_URL , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, FILTER_VALIDATE_URL , FILTER_FORCE_ARRAY));
	assertType('array<array|non-falsy-string|null>', filter_var($mixed, FILTER_VALIDATE_URL , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, FILTER_VALIDATE_URL , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|non-falsy-string|false>', filter_var($mixed, FILTER_VALIDATE_URL , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|non-falsy-string>', filter_var($mixed, FILTER_VALIDATE_URL , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|non-falsy-string>', filter_var($mixed, FILTER_VALIDATE_URL , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('int|false', filter_var($mixed, FILTER_VALIDATE_INT ));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_INT , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_INT , ["flags" => $mixed]));
	assertType('int|null', filter_var($mixed, FILTER_VALIDATE_INT , FILTER_NULL_ON_FAILURE));
	assertType('int|null', filter_var($mixed, FILTER_VALIDATE_INT , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('int|null', filter_var($mixed, FILTER_VALIDATE_INT , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('int|null', filter_var($mixed, FILTER_VALIDATE_INT , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|int', filter_var($mixed, FILTER_VALIDATE_INT , ["options" => ["default" => new Analyser]]));
	assertType('array<array|int|null>', filter_var($mixed, FILTER_VALIDATE_INT , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|int|null>', filter_var($mixed, FILTER_VALIDATE_INT , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|int|false>', filter_var($mixed, FILTER_VALIDATE_INT , FILTER_FORCE_ARRAY));
	assertType('array<array|int|null>', filter_var($mixed, FILTER_VALIDATE_INT , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|int|false>', filter_var($mixed, FILTER_VALIDATE_INT , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|int|false>', filter_var($mixed, FILTER_VALIDATE_INT , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|int>', filter_var($mixed, FILTER_VALIDATE_INT , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|int>', filter_var($mixed, FILTER_VALIDATE_INT , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('float|false', filter_var($mixed, FILTER_VALIDATE_FLOAT ));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_FLOAT , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_FLOAT , ["flags" => $mixed]));
	assertType('float|null', filter_var($mixed, FILTER_VALIDATE_FLOAT , FILTER_NULL_ON_FAILURE));
	assertType('float|null', filter_var($mixed, FILTER_VALIDATE_FLOAT , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('float|null', filter_var($mixed, FILTER_VALIDATE_FLOAT , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('float|null', filter_var($mixed, FILTER_VALIDATE_FLOAT , ["flags" => $nullFilter]));
	assertType('FilterVar\\Analyser|float', filter_var($mixed, FILTER_VALIDATE_FLOAT , ["options" => ["default" => new Analyser]]));
	assertType('array<array|float|null>', filter_var($mixed, FILTER_VALIDATE_FLOAT , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|float|null>', filter_var($mixed, FILTER_VALIDATE_FLOAT , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4));
	assertType('array<array|float|false>', filter_var($mixed, FILTER_VALIDATE_FLOAT , FILTER_FORCE_ARRAY));
	assertType('array<array|float|null>', filter_var($mixed, FILTER_VALIDATE_FLOAT , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|float|false>', filter_var($mixed, FILTER_VALIDATE_FLOAT , ["flags" => FILTER_FORCE_ARRAY | FILTER_FLAG_IPV4]));
	assertType('array<array|float|false>', filter_var($mixed, FILTER_VALIDATE_FLOAT , ["flags" => $forceArrayFilter]));
	assertType('array<array|FilterVar\Analyser|float>', filter_var($mixed, FILTER_VALIDATE_FLOAT , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|FilterVar\Analyser|float>', filter_var($mixed, FILTER_VALIDATE_FLOAT , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('bool', filter_var($mixed, FILTER_VALIDATE_BOOLEAN ));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , $mixed));
	assertType('mixed', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , ["flags" => $mixed]));
	assertType('bool|null', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , FILTER_NULL_ON_FAILURE));
	assertType('bool|null', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , ["flags" => FILTER_NULL_ON_FAILURE]));
	assertType('bool|null', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FLAG_IPV4]));
	assertType('bool|null', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , ["flags" => $nullFilter]));
	assertType('bool|FilterVar\\Analyser', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , ["options" => ["default" => new Analyser]]));
	assertType('bool', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , ["options" => ["default" => true]]));
	assertType('array<array|bool|null>', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY));
	assertType('array<array|bool>', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , FILTER_FORCE_ARRAY));
	assertType('array<array|bool|null>', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , ["flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('array<array|bool>', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , ["flags" => $forceArrayFilter]));
	assertType('array<array|bool|FilterVar\Analyser>', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , ["options" => ["default" => new Analyser], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|bool>', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , ["options" => ["default" => false], "flags" => FILTER_FORCE_ARRAY]));
	assertType('array<array|bool|FilterVar\Analyser>', filter_var($mixed, FILTER_VALIDATE_BOOLEAN , ["options" => ["default" => new Analyser], "flags" => FILTER_NULL_ON_FAILURE | FILTER_FORCE_ARRAY]));
	assertType('mixed', filter_var($mixed, $mixed));
	assertType('string', filter_var($mixed, FILTER_SANITIZE_URL, ["options" => ["default" => "foo"]]));
	assertType('string|false', filter_var($mixed));
	assertType('12', filter_var(12, FILTER_VALIDATE_INT));
	assertType('false', filter_var(false, FILTER_VALIDATE_BOOLEAN));
	assertType('array<false>', filter_var(false, FILTER_VALIDATE_BOOLEAN, FILTER_FORCE_ARRAY));
	assertType('array<false>', filter_var(false, FILTER_VALIDATE_BOOLEAN, FILTER_FORCE_ARRAY | FILTER_NULL_ON_FAILURE));
	assertType('3.27', filter_var(3.27, FILTER_VALIDATE_FLOAT));
	assertType('3.27', filter_var(3.27, FILTER_VALIDATE_FLOAT, FILTER_NULL_ON_FAILURE));
	assertType('int<0, max>', filter_var(rand(), FILTER_VALIDATE_INT));
	assertType('12.0', filter_var(12, FILTER_VALIDATE_FLOAT));
};
