/* GENERATED by turbo-ext/bin/generate-parser-actions.php — do not edit */
/*
 * Reduce actions for rules 1-268 of php-parser's Php8 grammar
 * (vendor/nikic/php-parser/lib/PhpParser/Parser/Php8.php, initReduceCallbacks).
 * Rules with a null callback have no case here; returning false makes the
 * engine apply the default action. Hand-ported special cases are emitted
 * verbatim from src/parser/action-overrides/<sha1-of-php-body>.inc.
 */

#include "ParserEngine.h"

namespace phpstanturbo {

bool ParserEngine::reduceRange1(int rule, int stackPos)
{
	switch (rule) {
	/* rule 1 */
	case 1: {
		semValue = handleNamespaces(PN_SEM(1, 1));
		return true;
	}
	/* rule 2 */
	case 2: {
		if (!PN_SEM(2, 2).isNull()) {
			pushOnto(PN_SEM(2, 1), PN_SEM(2, 2));
		}
		semValue = PN_SEM(2, 1);
		return true;
	}
	/* rule 3 */
	case 3: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 4 (from action-overrides/aeb46c35c63d49d076d22af3cd5ef3ffc214e9dc.inc) */
	case 4: {
		/* $nop = $self->maybeCreateZeroLengthNop($self->tokenPos);
		 * if ($nop !== null) { $self->semStack[$1][] = $nop; } $$ = $self->semStack[$1]; */
		zv::Val nop = maybeCreateZeroLengthNop(tokenPos);
		if (!nop.isNull()) {
			pushOnto(PN_SEM(1, 1), std::move(nop));
		}
		semValue = PN_SEM(1, 1);
		return true;
	}
	/* rule 76 */
	case 76: {
		semValue = PN_SEM(1, 1);
		if (semValue.ref().stringEquals("<?=")) {
			emitError("Cannot use \"<?=\" as an identifier", PN_ATTRS(1, 1, 1));
		}
		return true;
	}
	/* rule 85 */
	case 85: {
		semValue = newNode("Node\\Identifier", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 86 */
	case 86: {
		semValue = newNode("Node\\Identifier", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 87 */
	case 87: {
		semValue = newNode("Node\\Identifier", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 88 */
	case 88: {
		semValue = newNode("Node\\Identifier", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 89 */
	case 89: {
		semValue = newName(PN_SEM(1, 1), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 90 */
	case 90: {
		semValue = newName(PN_SEM(1, 1), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 91 */
	case 91: {
		semValue = newName(PN_SEM(1, 1), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 92 */
	case 92: {
		semValue = newName(PN_SEM(1, 1), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 93 */
	case 93: {
		semValue = newName(PN_SEM(1, 1), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 95 */
	case 95: {
		zv::Val t1 = substr(PN_SEM(1, 1), 1);
		semValue = newName(t1.ref(), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 96 */
	case 96: {
		zv::Val t1 = substr(PN_SEM(1, 1), 1);
		semValue = newNode("Expr\\Variable", PN_ATTRS(1, 1, 1), t1);
		return true;
	}
	/* rule 97 */
	case 97: {
		/* nothing */
		return true;
	}
	/* rule 98 */
	case 98: {
		/* nothing */
		return true;
	}
	/* rule 99 */
	case 99: {
		/* nothing */
		return true;
	}
	/* rule 100 */
	case 100: {
		emitError("A trailing comma is not allowed here", PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 103 */
	case 103: {
		zv::Val t1 = zv::Arr::empty();
		semValue = newNode("Node\\Attribute", PN_ATTRS(1, 1, 1), PN_SEM(1, 1), t1);
		return true;
	}
	/* rule 104 */
	case 104: {
		semValue = newNode("Node\\Attribute", PN_ATTRS(2, 1, 2), PN_SEM(2, 1), PN_SEM(2, 2));
		return true;
	}
	/* rule 105 */
	case 105: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 106 */
	case 106: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 107 */
	case 107: {
		semValue = newNode("Node\\AttributeGroup", PN_ATTRS(4, 1, 4), PN_SEM(4, 2));
		return true;
	}
	/* rule 108 */
	case 108: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 109 */
	case 109: {
		pushOnto(PN_SEM(2, 1), PN_SEM(2, 2));
		semValue = PN_SEM(2, 1);
		return true;
	}
	/* rule 110 */
	case 110: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 115 */
	case 115: {
		zv::Val t1 = handleHaltCompiler();
		semValue = newNode("Stmt\\HaltCompiler", PN_ATTRS(4, 1, 4), t1);
		return true;
	}
	/* rule 116 */
	case 116: {
		semValue = newNode("Stmt\\Namespace_", PN_ATTRS(3, 1, 3), PN_SEM(3, 2), nullptr);
		setNodeAttribute(semValue.ref(), "kind", zv::Val::integer(1 /* Stmt\Namespace_::KIND_SEMICOLON */));
		checkNamespace(semValue.ref());
		return true;
	}
	/* rule 117 */
	case 117: {
		semValue = newNode("Stmt\\Namespace_", PN_ATTRS(5, 1, 5), PN_SEM(5, 2), PN_SEM(5, 4));
		setNodeAttribute(semValue.ref(), "kind", zv::Val::integer(2 /* Stmt\Namespace_::KIND_BRACED */));
		checkNamespace(semValue.ref());
		return true;
	}
	/* rule 118 */
	case 118: {
		semValue = newNode("Stmt\\Namespace_", PN_ATTRS(4, 1, 4), nullptr, PN_SEM(4, 3));
		setNodeAttribute(semValue.ref(), "kind", zv::Val::integer(2 /* Stmt\Namespace_::KIND_BRACED */));
		checkNamespace(semValue.ref());
		return true;
	}
	/* rule 119 */
	case 119: {
		semValue = newNode("Stmt\\Use_", PN_ATTRS(3, 1, 3), PN_SEM(3, 2), zv::Val::integer(1 /* Stmt\Use_::TYPE_NORMAL */));
		return true;
	}
	/* rule 120 */
	case 120: {
		semValue = newNode("Stmt\\Use_", PN_ATTRS(4, 1, 4), PN_SEM(4, 3), PN_SEM(4, 2));
		return true;
	}
	/* rule 122 */
	case 122: {
		zv::Val t1 = zv::Arr::empty();
		semValue = newNode("Stmt\\Const_", PN_ATTRS(3, 1, 3), PN_SEM(3, 2), t1);
		return true;
	}
	/* rule 123 */
	case 123: {
		semValue = newNode("Stmt\\Const_", PN_ATTRS(4, 1, 4), PN_SEM(4, 3), PN_SEM(4, 1));
		checkConstantAttributes(semValue.ref());
		return true;
	}
	/* rule 124 */
	case 124: {
		semValue = zv::Val::integer(2 /* Stmt\Use_::TYPE_FUNCTION */);
		return true;
	}
	/* rule 125 */
	case 125: {
		semValue = zv::Val::integer(3 /* Stmt\Use_::TYPE_CONSTANT */);
		return true;
	}
	/* rule 126 */
	case 126: {
		semValue = newNode("Stmt\\GroupUse", PN_ATTRS(8, 1, 8), PN_SEM(8, 3), PN_SEM(8, 6), PN_SEM(8, 2));
		return true;
	}
	/* rule 127 */
	case 127: {
		semValue = newNode("Stmt\\GroupUse", PN_ATTRS(7, 1, 7), PN_SEM(7, 2), PN_SEM(7, 5), zv::Val::integer(0 /* Stmt\Use_::TYPE_UNKNOWN */));
		return true;
	}
	/* rule 129 */
	case 129: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 130 */
	case 130: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 132 */
	case 132: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 133 */
	case 133: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 135 */
	case 135: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 136 */
	case 136: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 137 */
	case 137: {
		semValue = newNode("Node\\UseItem", PN_ATTRS(1, 1, 1), PN_SEM(1, 1), nullptr, zv::Val::integer(0 /* Stmt\Use_::TYPE_UNKNOWN */));
		checkUseUse(semValue.ref(), stackPos - (1 - 1));
		return true;
	}
	/* rule 138 */
	case 138: {
		semValue = newNode("Node\\UseItem", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3), zv::Val::integer(0 /* Stmt\Use_::TYPE_UNKNOWN */));
		checkUseUse(semValue.ref(), stackPos - (3 - 3));
		return true;
	}
	/* rule 139 */
	case 139: {
		semValue = newNode("Node\\UseItem", PN_ATTRS(1, 1, 1), PN_SEM(1, 1), nullptr, zv::Val::integer(0 /* Stmt\Use_::TYPE_UNKNOWN */));
		checkUseUse(semValue.ref(), stackPos - (1 - 1));
		return true;
	}
	/* rule 140 */
	case 140: {
		semValue = newNode("Node\\UseItem", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3), zv::Val::integer(0 /* Stmt\Use_::TYPE_UNKNOWN */));
		checkUseUse(semValue.ref(), stackPos - (3 - 3));
		return true;
	}
	/* rule 141 */
	case 141: {
		semValue = PN_SEM(1, 1);
		propWrite(semValue.ref(), "type", zv::Val::integer(1 /* Stmt\Use_::TYPE_NORMAL */));
		return true;
	}
	/* rule 142 */
	case 142: {
		semValue = PN_SEM(2, 2);
		propWrite(semValue.ref(), "type", zv::Val::copyOf(PN_SEM(2, 1)));
		return true;
	}
	/* rule 144 */
	case 144: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 145 */
	case 145: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 146 */
	case 146: {
		semValue = newNode("Node\\Const_", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 148 */
	case 148: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 149 */
	case 149: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 150 */
	case 150: {
		zv::Val t1 = newNode("Node\\Identifier", PN_ATTRS(3, 1, 1), PN_SEM(3, 1));
		semValue = newNode("Node\\Const_", PN_ATTRS(3, 1, 3), t1, PN_SEM(3, 3));
		return true;
	}
	/* rule 151 */
	case 151: {
		zv::Val t1 = newNode("Node\\Identifier", PN_ATTRS(3, 1, 1), PN_SEM(3, 1));
		semValue = newNode("Node\\Const_", PN_ATTRS(3, 1, 3), t1, PN_SEM(3, 3));
		return true;
	}
	/* rule 152 */
	case 152: {
		if (!PN_SEM(2, 2).isNull()) {
			pushOnto(PN_SEM(2, 1), PN_SEM(2, 2));
		}
		semValue = PN_SEM(2, 1);
		return true;
	}
	/* rule 153 */
	case 153: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 154 (from action-overrides/aeb46c35c63d49d076d22af3cd5ef3ffc214e9dc.inc) */
	case 154: {
		/* $nop = $self->maybeCreateZeroLengthNop($self->tokenPos);
		 * if ($nop !== null) { $self->semStack[$1][] = $nop; } $$ = $self->semStack[$1]; */
		zv::Val nop = maybeCreateZeroLengthNop(tokenPos);
		if (!nop.isNull()) {
			pushOnto(PN_SEM(1, 1), std::move(nop));
		}
		semValue = PN_SEM(1, 1);
		return true;
	}
	/* rule 158 */
	case 158: {
		fatalError("__HALT_COMPILER() can only be used from the outermost scope", PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 159 */
	case 159: {
		semValue = newNode("Stmt\\Block", PN_ATTRS(3, 1, 3), PN_SEM(3, 2));
		return true;
	}
	/* rule 160 */
	case 160: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(7, 5)));
		sub1.set("elseifs", zv::Val::copyOf(PN_SEM(7, 6)));
		sub1.set("else", zv::Val::copyOf(PN_SEM(7, 7)));
		semValue = newNodeCtor("Stmt\\If_", PN_ATTRS(7, 1, 7), PN_SEM(7, 3), sub1);
		return true;
	}
	/* rule 161 */
	case 161: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(10, 6)));
		sub1.set("elseifs", zv::Val::copyOf(PN_SEM(10, 7)));
		sub1.set("else", zv::Val::copyOf(PN_SEM(10, 8)));
		semValue = newNodeCtor("Stmt\\If_", PN_ATTRS(10, 1, 10), PN_SEM(10, 3), sub1);
		return true;
	}
	/* rule 162 */
	case 162: {
		semValue = newNode("Stmt\\While_", PN_ATTRS(5, 1, 5), PN_SEM(5, 3), PN_SEM(5, 5));
		return true;
	}
	/* rule 163 */
	case 163: {
		semValue = newNode("Stmt\\Do_", PN_ATTRS(7, 1, 7), PN_SEM(7, 5), PN_SEM(7, 2));
		return true;
	}
	/* rule 164 */
	case 164: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("init", zv::Val::copyOf(PN_SEM(9, 3)));
		sub1.set("cond", zv::Val::copyOf(PN_SEM(9, 5)));
		sub1.set("loop", zv::Val::copyOf(PN_SEM(9, 7)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(9, 9)));
		semValue = newNodeCtor("Stmt\\For_", PN_ATTRS(9, 1, 9), sub1);
		return true;
	}
	/* rule 165 */
	case 165: {
		semValue = newNode("Stmt\\Switch_", PN_ATTRS(5, 1, 5), PN_SEM(5, 3), PN_SEM(5, 5));
		return true;
	}
	/* rule 166 */
	case 166: {
		semValue = newNode("Stmt\\Break_", PN_ATTRS(3, 1, 3), PN_SEM(3, 2));
		return true;
	}
	/* rule 167 */
	case 167: {
		semValue = newNode("Stmt\\Continue_", PN_ATTRS(3, 1, 3), PN_SEM(3, 2));
		return true;
	}
	/* rule 168 */
	case 168: {
		semValue = newNode("Stmt\\Return_", PN_ATTRS(3, 1, 3), PN_SEM(3, 2));
		return true;
	}
	/* rule 169 */
	case 169: {
		semValue = newNode("Stmt\\Global_", PN_ATTRS(3, 1, 3), PN_SEM(3, 2));
		return true;
	}
	/* rule 170 */
	case 170: {
		semValue = newNode("Stmt\\Static_", PN_ATTRS(3, 1, 3), PN_SEM(3, 2));
		return true;
	}
	/* rule 171 */
	case 171: {
		semValue = newNode("Stmt\\Echo_", PN_ATTRS(3, 1, 3), PN_SEM(3, 2));
		return true;
	}
	/* rule 172 */
	case 172: {
		semValue = newNode("Stmt\\InlineHTML", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		setNodeAttribute(semValue.ref(), "hasLeadingNewline", zv::Val::boolean(inlineHtmlHasLeadingNewline(stackPos - (1 - 1))));
		return true;
	}
	/* rule 173 */
	case 173: {
		semValue = newNode("Stmt\\Expression", PN_ATTRS(2, 1, 2), PN_SEM(2, 1));
		return true;
	}
	/* rule 174 */
	case 174: {
		semValue = newNode("Stmt\\Unset_", PN_ATTRS(5, 1, 5), PN_SEM(5, 3));
		return true;
	}
	/* rule 175 */
	case 175: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("keyVar", zv::Val::null());
		sub1.set("byRef", zv::Val::copyOf(itemAt(PN_SEM(7, 5), 1)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(7, 7)));
		semValue = newNodeCtor("Stmt\\Foreach_", PN_ATTRS(7, 1, 7), PN_SEM(7, 3), itemAt(PN_SEM(7, 5), 0), sub1);
		return true;
	}
	/* rule 176 */
	case 176: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("keyVar", zv::Val::copyOf(PN_SEM(9, 5)));
		sub1.set("byRef", zv::Val::copyOf(itemAt(PN_SEM(9, 7), 1)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(9, 9)));
		semValue = newNodeCtor("Stmt\\Foreach_", PN_ATTRS(9, 1, 9), PN_SEM(9, 3), itemAt(PN_SEM(9, 7), 0), sub1);
		return true;
	}
	/* rule 177 */
	case 177: {
		zv::Val t1 = newNode("Expr\\Error", PN_ATTRS(6, 4, 4));
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(6, 6)));
		semValue = newNodeCtor("Stmt\\Foreach_", PN_ATTRS(6, 1, 6), PN_SEM(6, 3), t1, sub1);
		return true;
	}
	/* rule 178 */
	case 178: {
		semValue = newNode("Stmt\\Declare_", PN_ATTRS(5, 1, 5), PN_SEM(5, 3), PN_SEM(5, 5));
		return true;
	}
	/* rule 179 */
	case 179: {
		semValue = newNode("Stmt\\TryCatch", PN_ATTRS(6, 1, 6), PN_SEM(6, 3), PN_SEM(6, 5), PN_SEM(6, 6));
		checkTryCatch(semValue.ref());
		return true;
	}
	/* rule 180 */
	case 180: {
		semValue = newNode("Stmt\\Goto_", PN_ATTRS(3, 1, 3), PN_SEM(3, 2));
		return true;
	}
	/* rule 181 */
	case 181: {
		semValue = newNode("Stmt\\Label", PN_ATTRS(2, 1, 2), PN_SEM(2, 1));
		return true;
	}
	/* rule 182 */
	case 182: {
		semValue = zv::Val::null();
		/* means: no statement */
		return true;
	}
	/* rule 184 */
	case 184: {
		zv::Val t1 = maybeCreateNop(PN_TOKSTART(1, 1), tokenEndStack[stackPos]);
		if (t1.isUndef()) {
			t1 = zv::Val::null(); /* PHP null return */
		}
		semValue = std::move(t1);
		return true;
	}
	/* rule 185 */
	case 185: {
		if (isInstanceOf(PN_SEM(1, 1), "Stmt\\Block")) {
			semValue = prop(PN_SEM(1, 1), "stmts");
		} else if (PN_SEM(1, 1).isNull()) {
			semValue = zv::Arr::empty();
		} else {
			semValue = arrayOf(PN_SEM(1, 1));
		}
		return true;
	}
	/* rule 186 */
	case 186: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 187 */
	case 187: {
		pushOnto(PN_SEM(2, 1), PN_SEM(2, 2));
		semValue = PN_SEM(2, 1);
		return true;
	}
	/* rule 188 */
	case 188: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 189 */
	case 189: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 190 */
	case 190: {
		semValue = newNode("Stmt\\Catch_", PN_ATTRS(8, 1, 8), PN_SEM(8, 3), PN_SEM(8, 4), PN_SEM(8, 7));
		return true;
	}
	/* rule 191 */
	case 191: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 192 */
	case 192: {
		semValue = newNode("Stmt\\Finally_", PN_ATTRS(4, 1, 4), PN_SEM(4, 3));
		return true;
	}
	/* rule 194 */
	case 194: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 195 */
	case 195: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 196 */
	case 196: {
		semValue = zv::Val::boolean(false);
		return true;
	}
	/* rule 197 */
	case 197: {
		semValue = zv::Val::boolean(true);
		return true;
	}
	/* rule 198 */
	case 198: {
		semValue = zv::Val::boolean(false);
		return true;
	}
	/* rule 199 */
	case 199: {
		semValue = zv::Val::boolean(true);
		return true;
	}
	/* rule 200 */
	case 200: {
		semValue = zv::Val::boolean(false);
		return true;
	}
	/* rule 201 */
	case 201: {
		semValue = zv::Val::boolean(true);
		return true;
	}
	/* rule 202 */
	case 202: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 203 */
	case 203: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 205 */
	case 205: {
		semValue = newNode("Node\\Identifier", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 206 */
	case 206: {
		semValue = newNode("Node\\Identifier", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 207 */
	case 207: {
		semValue = newNode("Node\\Identifier", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 208 */
	case 208: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(8, 2)));
		sub1.set("params", zv::Val::copyOf(PN_SEM(8, 5)));
		sub1.set("returnType", zv::Val::copyOf(PN_SEM(8, 7)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(8, 8)));
		sub1.set("attrGroups", zv::Arr::empty());
		semValue = newNodeCtor("Stmt\\Function_", PN_ATTRS(8, 1, 8), PN_SEM(8, 3), sub1);
		return true;
	}
	/* rule 209 */
	case 209: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(9, 3)));
		sub1.set("params", zv::Val::copyOf(PN_SEM(9, 6)));
		sub1.set("returnType", zv::Val::copyOf(PN_SEM(9, 8)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(9, 9)));
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(9, 1)));
		semValue = newNodeCtor("Stmt\\Function_", PN_ATTRS(9, 1, 9), PN_SEM(9, 4), sub1);
		return true;
	}
	/* rule 210 */
	case 210: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("type", zv::Val::copyOf(PN_SEM(7, 1)));
		sub1.set("extends", zv::Val::copyOf(PN_SEM(7, 3)));
		sub1.set("implements", zv::Val::copyOf(PN_SEM(7, 4)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(7, 6)));
		sub1.set("attrGroups", zv::Arr::empty());
		semValue = newNodeCtor("Stmt\\Class_", PN_ATTRS(7, 1, 7), PN_SEM(7, 2), sub1);
		checkClass(semValue.ref(), stackPos - (7 - 2));
		return true;
	}
	/* rule 211 */
	case 211: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("type", zv::Val::copyOf(PN_SEM(8, 2)));
		sub1.set("extends", zv::Val::copyOf(PN_SEM(8, 4)));
		sub1.set("implements", zv::Val::copyOf(PN_SEM(8, 5)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(8, 7)));
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(8, 1)));
		semValue = newNodeCtor("Stmt\\Class_", PN_ATTRS(8, 1, 8), PN_SEM(8, 3), sub1);
		checkClass(semValue.ref(), stackPos - (8 - 3));
		return true;
	}
	/* rule 212 */
	case 212: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("extends", zv::Val::copyOf(PN_SEM(7, 4)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(7, 6)));
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(7, 1)));
		semValue = newNodeCtor("Stmt\\Interface_", PN_ATTRS(7, 1, 7), PN_SEM(7, 3), sub1);
		checkInterface(semValue.ref(), stackPos - (7 - 3));
		return true;
	}
	/* rule 213 */
	case 213: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(6, 5)));
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(6, 1)));
		semValue = newNodeCtor("Stmt\\Trait_", PN_ATTRS(6, 1, 6), PN_SEM(6, 3), sub1);
		return true;
	}
	/* rule 214 */
	case 214: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("scalarType", zv::Val::copyOf(PN_SEM(8, 4)));
		sub1.set("implements", zv::Val::copyOf(PN_SEM(8, 5)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(8, 7)));
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(8, 1)));
		semValue = newNodeCtor("Stmt\\Enum_", PN_ATTRS(8, 1, 8), PN_SEM(8, 3), sub1);
		checkEnum(semValue.ref(), stackPos - (8 - 3));
		return true;
	}
	/* rule 215 */
	case 215: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 216 */
	case 216: {
		semValue = PN_SEM(2, 2);
		return true;
	}
	/* rule 217 */
	case 217: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 218 */
	case 218: {
		semValue = PN_SEM(2, 2);
		return true;
	}
	/* rule 219 */
	case 219: {
		semValue = zv::Val::integer(0);
		return true;
	}
	/* rule 222 */
	case 222: {
		checkClassModifier(PN_SEM(2, 1).toLong(), PN_SEM(2, 2).toLong(), stackPos - (2 - 2));
		semValue = zv::Val::integer(PN_SEM(2, 1).toLong() | PN_SEM(2, 2).toLong());
		return true;
	}
	/* rule 223 */
	case 223: {
		semValue = zv::Val::integer(16 /* Modifiers::ABSTRACT */);
		return true;
	}
	/* rule 224 */
	case 224: {
		semValue = zv::Val::integer(32 /* Modifiers::FINAL */);
		return true;
	}
	/* rule 225 */
	case 225: {
		semValue = zv::Val::integer(64 /* Modifiers::READONLY */);
		return true;
	}
	/* rule 226 */
	case 226: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 227 */
	case 227: {
		semValue = PN_SEM(2, 2);
		return true;
	}
	/* rule 228 */
	case 228: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 229 */
	case 229: {
		semValue = PN_SEM(2, 2);
		return true;
	}
	/* rule 230 */
	case 230: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 231 */
	case 231: {
		semValue = PN_SEM(2, 2);
		return true;
	}
	/* rule 233 */
	case 233: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 234 */
	case 234: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 236 */
	case 236: {
		semValue = PN_SEM(4, 2);
		return true;
	}
	/* rule 238 */
	case 238: {
		semValue = PN_SEM(4, 2);
		return true;
	}
	/* rule 239 */
	case 239: {
		if (isInstanceOf(PN_SEM(1, 1), "Stmt\\Block")) {
			semValue = prop(PN_SEM(1, 1), "stmts");
		} else if (PN_SEM(1, 1).isNull()) {
			semValue = zv::Arr::empty();
		} else {
			semValue = arrayOf(PN_SEM(1, 1));
		}
		return true;
	}
	/* rule 240 */
	case 240: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 241 */
	case 241: {
		semValue = PN_SEM(4, 2);
		return true;
	}
	/* rule 243 */
	case 243: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 244 */
	case 244: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 245 */
	case 245: {
		semValue = newNodeCtor("Node\\DeclareItem", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 246 */
	case 246: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 247 */
	case 247: {
		semValue = PN_SEM(4, 3);
		return true;
	}
	/* rule 248 */
	case 248: {
		semValue = PN_SEM(4, 2);
		return true;
	}
	/* rule 249 */
	case 249: {
		semValue = PN_SEM(5, 3);
		return true;
	}
	/* rule 250 */
	case 250: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 251 */
	case 251: {
		pushOnto(PN_SEM(2, 1), PN_SEM(2, 2));
		semValue = PN_SEM(2, 1);
		return true;
	}
	/* rule 252 */
	case 252: {
		semValue = newNode("Stmt\\Case_", PN_ATTRS(4, 1, 4), PN_SEM(4, 2), PN_SEM(4, 4));
		return true;
	}
	/* rule 253 */
	case 253: {
		semValue = newNode("Stmt\\Case_", PN_ATTRS(3, 1, 3), nullptr, PN_SEM(3, 3));
		return true;
	}
	/* rule 256 */
	case 256: {
		semValue = newNode("Expr\\Match_", PN_ATTRS(7, 1, 7), PN_SEM(7, 3), PN_SEM(7, 6));
		return true;
	}
	/* rule 257 */
	case 257: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 259 */
	case 259: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 260 */
	case 260: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 261 */
	case 261: {
		semValue = newNode("Node\\MatchArm", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 262 */
	case 262: {
		semValue = newNode("Node\\MatchArm", PN_ATTRS(4, 1, 4), nullptr, PN_SEM(4, 4));
		return true;
	}
	/* rule 263 */
	case 263: {
		semValue = PN_SEM(1, 1);
		return true;
	}
	/* rule 264 */
	case 264: {
		semValue = PN_SEM(4, 2);
		return true;
	}
	/* rule 265 */
	case 265: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 266 */
	case 266: {
		pushOnto(PN_SEM(2, 1), PN_SEM(2, 2));
		semValue = PN_SEM(2, 1);
		return true;
	}
	/* rule 267 */
	case 267: {
		semValue = newNode("Stmt\\ElseIf_", PN_ATTRS(5, 1, 5), PN_SEM(5, 3), PN_SEM(5, 5));
		return true;
	}
	/* rule 268 */
	case 268: {
		semValue = zv::Arr::empty();
		return true;
	}
	default:
		return false;
	}
}

} // namespace phpstanturbo
