/* GENERATED by turbo-ext/bin/generate-parser-actions.php — do not edit */
/*
 * Reduce actions for rules 454-649 of php-parser's Php8 grammar
 * (vendor/nikic/php-parser/lib/PhpParser/Parser/Php8.php, initReduceCallbacks).
 * Rules with a null callback have no case here; returning false makes the
 * engine apply the default action. Hand-ported special cases are emitted
 * verbatim from src/parser/action-overrides/<sha1-of-php-body>.inc.
 */

#include "ParserEngine.h"

namespace phpstanturbo {

/* array_pop($this->semValue) on a packed 0..n-1 list, with the same
 * copy-on-write separation PHP performs on write. Also resets
 * nNextFreeElement like array_pop. */
static void phpArrayPop(zval *arr)
{
	SEPARATE_ARRAY(arr);
	HashTable *ht = Z_ARRVAL_P(arr);
	uint32_t n = zend_hash_num_elements(ht);
	if (n == 0) {
		return;
	}
	zend_hash_index_del(ht, n - 1);
	ht->nNextFreeElement = (zend_long) (n - 1);
	zend_hash_internal_pointer_reset(ht);
}

bool ParserEngine::reduceRange3(int rule, int stackPos)
{
	switch (rule) {
	/* rule 454 */
	case 454: {
		semValue = newNode("Expr\\BinaryOp\\BitwiseXor", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 455 */
	case 455: {
		semValue = newNode("Expr\\BinaryOp\\Concat", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 456 */
	case 456: {
		semValue = newNode("Expr\\BinaryOp\\Plus", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 457 */
	case 457: {
		semValue = newNode("Expr\\BinaryOp\\Minus", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 458 */
	case 458: {
		semValue = newNode("Expr\\BinaryOp\\Mul", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 459 */
	case 459: {
		semValue = newNode("Expr\\BinaryOp\\Div", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 460 */
	case 460: {
		semValue = newNode("Expr\\BinaryOp\\Mod", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 461 */
	case 461: {
		semValue = newNode("Expr\\BinaryOp\\ShiftLeft", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 462 */
	case 462: {
		semValue = newNode("Expr\\BinaryOp\\ShiftRight", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 463 */
	case 463: {
		semValue = newNode("Expr\\BinaryOp\\Pow", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 464 */
	case 464: {
		semValue = newNode("Expr\\UnaryPlus", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 465 */
	case 465: {
		semValue = newNode("Expr\\UnaryMinus", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 466 */
	case 466: {
		semValue = newNode("Expr\\BooleanNot", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 467 */
	case 467: {
		semValue = newNode("Expr\\BitwiseNot", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 468 */
	case 468: {
		semValue = newNode("Expr\\BinaryOp\\Identical", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 469 */
	case 469: {
		semValue = newNode("Expr\\BinaryOp\\NotIdentical", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 470 */
	case 470: {
		semValue = newNode("Expr\\BinaryOp\\Equal", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 471 */
	case 471: {
		semValue = newNode("Expr\\BinaryOp\\NotEqual", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 472 */
	case 472: {
		semValue = newNode("Expr\\BinaryOp\\Spaceship", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 473 */
	case 473: {
		semValue = newNode("Expr\\BinaryOp\\Smaller", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 474 */
	case 474: {
		semValue = newNode("Expr\\BinaryOp\\SmallerOrEqual", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 475 */
	case 475: {
		semValue = newNode("Expr\\BinaryOp\\Greater", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 476 */
	case 476: {
		semValue = newNode("Expr\\BinaryOp\\GreaterOrEqual", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 477 */
	case 477: {
		semValue = newNode("Expr\\BinaryOp\\Pipe", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		checkPipeOperatorParentheses(PN_SEM(3, 3));
		return true;
	}
	/* rule 478 */
	case 478: {
		semValue = newNode("Expr\\Instanceof_", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 479 */
	case 479: {
		semValue = PN_SEM(3, 2);
		if (isInstanceOf(semValue.ref(), "Expr\\ArrowFunction")) {
			parenthesizedArrowFunctionsAdd(semValue.ref());
		}
		return true;
	}
	/* rule 480 */
	case 480: {
		semValue = newNode("Expr\\Ternary", PN_ATTRS(5, 1, 5), PN_SEM(5, 1), PN_SEM(5, 3), PN_SEM(5, 5));
		return true;
	}
	/* rule 481 */
	case 481: {
		semValue = newNode("Expr\\Ternary", PN_ATTRS(4, 1, 4), PN_SEM(4, 1), nullptr, PN_SEM(4, 4));
		return true;
	}
	/* rule 482 */
	case 482: {
		semValue = newNode("Expr\\BinaryOp\\Coalesce", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 483 */
	case 483: {
		semValue = newNode("Expr\\Isset_", PN_ATTRS(4, 1, 4), PN_SEM(4, 3));
		return true;
	}
	/* rule 484 */
	case 484: {
		semValue = newNode("Expr\\Empty_", PN_ATTRS(4, 1, 4), PN_SEM(4, 3));
		return true;
	}
	/* rule 485 */
	case 485: {
		semValue = newNode("Expr\\Include_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2), zv::Val::integer(1 /* Expr\Include_::TYPE_INCLUDE */));
		return true;
	}
	/* rule 486 */
	case 486: {
		semValue = newNode("Expr\\Include_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2), zv::Val::integer(2 /* Expr\Include_::TYPE_INCLUDE_ONCE */));
		return true;
	}
	/* rule 487 */
	case 487: {
		semValue = newNode("Expr\\Eval_", PN_ATTRS(4, 1, 4), PN_SEM(4, 3));
		return true;
	}
	/* rule 488 */
	case 488: {
		semValue = newNode("Expr\\Include_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2), zv::Val::integer(3 /* Expr\Include_::TYPE_REQUIRE */));
		return true;
	}
	/* rule 489 */
	case 489: {
		semValue = newNode("Expr\\Include_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2), zv::Val::integer(4 /* Expr\Include_::TYPE_REQUIRE_ONCE */));
		return true;
	}
	/* rule 490 */
	case 490: {
		zv::Arr attrs = PN_ATTRS(2, 1, 2);
		attrs.set("kind", zv::Val::integer(getIntCastKind(PN_SEM(2, 1))));
		semValue = newNode("Expr\\Cast\\Int_", std::move(attrs), PN_SEM(2, 2));
		return true;
	}
	/* rule 491 */
	case 491: {
		zv::Arr attrs = PN_ATTRS(2, 1, 2);
		attrs.set("kind", zv::Val::integer(getFloatCastKind(PN_SEM(2, 1))));
		semValue = newNode("Expr\\Cast\\Double", std::move(attrs), PN_SEM(2, 2));
		return true;
	}
	/* rule 492 */
	case 492: {
		zv::Arr attrs = PN_ATTRS(2, 1, 2);
		attrs.set("kind", zv::Val::integer(getStringCastKind(PN_SEM(2, 1))));
		semValue = newNode("Expr\\Cast\\String_", std::move(attrs), PN_SEM(2, 2));
		return true;
	}
	/* rule 493 */
	case 493: {
		semValue = newNode("Expr\\Cast\\Array_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 494 */
	case 494: {
		semValue = newNode("Expr\\Cast\\Object_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 495 */
	case 495: {
		zv::Arr attrs = PN_ATTRS(2, 1, 2);
		attrs.set("kind", zv::Val::integer(getBoolCastKind(PN_SEM(2, 1))));
		semValue = newNode("Expr\\Cast\\Bool_", std::move(attrs), PN_SEM(2, 2));
		return true;
	}
	/* rule 496 */
	case 496: {
		semValue = newNode("Expr\\Cast\\Unset_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 497 */
	case 497: {
		semValue = newNode("Expr\\Cast\\Void_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 498 */
	case 498: {
		semValue = createExitExpr(PN_SEM(2, 1), stackPos - (2 - 1), PN_SEM(2, 2), PN_ATTRS(2, 1, 2));
		return true;
	}
	/* rule 499 */
	case 499: {
		semValue = newNode("Expr\\ErrorSuppress", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 501 */
	case 501: {
		semValue = newNode("Expr\\ShellExec", PN_ATTRS(3, 1, 3), PN_SEM(3, 2));
		return true;
	}
	/* rule 502 */
	case 502: {
		semValue = newNode("Expr\\Print_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 503 */
	case 503: {
		semValue = newNode("Expr\\Yield_", PN_ATTRS(1, 1, 1), nullptr, nullptr);
		return true;
	}
	/* rule 504 */
	case 504: {
		semValue = newNode("Expr\\Yield_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2), nullptr);
		return true;
	}
	/* rule 505 */
	case 505: {
		semValue = newNode("Expr\\Yield_", PN_ATTRS(4, 1, 4), PN_SEM(4, 4), PN_SEM(4, 2));
		return true;
	}
	/* rule 506 */
	case 506: {
		semValue = newNode("Expr\\YieldFrom", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 507 */
	case 507: {
		semValue = newNode("Expr\\Throw_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 508 */
	case 508: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("static", zv::Val::boolean(false));
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(8, 2)));
		sub1.set("params", zv::Val::copyOf(PN_SEM(8, 4)));
		sub1.set("returnType", zv::Val::copyOf(PN_SEM(8, 6)));
		sub1.set("expr", zv::Val::copyOf(PN_SEM(8, 8)));
		sub1.set("attrGroups", zv::Arr::empty());
		semValue = newNodeCtor("Expr\\ArrowFunction", PN_ATTRS(8, 1, 8), sub1);
		return true;
	}
	/* rule 509 */
	case 509: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("static", zv::Val::boolean(true));
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(9, 3)));
		sub1.set("params", zv::Val::copyOf(PN_SEM(9, 5)));
		sub1.set("returnType", zv::Val::copyOf(PN_SEM(9, 7)));
		sub1.set("expr", zv::Val::copyOf(PN_SEM(9, 9)));
		sub1.set("attrGroups", zv::Arr::empty());
		semValue = newNodeCtor("Expr\\ArrowFunction", PN_ATTRS(9, 1, 9), sub1);
		return true;
	}
	/* rule 510 */
	case 510: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("static", zv::Val::boolean(false));
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(8, 2)));
		sub1.set("params", zv::Val::copyOf(PN_SEM(8, 4)));
		sub1.set("uses", zv::Val::copyOf(PN_SEM(8, 6)));
		sub1.set("returnType", zv::Val::copyOf(PN_SEM(8, 7)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(8, 8)));
		sub1.set("attrGroups", zv::Arr::empty());
		semValue = newNodeCtor("Expr\\Closure", PN_ATTRS(8, 1, 8), sub1);
		return true;
	}
	/* rule 511 */
	case 511: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("static", zv::Val::boolean(true));
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(9, 3)));
		sub1.set("params", zv::Val::copyOf(PN_SEM(9, 5)));
		sub1.set("uses", zv::Val::copyOf(PN_SEM(9, 7)));
		sub1.set("returnType", zv::Val::copyOf(PN_SEM(9, 8)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(9, 9)));
		sub1.set("attrGroups", zv::Arr::empty());
		semValue = newNodeCtor("Expr\\Closure", PN_ATTRS(9, 1, 9), sub1);
		return true;
	}
	/* rule 512 */
	case 512: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("static", zv::Val::boolean(false));
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(9, 3)));
		sub1.set("params", zv::Val::copyOf(PN_SEM(9, 5)));
		sub1.set("returnType", zv::Val::copyOf(PN_SEM(9, 7)));
		sub1.set("expr", zv::Val::copyOf(PN_SEM(9, 9)));
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(9, 1)));
		semValue = newNodeCtor("Expr\\ArrowFunction", PN_ATTRS(9, 1, 9), sub1);
		return true;
	}
	/* rule 513 */
	case 513: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("static", zv::Val::boolean(true));
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(10, 4)));
		sub1.set("params", zv::Val::copyOf(PN_SEM(10, 6)));
		sub1.set("returnType", zv::Val::copyOf(PN_SEM(10, 8)));
		sub1.set("expr", zv::Val::copyOf(PN_SEM(10, 10)));
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(10, 1)));
		semValue = newNodeCtor("Expr\\ArrowFunction", PN_ATTRS(10, 1, 10), sub1);
		return true;
	}
	/* rule 514 */
	case 514: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("static", zv::Val::boolean(false));
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(9, 3)));
		sub1.set("params", zv::Val::copyOf(PN_SEM(9, 5)));
		sub1.set("uses", zv::Val::copyOf(PN_SEM(9, 7)));
		sub1.set("returnType", zv::Val::copyOf(PN_SEM(9, 8)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(9, 9)));
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(9, 1)));
		semValue = newNodeCtor("Expr\\Closure", PN_ATTRS(9, 1, 9), sub1);
		return true;
	}
	/* rule 515 */
	case 515: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("static", zv::Val::boolean(true));
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(10, 4)));
		sub1.set("params", zv::Val::copyOf(PN_SEM(10, 6)));
		sub1.set("uses", zv::Val::copyOf(PN_SEM(10, 8)));
		sub1.set("returnType", zv::Val::copyOf(PN_SEM(10, 9)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(10, 10)));
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(10, 1)));
		semValue = newNodeCtor("Expr\\Closure", PN_ATTRS(10, 1, 10), sub1);
		return true;
	}
	/* rule 516 */
	case 516: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("type", zv::Val::copyOf(PN_SEM(8, 2)));
		sub1.set("extends", zv::Val::copyOf(PN_SEM(8, 4)));
		sub1.set("implements", zv::Val::copyOf(PN_SEM(8, 5)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(8, 7)));
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(8, 1)));
		zv::Val t1 = newNodeCtor("Stmt\\Class_", PN_ATTRS(8, 1, 8), nullptr, sub1);
		semValue = arrayOf(t1, PN_SEM(8, 3));
		checkClass(itemAt(semValue.ref(), 0), -1);
		return true;
	}
	/* rule 517 */
	case 517: {
		semValue = newNode("Expr\\New_", PN_ATTRS(3, 1, 3), PN_SEM(3, 2), PN_SEM(3, 3));
		return true;
	}
	/* rule 518 (from action-overrides/4e1822bc7002c2a89dd7a63f0c78b90f91b21da1.inc) */
	case 518: {
		/* list($class, $ctorArgs) = $self->semStack[...]; $$ = new Expr\New_($class, $ctorArgs, attributes); */
		zv::Ref pair = PN_SEM(2, 2);
		semValue = newNode("Expr\\New_", PN_ATTRS(2, 1, 2), itemAt(pair, 0), itemAt(pair, 1));
		return true;
	}
	/* rule 519 */
	case 519: {
		zv::Val t1 = zv::Arr::empty();
		semValue = newNode("Expr\\New_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2), t1);
		return true;
	}
	/* rule 522 */
	case 522: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 523 */
	case 523: {
		semValue = PN_SEM(4, 3);
		return true;
	}
	/* rule 525 */
	case 525: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 526 */
	case 526: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 527 */
	case 527: {
		semValue = newNode("Node\\ClosureUse", PN_ATTRS(2, 1, 2), PN_SEM(2, 2), PN_SEM(2, 1));
		return true;
	}
	/* rule 528 */
	case 528: {
		semValue = newName(PN_SEM(1, 1), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 529 */
	case 529: {
		semValue = newNode("Expr\\FuncCall", PN_ATTRS(2, 1, 2), PN_SEM(2, 1), PN_SEM(2, 2));
		return true;
	}
	/* rule 530 */
	case 530: {
		semValue = newNode("Expr\\FuncCall", PN_ATTRS(2, 1, 2), PN_SEM(2, 1), PN_SEM(2, 2));
		return true;
	}
	/* rule 531 */
	case 531: {
		semValue = newNode("Expr\\FuncCall", PN_ATTRS(2, 1, 2), PN_SEM(2, 1), PN_SEM(2, 2));
		return true;
	}
	/* rule 532 */
	case 532: {
		semValue = newNode("Expr\\StaticCall", PN_ATTRS(4, 1, 4), PN_SEM(4, 1), PN_SEM(4, 3), PN_SEM(4, 4));
		return true;
	}
	/* rule 533 */
	case 533: {
		semValue = newName(PN_SEM(1, 1), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 535 */
	case 535: {
		semValue = newName(PN_SEM(1, 1), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 536 */
	case 536: {
		semValue = newName(PN_SEM(1, 1), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 537 */
	case 537: {
		zv::Val t1 = substr(PN_SEM(1, 1), 1);
		semValue = newNameVariant("Name\\FullyQualified", t1.ref(), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 538 */
	case 538: {
		zv::Val t1 = substr(PN_SEM(1, 1), 10);
		semValue = newNameVariant("Name\\Relative", t1.ref(), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 541 */
	case 541: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 542 */
	case 542: {
		semValue = newNode("Expr\\Error", PN_ATTRS(1, 1, 1));
		errorState = 2;
		return true;
	}
	/* rule 545 */
	case 545: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 546 (from action-overrides/33cd4fd5bb9aa00cd570b40ef1921386414be6a8.inc) */
	case 546: {
		/* $$ = array($1); foreach ($$ as $s): backtick parseEscapeSequences() on InterpolatedStringParts */
		zv::Arr arr = arrayOf(PN_SEM(1, 1));
		for (auto entry : arr.arrRef()) {
			if (isInstanceOf(entry.value(), "Node\\InterpolatedStringPart")) {
				parseEscapeSequencesInPart(entry.value(), "`");
			}
		}
		semValue = std::move(arr);
		return true;
	}
	/* rule 547 (from action-overrides/dd5881dec8adf82f4b92c400bfedca8c43ef66b4.inc) */
	case 547: {
		/* foreach ($1 as $s): backtick parseEscapeSequences() on InterpolatedStringParts; $$ = $1 */
		for (auto entry : zv::ArrRef(PN_SEM(1, 1).raw())) {
			if (isInstanceOf(entry.value(), "Node\\InterpolatedStringPart")) {
				parseEscapeSequencesInPart(entry.value(), "`");
			}
		}
		semValue = PN_SEM(1, 1);
		return true;
	}
	/* rule 548 */
	case 548: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 550 */
	case 550: {
		semValue = newNode("Expr\\ConstFetch", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 551 */
	case 551: {
		semValue = newNode("Scalar\\MagicConst\\Line", PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 552 */
	case 552: {
		semValue = newNode("Scalar\\MagicConst\\File", PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 553 */
	case 553: {
		semValue = newNode("Scalar\\MagicConst\\Dir", PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 554 */
	case 554: {
		semValue = newNode("Scalar\\MagicConst\\Class_", PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 555 */
	case 555: {
		semValue = newNode("Scalar\\MagicConst\\Trait_", PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 556 */
	case 556: {
		semValue = newNode("Scalar\\MagicConst\\Method", PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 557 */
	case 557: {
		semValue = newNode("Scalar\\MagicConst\\Function_", PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 558 */
	case 558: {
		semValue = newNode("Scalar\\MagicConst\\Namespace_", PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 559 */
	case 559: {
		semValue = newNode("Scalar\\MagicConst\\Property", PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 560 */
	case 560: {
		semValue = newNode("Expr\\ClassConstFetch", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 561 */
	case 561: {
		semValue = newNode("Expr\\ClassConstFetch", PN_ATTRS(5, 1, 5), PN_SEM(5, 1), PN_SEM(5, 4));
		return true;
	}
	/* rule 562 */
	case 562: {
		zv::Val t1 = newNode("Expr\\Error", PN_ATTRS(3, 3, 3));
		semValue = newNode("Expr\\ClassConstFetch", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), t1);
		errorState = 2;
		return true;
	}
	/* rule 563 */
	case 563: {
		zv::Arr attrs = PN_ATTRS(3, 1, 3);
		attrs.set("kind", zv::Val::integer(2 /* Expr\Array_::KIND_SHORT */));
		semValue = newNode("Expr\\Array_", std::move(attrs), PN_SEM(3, 2));
		return true;
	}
	/* rule 564 */
	case 564: {
		zv::Arr attrs = PN_ATTRS(4, 1, 4);
		attrs.set("kind", zv::Val::integer(1 /* Expr\Array_::KIND_LONG */));
		semValue = newNode("Expr\\Array_", std::move(attrs), PN_SEM(4, 3));
		createdArraysAdd(semValue.ref());
		return true;
	}
	/* rule 565 */
	case 565: {
		semValue = PN_SEM(1, 1);
		createdArraysAdd(semValue.ref());
		return true;
	}
	/* rule 566 */
	case 566: {
		semValue = stringFromString(PN_SEM(1, 1), PN_ATTRS(1, 1, 1), phpVersionId >= 70000 /* PhpVersion::supportsUnicodeEscapes() */);
		return true;
	}
	/* rule 567 (from action-overrides/302966ab17149baef35dbb007abfe742d2706046.inc) */
	case 567: {
		/* $attrs['kind'] = KIND_DOUBLE_QUOTED; double-quote parseEscapeSequences() on the
		 * InterpolatedStringParts of $2; $$ = new Scalar\InterpolatedString($2, $attrs) */
		zv::Arr attrs = PN_ATTRS(3, 1, 3);
		attrs.set("kind", zv::Val::integer(2 /* Scalar\String_::KIND_DOUBLE_QUOTED */));
		for (auto entry : zv::ArrRef(PN_SEM(3, 2).raw())) {
			if (isInstanceOf(entry.value(), "Node\\InterpolatedStringPart")) {
				parseEscapeSequencesInPart(entry.value(), "\"");
			}
		}
		semValue = newNode("Scalar\\InterpolatedString", std::move(attrs), PN_SEM(3, 2));
		return true;
	}
	/* rule 568 */
	case 568: {
		semValue = parseLNumber(PN_SEM(1, 1), PN_ATTRS(1, 1, 1), phpVersionId < 70000 /* PhpVersion::allowsInvalidOctals() */);
		return true;
	}
	/* rule 569 */
	case 569: {
		semValue = floatFromString(PN_SEM(1, 1), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 573 */
	case 573: {
		semValue = parseDocString(PN_SEM(3, 1), PN_SEM(3, 2), PN_SEM(3, 3), PN_ATTRS(3, 1, 3), PN_ATTRS(3, 3, 3), true);
		return true;
	}
	/* rule 574 */
	case 574: {
		zv::Val t1 = zv::Val::string("", 0);
		semValue = parseDocString(PN_SEM(2, 1), t1.ref(), PN_SEM(2, 2), PN_ATTRS(2, 1, 2), PN_ATTRS(2, 2, 2), true);
		return true;
	}
	/* rule 575 */
	case 575: {
		semValue = parseDocString(PN_SEM(3, 1), PN_SEM(3, 2), PN_SEM(3, 3), PN_ATTRS(3, 1, 3), PN_ATTRS(3, 3, 3), true);
		return true;
	}
	/* rule 576 */
	case 576: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 579 */
	case 579: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 586 */
	case 586: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 590 */
	case 590: {
		semValue = newNode("Expr\\ArrayDimFetch", PN_ATTRS(4, 1, 4), PN_SEM(4, 1), PN_SEM(4, 3));
		return true;
	}
	/* rule 592 */
	case 592: {
		semValue = newNode("Expr\\MethodCall", PN_ATTRS(4, 1, 4), PN_SEM(4, 1), PN_SEM(4, 3), PN_SEM(4, 4));
		return true;
	}
	/* rule 593 */
	case 593: {
		semValue = newNode("Expr\\NullsafeMethodCall", PN_ATTRS(4, 1, 4), PN_SEM(4, 1), PN_SEM(4, 3), PN_SEM(4, 4));
		return true;
	}
	/* rule 594 */
	case 594: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 598 */
	case 598: {
		semValue = newNode("Expr\\PropertyFetch", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 599 */
	case 599: {
		semValue = newNode("Expr\\NullsafePropertyFetch", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 601 */
	case 601: {
		semValue = newNode("Expr\\Variable", PN_ATTRS(4, 1, 4), PN_SEM(4, 3));
		return true;
	}
	/* rule 602 */
	case 602: {
		semValue = newNode("Expr\\Variable", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 603 */
	case 603: {
		zv::Val t1 = newNode("Expr\\Error", PN_ATTRS(2, 1, 2));
		semValue = newNode("Expr\\Variable", PN_ATTRS(2, 1, 2), t1);
		errorState = 2;
		return true;
	}
	/* rule 604 (from action-overrides/9010e0ff64f5ffbc6b330506e2e596585337c3f7.inc) */
	case 604: {
		/* $var = $1->name; $$ = \is_string($var) ? new VarLikeIdentifier($var, attributes) : $var; */
		zv::Ref var = prop(PN_SEM(1, 1), "name");
		if (var.raw() != NULL && var.isString()) {
			semValue = newNode("Node\\VarLikeIdentifier", PN_ATTRS(1, 1, 1), var);
		} else if (var.raw() != NULL) {
			semValue = var;
		} else {
			semValue = zv::Val::null();
		}
		return true;
	}
	/* rule 605 */
	case 605: {
		semValue = newNode("Expr\\StaticPropertyFetch", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 607 */
	case 607: {
		semValue = newNode("Expr\\ArrayDimFetch", PN_ATTRS(4, 1, 4), PN_SEM(4, 1), PN_SEM(4, 3));
		return true;
	}
	/* rule 608 */
	case 608: {
		semValue = newNode("Expr\\PropertyFetch", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 609 */
	case 609: {
		semValue = newNode("Expr\\NullsafePropertyFetch", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 610 */
	case 610: {
		semValue = newNode("Expr\\StaticPropertyFetch", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 611 */
	case 611: {
		semValue = newNode("Expr\\StaticPropertyFetch", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 613 */
	case 613: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 616 */
	case 616: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 618 */
	case 618: {
		semValue = newNode("Expr\\Error", PN_ATTRS(1, 1, 1));
		errorState = 2;
		return true;
	}
	/* rule 619 */
	case 619: {
		semValue = newNode("Expr\\List_", PN_ATTRS(4, 1, 4), PN_SEM(4, 3));
		setNodeAttribute(semValue.ref(), "kind", zv::Val::integer(1 /* Expr\List_::KIND_LIST */));
		postprocessList(semValue.ref());
		return true;
	}
	/* rule 620 (from action-overrides/c903abbc90c691e24a2e00c5eeed110ffb990a89.inc) */
	case 620: {
		/* $$ = $1; if ($$[count($$)-1]->value instanceof Expr\Error) array_pop($$); */
		semValue = PN_SEM(1, 1);
		uint32_t n = zv::ArrRef(semValue.raw()).size();
		if (n > 0) {
			zv::Ref last = itemAt(semValue.ref(), n - 1);
			if (last.raw() != NULL) {
				zv::Ref value = prop(last, "value");
				if (value.raw() != NULL && isInstanceOf(value, "Expr\\Error")) {
					phpArrayPop(semValue.raw());
				}
			}
		}
		return true;
	}
	/* rule 622 */
	case 622: {
		/* do nothing -- prevent default action of $$=$self->semStack[$1]. See $551. */
		return true;
	}
	/* rule 623 */
	case 623: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 624 */
	case 624: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 625 */
	case 625: {
		semValue = newNode("Node\\ArrayItem", PN_ATTRS(1, 1, 1), PN_SEM(1, 1), nullptr, zv::Val::boolean(false), zv::Val::boolean(false) /* ctor default for omitted $unpack */);
		return true;
	}
	/* rule 626 */
	case 626: {
		semValue = newNode("Node\\ArrayItem", PN_ATTRS(2, 1, 2), PN_SEM(2, 2), nullptr, zv::Val::boolean(true), zv::Val::boolean(false) /* ctor default for omitted $unpack */);
		return true;
	}
	/* rule 627 */
	case 627: {
		semValue = newNode("Node\\ArrayItem", PN_ATTRS(1, 1, 1), PN_SEM(1, 1), nullptr, zv::Val::boolean(false), zv::Val::boolean(false) /* ctor default for omitted $unpack */);
		return true;
	}
	/* rule 628 */
	case 628: {
		semValue = newNode("Node\\ArrayItem", PN_ATTRS(3, 1, 3), PN_SEM(3, 3), PN_SEM(3, 1), zv::Val::boolean(false), zv::Val::boolean(false) /* ctor default for omitted $unpack */);
		return true;
	}
	/* rule 629 */
	case 629: {
		semValue = newNode("Node\\ArrayItem", PN_ATTRS(4, 1, 4), PN_SEM(4, 4), PN_SEM(4, 1), zv::Val::boolean(true), zv::Val::boolean(false) /* ctor default for omitted $unpack */);
		return true;
	}
	/* rule 630 */
	case 630: {
		semValue = newNode("Node\\ArrayItem", PN_ATTRS(3, 1, 3), PN_SEM(3, 3), PN_SEM(3, 1), zv::Val::boolean(false), zv::Val::boolean(false) /* ctor default for omitted $unpack */);
		return true;
	}
	/* rule 631 */
	case 631: {
		semValue = newNode("Node\\ArrayItem", PN_ATTRS(2, 1, 2), PN_SEM(2, 2), nullptr, zv::Val::boolean(false), zv::Val::boolean(true));
		return true;
	}
	/* rule 632 (from action-overrides/0ffe3fa3e57871da42f4e4d382a75a3380e24f77.inc) */
	case 632: {
		/* Error node created now to remember the position; later either reported or
		 * converted to a null element, depending on creation vs destructuring context.
		 * createEmptyElemAttributes() delegates to getAttributesForToken(); the SAME
		 * attrs array is shared between the Error node and the ArrayItem, as in PHP. */
		zv::Arr attrs = getAttributesForToken(tokenPos);
		zv::Val attrsForError = zv::Val::copyOf(attrs.ref());
		zv::Val err = newNode("Expr\\Error", std::move(attrsForError));
		semValue = newNode("Node\\ArrayItem", std::move(attrs), err, nullptr, zv::Val::boolean(false), zv::Val::boolean(false));
		return true;
	}
	/* rule 633 */
	case 633: {
		pushOnto(PN_SEM(2, 1), PN_SEM(2, 2));
		semValue = PN_SEM(2, 1);
		return true;
	}
	/* rule 634 */
	case 634: {
		pushOnto(PN_SEM(2, 1), PN_SEM(2, 2));
		semValue = PN_SEM(2, 1);
		return true;
	}
	/* rule 635 */
	case 635: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 636 */
	case 636: {
		semValue = arrayOf(PN_SEM(2, 1), PN_SEM(2, 2));
		return true;
	}
	/* rule 637 */
	case 637: {
		zv::Arr attrs = PN_ATTRS(1, 1, 1);
		attrs.set("rawValue", zv::Val::copyOf(PN_SEM(1, 1)));
		semValue = newNode("Node\\InterpolatedStringPart", std::move(attrs), PN_SEM(1, 1));
		return true;
	}
	/* rule 638 */
	case 638: {
		semValue = newNode("Expr\\Variable", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 640 */
	case 640: {
		semValue = newNode("Expr\\ArrayDimFetch", PN_ATTRS(4, 1, 4), PN_SEM(4, 1), PN_SEM(4, 3));
		return true;
	}
	/* rule 641 */
	case 641: {
		semValue = newNode("Expr\\PropertyFetch", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 642 */
	case 642: {
		semValue = newNode("Expr\\NullsafePropertyFetch", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 643 */
	case 643: {
		semValue = newNode("Expr\\Variable", PN_ATTRS(3, 1, 3), PN_SEM(3, 2));
		return true;
	}
	/* rule 644 */
	case 644: {
		semValue = newNode("Expr\\Variable", PN_ATTRS(3, 1, 3), PN_SEM(3, 2));
		return true;
	}
	/* rule 645 */
	case 645: {
		semValue = newNode("Expr\\ArrayDimFetch", PN_ATTRS(6, 1, 6), PN_SEM(6, 2), PN_SEM(6, 4));
		return true;
	}
	/* rule 646 */
	case 646: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 647 */
	case 647: {
		semValue = newNode("Scalar\\String_", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 648 */
	case 648: {
		semValue = parseNumString(PN_SEM(1, 1), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 649 (from action-overrides/4d582a24c4d2e51f11f292d174b7c3141cadb3e4.inc) */
	case 649: {
		/* $$ = $self->parseNumString('-' . $2, attributes) */
		zend_string *cat = zend_string_concat2("-", 1,
			Z_STRVAL_P(PN_SEM(2, 2).raw()), Z_STRLEN_P(PN_SEM(2, 2).raw()));
		zv::Val tmp = zv::Val::adoptString(cat);
		semValue = parseNumString(tmp.ref(), PN_ATTRS(2, 1, 2));
		return true;
	}
	default:
		return false;
	}
}

} // namespace phpstanturbo
