/* GENERATED by turbo-ext/bin/generate-parser-actions.php — do not edit */
/* Dispatch boundaries for ParserEngine::reduce() (ParserRunner.cpp): rules
 * below PN_REDUCE_SPLIT_1 live in ParserRunnerActions1.cpp (reduceRange1),
 * below PN_REDUCE_SPLIT_2 in ParserRunnerActions2.cpp (reduceRange2), the
 * rest in ParserRunnerActions3.cpp (reduceRange3). */

#ifndef PHPSTANTURBO_PN_ACTIONS_SPLIT_H
#define PHPSTANTURBO_PN_ACTIONS_SPLIT_H

#define PN_REDUCE_SPLIT_1 269
#define PN_REDUCE_SPLIT_2 454

#endif
