/* GENERATED by turbo-ext/bin/generate-parser-actions.php — do not edit */
/*
 * Reduce actions for rules 269-453 of php-parser's Php8 grammar
 * (vendor/nikic/php-parser/lib/PhpParser/Parser/Php8.php, initReduceCallbacks).
 * Rules with a null callback have no case here; returning false makes the
 * engine apply the default action. Hand-ported special cases are emitted
 * verbatim from src/parser/action-overrides/<sha1-of-php-body>.inc.
 */

#include "ParserEngine.h"

namespace phpstanturbo {

bool ParserEngine::reduceRange2(int rule, int stackPos)
{
	switch (rule) {
	/* rule 269 */
	case 269: {
		pushOnto(PN_SEM(2, 1), PN_SEM(2, 2));
		semValue = PN_SEM(2, 1);
		return true;
	}
	/* rule 270 */
	case 270: {
		semValue = newNode("Stmt\\ElseIf_", PN_ATTRS(6, 1, 6), PN_SEM(6, 3), PN_SEM(6, 6));
		fixupAlternativeElse(semValue.ref());
		return true;
	}
	/* rule 271 */
	case 271: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 272 */
	case 272: {
		semValue = newNode("Stmt\\Else_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 273 */
	case 273: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 274 */
	case 274: {
		semValue = newNode("Stmt\\Else_", PN_ATTRS(3, 1, 3), PN_SEM(3, 3));
		fixupAlternativeElse(semValue.ref());
		return true;
	}
	/* rule 275 */
	case 275: {
		semValue = arrayOf(PN_SEM(1, 1), zv::Val::boolean(false));
		return true;
	}
	/* rule 276 */
	case 276: {
		semValue = arrayOf(PN_SEM(2, 2), zv::Val::boolean(true));
		return true;
	}
	/* rule 277 */
	case 277: {
		semValue = arrayOf(PN_SEM(1, 1), zv::Val::boolean(false));
		return true;
	}
	/* rule 278 */
	case 278: {
		zv::Val t1 = fixupArrayDestructuring(PN_SEM(1, 1));
		semValue = arrayOf(t1, zv::Val::boolean(false));
		return true;
	}
	/* rule 280 */
	case 280: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 281 */
	case 281: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 282 */
	case 282: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 283 */
	case 283: {
		semValue = zv::Val::integer(0);
		return true;
	}
	/* rule 284 */
	case 284: {
		checkModifier(PN_SEM(2, 1).toLong(), PN_SEM(2, 2).toLong(), stackPos - (2 - 2));
		semValue = zv::Val::integer(PN_SEM(2, 1).toLong() | PN_SEM(2, 2).toLong());
		return true;
	}
	/* rule 285 */
	case 285: {
		semValue = zv::Val::integer(1 /* Modifiers::PUBLIC */);
		return true;
	}
	/* rule 286 */
	case 286: {
		semValue = zv::Val::integer(2 /* Modifiers::PROTECTED */);
		return true;
	}
	/* rule 287 */
	case 287: {
		semValue = zv::Val::integer(4 /* Modifiers::PRIVATE */);
		return true;
	}
	/* rule 288 */
	case 288: {
		semValue = zv::Val::integer(128 /* Modifiers::PUBLIC_SET */);
		return true;
	}
	/* rule 289 */
	case 289: {
		semValue = zv::Val::integer(256 /* Modifiers::PROTECTED_SET */);
		return true;
	}
	/* rule 290 */
	case 290: {
		semValue = zv::Val::integer(512 /* Modifiers::PRIVATE_SET */);
		return true;
	}
	/* rule 291 */
	case 291: {
		semValue = zv::Val::integer(64 /* Modifiers::READONLY */);
		return true;
	}
	/* rule 292 */
	case 292: {
		semValue = zv::Val::integer(32 /* Modifiers::FINAL */);
		return true;
	}
	/* rule 293 */
	case 293: {
		semValue = newNode("Node\\Param", PN_ATTRS(7, 1, 7), PN_SEM(7, 6), nullptr, PN_SEM(7, 3), PN_SEM(7, 4), PN_SEM(7, 5), PN_SEM(7, 2), PN_SEM(7, 1), PN_SEM(7, 7));
		checkParam(semValue.ref());
		addPropertyNameToHooks(semValue.ref());
		return true;
	}
	/* rule 294 */
	case 294: {
		semValue = newNode("Node\\Param", PN_ATTRS(9, 1, 9), PN_SEM(9, 6), PN_SEM(9, 8), PN_SEM(9, 3), PN_SEM(9, 4), PN_SEM(9, 5), PN_SEM(9, 2), PN_SEM(9, 1), PN_SEM(9, 9));
		checkParam(semValue.ref());
		addPropertyNameToHooks(semValue.ref());
		return true;
	}
	/* rule 295 */
	case 295: {
		zv::Val t1 = newNode("Expr\\Error", PN_ATTRS(6, 1, 6));
		semValue = newNode("Node\\Param", PN_ATTRS(6, 1, 6), t1, nullptr, PN_SEM(6, 3), PN_SEM(6, 4), PN_SEM(6, 5), PN_SEM(6, 2), PN_SEM(6, 1), zv::Arr::empty() /* ctor default for omitted $hooks */);
		return true;
	}
	/* rule 297 */
	case 297: {
		semValue = newNode("Node\\NullableType", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 298 */
	case 298: {
		semValue = newNode("Node\\UnionType", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 301 */
	case 301: {
		zv::Val t1 = zv::Val::string("static", 6);
		semValue = newName(t1.ref(), PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 302 */
	case 302: {
		semValue = handleBuiltinTypes(PN_SEM(1, 1));
		return true;
	}
	/* rule 303 */
	case 303: {
		semValue = newNode("Node\\Identifier", PN_ATTRS(1, 1, 1), zv::Val::string("array", 5));
		return true;
	}
	/* rule 304 */
	case 304: {
		semValue = newNode("Node\\Identifier", PN_ATTRS(1, 1, 1), zv::Val::string("callable", 8));
		return true;
	}
	/* rule 306 */
	case 306: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 307 */
	case 307: {
		semValue = arrayOf(PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 308 */
	case 308: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 310 */
	case 310: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 311 */
	case 311: {
		semValue = arrayOf(PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 312 */
	case 312: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 313 */
	case 313: {
		semValue = arrayOf(PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 314 */
	case 314: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 315 */
	case 315: {
		semValue = newNode("Node\\IntersectionType", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 316 */
	case 316: {
		semValue = arrayOf(PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 317 */
	case 317: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 318 */
	case 318: {
		semValue = newNode("Node\\IntersectionType", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 320 */
	case 320: {
		semValue = newNode("Node\\NullableType", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 321 */
	case 321: {
		semValue = newNode("Node\\UnionType", PN_ATTRS(1, 1, 1), PN_SEM(1, 1));
		return true;
	}
	/* rule 323 */
	case 323: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 325 */
	case 325: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 326 */
	case 326: {
		semValue = PN_SEM(2, 2);
		return true;
	}
	/* rule 327 */
	case 327: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 328 */
	case 328: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 329 */
	case 329: {
		semValue = PN_SEM(4, 2);
		return true;
	}
	/* rule 330 */
	case 330: {
		semValue = arrayOf(PN_SEM(3, 2));
		return true;
	}
	/* rule 331 */
	case 331: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 332 */
	case 332: {
		semValue = PN_SEM(4, 2);
		return true;
	}
	/* rule 333 */
	case 333: {
		zv::Val t1 = newNode("Node\\Arg", PN_ATTRS(4, 1, 4), PN_SEM(4, 2), zv::Val::boolean(false), zv::Val::boolean(false), nullptr /* ctor default for omitted $name */);
		semValue = arrayOf(t1);
		return true;
	}
	/* rule 334 */
	case 334: {
		semValue = arrayOf(PN_SEM(3, 2));
		return true;
	}
	/* rule 335 */
	case 335: {
		zv::Val t1 = newNode("Node\\Arg", PN_ATTRS(3, 1, 1), PN_SEM(3, 1), zv::Val::boolean(false), zv::Val::boolean(false), nullptr /* ctor default for omitted $name */);
		semValue = arrayOf(t1, PN_SEM(3, 3));
		return true;
	}
	/* rule 336 */
	case 336: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 337 */
	case 337: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 338 */
	case 338: {
		semValue = newNode("Node\\VariadicPlaceholder", PN_ATTRS(1, 1, 1));
		return true;
	}
	/* rule 339 */
	case 339: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 340 */
	case 340: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 341 */
	case 341: {
		semValue = newNode("Node\\Arg", PN_ATTRS(2, 1, 2), PN_SEM(2, 2), zv::Val::boolean(true), zv::Val::boolean(false), nullptr /* ctor default for omitted $name */);
		return true;
	}
	/* rule 342 */
	case 342: {
		semValue = newNode("Node\\Arg", PN_ATTRS(2, 1, 2), PN_SEM(2, 2), zv::Val::boolean(false), zv::Val::boolean(true), nullptr /* ctor default for omitted $name */);
		return true;
	}
	/* rule 343 */
	case 343: {
		semValue = newNode("Node\\Arg", PN_ATTRS(3, 1, 3), PN_SEM(3, 3), zv::Val::boolean(false), zv::Val::boolean(false), PN_SEM(3, 1));
		return true;
	}
	/* rule 344 */
	case 344: {
		semValue = newNode("Node\\Arg", PN_ATTRS(1, 1, 1), PN_SEM(1, 1), zv::Val::boolean(false), zv::Val::boolean(false), nullptr /* ctor default for omitted $name */);
		return true;
	}
	/* rule 345 */
	case 345: {
		semValue = PN_SEM(1, 1);
		return true;
	}
	/* rule 347 */
	case 347: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 348 */
	case 348: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 351 */
	case 351: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 352 */
	case 352: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 353 */
	case 353: {
		semValue = newNode("Node\\StaticVar", PN_ATTRS(1, 1, 1), PN_SEM(1, 1), nullptr);
		return true;
	}
	/* rule 354 */
	case 354: {
		semValue = newNode("Node\\StaticVar", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 355 */
	case 355: {
		if (!PN_SEM(2, 2).isNull()) {
			pushOnto(PN_SEM(2, 1), PN_SEM(2, 2));
			semValue = PN_SEM(2, 1);
		} else {
			semValue = PN_SEM(2, 1);
		}
		return true;
	}
	/* rule 356 */
	case 356: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 357 (from action-overrides/aeb46c35c63d49d076d22af3cd5ef3ffc214e9dc.inc) */
	case 357: {
		/* $nop = $self->maybeCreateZeroLengthNop($self->tokenPos);
		 * if ($nop !== null) { $self->semStack[$1][] = $nop; } $$ = $self->semStack[$1]; */
		zv::Val nop = maybeCreateZeroLengthNop(tokenPos);
		if (!nop.isNull()) {
			pushOnto(PN_SEM(1, 1), std::move(nop));
		}
		semValue = PN_SEM(1, 1);
		return true;
	}
	/* rule 358 */
	case 358: {
		semValue = newNode("Stmt\\Property", PN_ATTRS(5, 1, 5), PN_SEM(5, 2), PN_SEM(5, 4), PN_SEM(5, 3), PN_SEM(5, 1), zv::Arr::empty() /* ctor default for omitted $hooks */);
		return true;
	}
	/* rule 359 */
	case 359: {
		semValue = newNode("Stmt\\Property", PN_ATTRS(7, 1, 7), PN_SEM(7, 2), PN_SEM(7, 4), PN_SEM(7, 3), PN_SEM(7, 1), PN_SEM(7, 6));
		checkPropertyHooksForMultiProperty(semValue.ref(), stackPos - (7 - 5));
		checkEmptyPropertyHookList(PN_SEM(7, 6), stackPos - (7 - 5));
		addPropertyNameToHooks(semValue.ref());
		return true;
	}
	/* rule 360 */
	case 360: {
		semValue = newNode("Stmt\\ClassConst", PN_ATTRS(5, 1, 5), PN_SEM(5, 4), PN_SEM(5, 2), PN_SEM(5, 1), nullptr /* ctor default for omitted $type */);
		checkClassConst(semValue.ref(), stackPos - (5 - 2));
		return true;
	}
	/* rule 361 */
	case 361: {
		semValue = newNode("Stmt\\ClassConst", PN_ATTRS(6, 1, 6), PN_SEM(6, 5), PN_SEM(6, 2), PN_SEM(6, 1), PN_SEM(6, 4));
		checkClassConst(semValue.ref(), stackPos - (6 - 2));
		return true;
	}
	/* rule 362 */
	case 362: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("type", zv::Val::copyOf(PN_SEM(10, 2)));
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(10, 4)));
		sub1.set("params", zv::Val::copyOf(PN_SEM(10, 7)));
		sub1.set("returnType", zv::Val::copyOf(PN_SEM(10, 9)));
		sub1.set("stmts", zv::Val::copyOf(PN_SEM(10, 10)));
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(10, 1)));
		semValue = newNodeCtor("Stmt\\ClassMethod", PN_ATTRS(10, 1, 10), PN_SEM(10, 5), sub1);
		checkClassMethod(semValue.ref(), stackPos - (10 - 2));
		return true;
	}
	/* rule 363 */
	case 363: {
		semValue = newNode("Stmt\\TraitUse", PN_ATTRS(3, 1, 3), PN_SEM(3, 2), PN_SEM(3, 3));
		return true;
	}
	/* rule 364 */
	case 364: {
		semValue = newNodeCtor("Stmt\\EnumCase", PN_ATTRS(5, 1, 5), PN_SEM(5, 3), PN_SEM(5, 4), PN_SEM(5, 1));
		return true;
	}
	/* rule 365 */
	case 365: {
		semValue = zv::Val::null();
		/* will be skipped */
		return true;
	}
	/* rule 366 */
	case 366: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 367 */
	case 367: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 368 */
	case 368: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 369 */
	case 369: {
		pushOnto(PN_SEM(2, 1), PN_SEM(2, 2));
		semValue = PN_SEM(2, 1);
		return true;
	}
	/* rule 370 */
	case 370: {
		semValue = newNodeCtor("Stmt\\TraitUseAdaptation\\Precedence", PN_ATTRS(4, 1, 4), itemAt(PN_SEM(4, 1), 0), itemAt(PN_SEM(4, 1), 1), PN_SEM(4, 3));
		return true;
	}
	/* rule 371 */
	case 371: {
		semValue = newNodeCtor("Stmt\\TraitUseAdaptation\\Alias", PN_ATTRS(5, 1, 5), itemAt(PN_SEM(5, 1), 0), itemAt(PN_SEM(5, 1), 1), PN_SEM(5, 3), PN_SEM(5, 4));
		return true;
	}
	/* rule 372 */
	case 372: {
		semValue = newNodeCtor("Stmt\\TraitUseAdaptation\\Alias", PN_ATTRS(4, 1, 4), itemAt(PN_SEM(4, 1), 0), itemAt(PN_SEM(4, 1), 1), PN_SEM(4, 3), nullptr);
		return true;
	}
	/* rule 373 */
	case 373: {
		semValue = newNodeCtor("Stmt\\TraitUseAdaptation\\Alias", PN_ATTRS(4, 1, 4), itemAt(PN_SEM(4, 1), 0), itemAt(PN_SEM(4, 1), 1), nullptr, PN_SEM(4, 3));
		return true;
	}
	/* rule 374 */
	case 374: {
		semValue = newNodeCtor("Stmt\\TraitUseAdaptation\\Alias", PN_ATTRS(4, 1, 4), itemAt(PN_SEM(4, 1), 0), itemAt(PN_SEM(4, 1), 1), nullptr, PN_SEM(4, 3));
		return true;
	}
	/* rule 375 */
	case 375: {
		semValue = arrayOf(PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 377 */
	case 377: {
		semValue = arrayOf(zv::Val::null(), PN_SEM(1, 1));
		return true;
	}
	/* rule 378 */
	case 378: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 381 */
	case 381: {
		semValue = zv::Val::integer(0);
		return true;
	}
	/* rule 382 */
	case 382: {
		semValue = zv::Val::integer(0);
		return true;
	}
	/* rule 385 */
	case 385: {
		checkModifier(PN_SEM(2, 1).toLong(), PN_SEM(2, 2).toLong(), stackPos - (2 - 2));
		semValue = zv::Val::integer(PN_SEM(2, 1).toLong() | PN_SEM(2, 2).toLong());
		return true;
	}
	/* rule 386 */
	case 386: {
		semValue = zv::Val::integer(1 /* Modifiers::PUBLIC */);
		return true;
	}
	/* rule 387 */
	case 387: {
		semValue = zv::Val::integer(2 /* Modifiers::PROTECTED */);
		return true;
	}
	/* rule 388 */
	case 388: {
		semValue = zv::Val::integer(4 /* Modifiers::PRIVATE */);
		return true;
	}
	/* rule 389 */
	case 389: {
		semValue = zv::Val::integer(128 /* Modifiers::PUBLIC_SET */);
		return true;
	}
	/* rule 390 */
	case 390: {
		semValue = zv::Val::integer(256 /* Modifiers::PROTECTED_SET */);
		return true;
	}
	/* rule 391 */
	case 391: {
		semValue = zv::Val::integer(512 /* Modifiers::PRIVATE_SET */);
		return true;
	}
	/* rule 392 */
	case 392: {
		semValue = zv::Val::integer(8 /* Modifiers::STATIC */);
		return true;
	}
	/* rule 393 */
	case 393: {
		semValue = zv::Val::integer(16 /* Modifiers::ABSTRACT */);
		return true;
	}
	/* rule 394 */
	case 394: {
		semValue = zv::Val::integer(32 /* Modifiers::FINAL */);
		return true;
	}
	/* rule 395 */
	case 395: {
		semValue = zv::Val::integer(64 /* Modifiers::READONLY */);
		return true;
	}
	/* rule 397 */
	case 397: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 398 */
	case 398: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 399 */
	case 399: {
		zv::Val t1 = substr(PN_SEM(1, 1), 1);
		semValue = newNode("Node\\VarLikeIdentifier", PN_ATTRS(1, 1, 1), t1);
		return true;
	}
	/* rule 400 */
	case 400: {
		semValue = newNode("Node\\PropertyItem", PN_ATTRS(1, 1, 1), PN_SEM(1, 1), nullptr);
		return true;
	}
	/* rule 401 */
	case 401: {
		semValue = newNode("Node\\PropertyItem", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 402 */
	case 402: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 403 */
	case 403: {
		pushOnto(PN_SEM(2, 1), PN_SEM(2, 2));
		semValue = PN_SEM(2, 1);
		return true;
	}
	/* rule 404 */
	case 404: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 405 */
	case 405: {
		semValue = PN_SEM(3, 2);
		checkEmptyPropertyHookList(PN_SEM(3, 2), stackPos - (3 - 1));
		return true;
	}
	/* rule 406 */
	case 406: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("flags", zv::Val::copyOf(PN_SEM(5, 2)));
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(5, 3)));
		sub1.set("params", zv::Arr::empty());
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(5, 1)));
		semValue = newNodeCtor("Node\\PropertyHook", PN_ATTRS(5, 1, 5), PN_SEM(5, 4), PN_SEM(5, 5), sub1);
		checkPropertyHook(semValue.ref(), 0, false);
		return true;
	}
	/* rule 407 */
	case 407: {
		zv::Arr sub1 = zv::Arr::empty();
		sub1.set("flags", zv::Val::copyOf(PN_SEM(8, 2)));
		sub1.set("byRef", zv::Val::copyOf(PN_SEM(8, 3)));
		sub1.set("params", zv::Val::copyOf(PN_SEM(8, 6)));
		sub1.set("attrGroups", zv::Val::copyOf(PN_SEM(8, 1)));
		semValue = newNodeCtor("Node\\PropertyHook", PN_ATTRS(8, 1, 8), PN_SEM(8, 4), PN_SEM(8, 8), sub1);
		checkPropertyHook(semValue.ref(), stackPos - (8 - 5), true);
		return true;
	}
	/* rule 408 */
	case 408: {
		semValue = zv::Val::null();
		return true;
	}
	/* rule 409 */
	case 409: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 410 */
	case 410: {
		semValue = PN_SEM(3, 2);
		return true;
	}
	/* rule 411 */
	case 411: {
		semValue = zv::Val::integer(0);
		return true;
	}
	/* rule 412 */
	case 412: {
		checkPropertyHookModifiers(PN_SEM(2, 1).toLong(), PN_SEM(2, 2).toLong(), stackPos - (2 - 2));
		semValue = zv::Val::integer(PN_SEM(2, 1).toLong() | PN_SEM(2, 2).toLong());
		return true;
	}
	/* rule 415 */
	case 415: {
		pushOnto(PN_SEM(3, 1), PN_SEM(3, 3));
		semValue = PN_SEM(3, 1);
		return true;
	}
	/* rule 416 */
	case 416: {
		semValue = arrayOf(PN_SEM(1, 1));
		return true;
	}
	/* rule 417 */
	case 417: {
		semValue = zv::Arr::empty();
		return true;
	}
	/* rule 420 */
	case 420: {
		semValue = newNode("Expr\\Assign", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 421 */
	case 421: {
		zv::Val t1 = fixupArrayDestructuring(PN_SEM(3, 1));
		semValue = newNode("Expr\\Assign", PN_ATTRS(3, 1, 3), t1, PN_SEM(3, 3));
		return true;
	}
	/* rule 422 */
	case 422: {
		semValue = newNode("Expr\\Assign", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 423 */
	case 423: {
		semValue = newNode("Expr\\AssignRef", PN_ATTRS(4, 1, 4), PN_SEM(4, 1), PN_SEM(4, 4));
		return true;
	}
	/* rule 424 */
	case 424: {
		semValue = newNode("Expr\\AssignRef", PN_ATTRS(4, 1, 4), PN_SEM(4, 1), PN_SEM(4, 4));
		if (!(phpVersionId < 70000 /* PhpVersion::allowsAssignNewByReference() */)) {
			emitError("Cannot assign new by reference", PN_ATTRS(4, 1, 4));
		}
		return true;
	}
	/* rule 427 */
	case 427: {
		zv::Val t1 = newName(PN_SEM(2, 1), PN_ATTRS(2, 1, 1));
		semValue = newNode("Expr\\FuncCall", PN_ATTRS(2, 1, 2), t1, PN_SEM(2, 2));
		return true;
	}
	/* rule 428 */
	case 428: {
		semValue = newNode("Expr\\Clone_", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 429 */
	case 429: {
		semValue = newNode("Expr\\AssignOp\\Plus", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 430 */
	case 430: {
		semValue = newNode("Expr\\AssignOp\\Minus", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 431 */
	case 431: {
		semValue = newNode("Expr\\AssignOp\\Mul", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 432 */
	case 432: {
		semValue = newNode("Expr\\AssignOp\\Div", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 433 */
	case 433: {
		semValue = newNode("Expr\\AssignOp\\Concat", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 434 */
	case 434: {
		semValue = newNode("Expr\\AssignOp\\Mod", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 435 */
	case 435: {
		semValue = newNode("Expr\\AssignOp\\BitwiseAnd", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 436 */
	case 436: {
		semValue = newNode("Expr\\AssignOp\\BitwiseOr", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 437 */
	case 437: {
		semValue = newNode("Expr\\AssignOp\\BitwiseXor", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 438 */
	case 438: {
		semValue = newNode("Expr\\AssignOp\\ShiftLeft", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 439 */
	case 439: {
		semValue = newNode("Expr\\AssignOp\\ShiftRight", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 440 */
	case 440: {
		semValue = newNode("Expr\\AssignOp\\Pow", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 441 */
	case 441: {
		semValue = newNode("Expr\\AssignOp\\Coalesce", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 442 */
	case 442: {
		semValue = newNode("Expr\\PostInc", PN_ATTRS(2, 1, 2), PN_SEM(2, 1));
		return true;
	}
	/* rule 443 */
	case 443: {
		semValue = newNode("Expr\\PreInc", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 444 */
	case 444: {
		semValue = newNode("Expr\\PostDec", PN_ATTRS(2, 1, 2), PN_SEM(2, 1));
		return true;
	}
	/* rule 445 */
	case 445: {
		semValue = newNode("Expr\\PreDec", PN_ATTRS(2, 1, 2), PN_SEM(2, 2));
		return true;
	}
	/* rule 446 */
	case 446: {
		semValue = newNode("Expr\\BinaryOp\\BooleanOr", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 447 */
	case 447: {
		semValue = newNode("Expr\\BinaryOp\\BooleanAnd", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 448 */
	case 448: {
		semValue = newNode("Expr\\BinaryOp\\LogicalOr", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 449 */
	case 449: {
		semValue = newNode("Expr\\BinaryOp\\LogicalAnd", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 450 */
	case 450: {
		semValue = newNode("Expr\\BinaryOp\\LogicalXor", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 451 */
	case 451: {
		semValue = newNode("Expr\\BinaryOp\\BitwiseOr", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 452 */
	case 452: {
		semValue = newNode("Expr\\BinaryOp\\BitwiseAnd", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	/* rule 453 */
	case 453: {
		semValue = newNode("Expr\\BinaryOp\\BitwiseAnd", PN_ATTRS(3, 1, 3), PN_SEM(3, 1), PN_SEM(3, 3));
		return true;
	}
	default:
		return false;
	}
}

} // namespace phpstanturbo
