on: pull_request

name: Block merge commits

jobs:
  message-check:
    name: Block Merge Commits

    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit

      - name: Block Merge Commits
        uses: Morishiri/block-merge-commits-action@a4554c78def8d874966a8d1e20e2971121443755 # v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
