# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Build Issue Bot"

on:
  pull_request:
    paths:
      - 'issue-bot/**'
      - '.github/workflows/build-issue-bot.yml'
  push:
    branches:
      - "1.12.x"
    paths:
      - 'issue-bot/**'
      - '.github/workflows/build-issue-bot.yml'

env:
  COMPOSER_ROOT_VERSION: "1.12.x-dev"

concurrency:
  group: build-issue-bot-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
  cancel-in-progress: true

jobs:
  build-issue-bot:
    name: "Build Issue Bot"

    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        script:
          - "../bin/phpstan"
          - "vendor/bin/phpunit"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.3"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Install Issue Bot dependencies"
        working-directory: "issue-bot"
        run: "composer install --no-interaction --no-progress"

      - name: "Tests"
        working-directory: "issue-bot"
        run: ${{ matrix.script }}
