# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Lint"

on:
  pull_request:
  push:
    branches:
      - "2.2.x"

concurrency:
  group: lint-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # v2.37.1
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Downgrade PHPUnit"
        if: matrix.php-version == '7.4' || matrix.php-version == '8.0' || matrix.php-version == '8.1'
        run: "composer require --dev phpunit/phpunit:^9.6 sebastian/diff:^4.0 doctrine/instantiator:^1.0 --update-with-dependencies --ignore-platform-reqs"

      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v4.0.0

      - uses: ./.github/actions/downgrade-code
        with:
          php-version: "${{ matrix.php-version }}"

      - name: "Validate Composer"
        run: "composer validate"

      - name: "Lint"
        run: "make lint"

  coding-standards:
    name: "Coding Standard"

    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Checkout build-cs"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: "phpstan/build-cs"
          path: "build-cs"
          ref: "2.x"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # v2.37.1
        with:
          coverage: "none"
          php-version: "8.5"

      - name: "Validate Composer"
        run: "composer validate"

      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v4.0.0

      - name: "Install build-cs dependencies"
        uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v4.0.0
        with:
          working-directory: "build-cs"

      - name: "Lint"
        run: "make lint"

      - name: "Coding Standard"
        run: "make cs"

  dependency-analysis:
    name: "Dependency Analysis"

    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # v2.37.1
        with:
          coverage: "none"
          php-version: "8.5"

      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v4.0.0

      - name: "Composer Dependency Analyser"
        run: "make composer-dependency-analyser"

  name-collision:
    name: "Name Collision Detector"

    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # v2.37.1
        with:
          coverage: "none"
          php-version: "8.5"

      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v4.0.0

      - name: "Name Collision Detector"
        run: "make name-collision"
