# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Merge maintained branch

on:
  push:
    branches:
      - "2.1.x"

jobs:
  merge:
    name: Merge branch
    if: github.repository_owner == 'phpstan'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          ref: '2.2.x'
          token: "${{ secrets.PHPSTAN_BOT_TOKEN }}"
      - name: "Merge branch"
        run: |
          git config user.name "phpstan-bot"
          git config user.email "bot@phpstan.org"
          git merge --strategy=ort origin/${{ github.ref_name }} -m "Merge branch ${{ github.ref_name }} into 2.2.x"
          git push
