# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Merge maintained branch

on:
  push:
    branches:
      - "2.2.x"

jobs:
  merge:
    name: Merge branch
    if: github.repository_owner == 'phpstan'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          ref: '2.3.x'
          token: "${{ secrets.PHPSTAN_BOT_TOKEN }}"
      - name: "Merge branch"
        run: |
          git config --global user.name "phpstan-bot"
          git config --global user.email "ondrej+phpstanbot@mirtes.cz"
          git merge --strategy=ort origin/${{ github.ref_name }} -m "Merge branch ${{ github.ref_name }} into 2.3.x"
          git push
