# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Merge maintained branch

on:
  push:
    branches:
      - "2.1.x"

jobs:
  merge:
    name: Merge branch
    if: github.repository_owner == 'phpstan'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: '2.2.x'
          token: "${{ secrets.PHPSTAN_BOT_TOKEN }}"
      - name: "Merge branch"
        run: |
          git config --global user.name "phpstan-bot"
          git config --global user.email "ondrej+phpstanbot@mirtes.cz"
          git merge --strategy=ort origin/${{ github.ref_name }} -m "Merge branch ${{ github.ref_name }} into 2.2.x"
          git push
