# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Base PR on previous branch"

on:
  pull_request_target:
    types:
      - opened
    branches:
      - '2.3.x'


permissions:
  contents: read

jobs:
  comment:
    name: "Comment on pull request"
    runs-on: 'ubuntu-latest'

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Comment PR
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          body: "You've opened the pull request against the latest branch 2.3.x. PHPStan 2.3 is not going to be released for months. If your code is relevant on 2.2.x and you want it to be released sooner, please rebase your pull request and change its target to 2.2.x."
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
