# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Pull request ready for review"

on:
  pull_request_target:
    types:
      - ready_for_review

jobs:
  comment:
    name: "Comment on pull request"
    runs-on: 'ubuntu-latest'

    steps:
      - name: Comment PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          body: "This pull request has been marked as ready for review."
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
