# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Pull request ready for review"

on:
  pull_request_target:
    types:
      - ready_for_review

permissions:
  contents: read

jobs:
  comment:
    name: "Comment on pull request"
    runs-on: 'ubuntu-latest'

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Comment PR
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          body: "This pull request has been marked as ready for review."
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
