# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Reflection golden test"

on:
  pull_request:
    paths-ignore:
      - 'compiler/**'
      - 'apigen/**'
      - 'changelog-generator/**'
      - 'issue-bot/**'
  push:
    branches:
      - "2.1.x"
    paths-ignore:
      - 'compiler/**'
      - 'apigen/**'
      - 'changelog-generator/**'
      - 'issue-bot/**'

env:
  REFLECTION_GOLDEN_TEST_FILE: "/tmp/reflection-golden.test"
  REFLECTION_GOLDEN_SYMBOLS_FILE: "/tmp/reflection-golden-symbols.txt"

concurrency:
  group: reflection-golden-test-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
  cancel-in-progress: true

jobs:
  dump-php-symbols:
    name: "Dump PHP symbols"
    runs-on: "ubuntu-latest"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # v2.37.1
        with:
          coverage: "none"
          php-version: "8.3"
          # Include exotic extensions to discover more symbols
          extensions: ds,mbstring,runkit7,scoutapm,seaslog,simdjson,var_representation,yac

      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v4.0.0

      - name: "Dump phpSymbols.txt"
        run: "php tests/dump-reflection-test-symbols.php"

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: phpSymbols
          path: ${{ env.REFLECTION_GOLDEN_SYMBOLS_FILE }}

  reflection-golden-test:
    name: "Reflection golden test"
    needs: dump-php-symbols
    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: phpSymbols
          path: /tmp

      - name: "Checkout base commit"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.base.sha || github.event.before }}

      - name: "Install PHP"
        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # v2.37.1
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl
          extensions: ds,mbstring
          ini-file: development
          ini-values: memory_limit=2G

      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v4.0.0

      - name: "Dump previous reflection data"
        run: "php tests/generate-reflection-test.php"

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: reflection-${{ matrix.php-version }}.test
          path: ${{ env.REFLECTION_GOLDEN_TEST_FILE }}

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: "ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda" # v4.0.0

      - name: "Reflection golden test"
        run: |
          set +e
          make tests-golden-reflection
          exit_code="$?"

          if [[ "$exit_code" != "0" ]]; then
            echo "::notice file=.github/workflows/reflection-golden-test.yml,line=3 ::Reflection golden tests detected changes by this pull request - see https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          fi

          exit 0
