# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Update PhpStorm stubs"
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * 2'

permissions:
  contents: read

jobs:
  update-phpstorm-stubs:
    name: "Update PhpStorm stubs"
    if: ${{ github.repository == 'phpstan/phpstan-src' }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: 2.1.x
          fetch-depth: '0'
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
      - name: "Install PHP"
        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # v2.37.1
        with:
          coverage: "none"
          php-version: "8.2"
      - uses: "ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520" # v3
      - name: "Checkout stubs"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: "phpstorm-stubs"
          repository: "jetbrains/phpstorm-stubs"
      - name: "Update stubs"
        run: "composer require \"jetbrains/phpstorm-stubs:dev-master#$(git -C phpstorm-stubs rev-parse HEAD)\""
      - name: "Remove stubs repo"
        run: "rm -r phpstorm-stubs"
      - name: "Update function metadata"
        run: "./bin/generate-function-metadata.php"
      - name: "Create Pull Request"
        id: create-pr
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
          branch-suffix: random
          delete-branch: true
          title: "Update PhpStorm stubs"
          body: "Update PhpStorm stubs"
          committer: "phpstan-bot <ondrej+phpstanbot@mirtes.cz>"
          commit-message: "Update PhpStorm stubs"
