# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Update PhpStorm stubs"
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * 2'

permissions:
  contents: read

jobs:
  update-phpstorm-stubs:
    name: "Update PhpStorm stubs"
    if: ${{ github.repository == 'phpstan/phpstan-src' }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: 2.1.x
          fetch-depth: '0'
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
      - name: "Install PHP"
        uses: "shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1" # v2
        with:
          coverage: "none"
          php-version: "8.2"
      - uses: "ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520" # v3
      - name: "Checkout stubs"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          path: "phpstorm-stubs"
          repository: "jetbrains/phpstorm-stubs"
      - name: "Update stubs"
        run: "composer require \"jetbrains/phpstorm-stubs:dev-master#$(git -C phpstorm-stubs rev-parse HEAD)\""
      - name: "Remove stubs repo"
        run: "rm -r phpstorm-stubs"
      - name: "Update function metadata"
        run: "./bin/generate-function-metadata.php"
      - name: "Create Pull Request"
        id: create-pr
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ secrets.PHPSTAN_BOT_TOKEN }}
          branch-suffix: random
          delete-branch: true
          title: "Update PhpStorm stubs"
          body: "Update PhpStorm stubs"
          committer: "phpstan-bot <ondrej+phpstanbot@mirtes.cz>"
          commit-message: "Update PhpStorm stubs"
